/* Salam DMS · MVNO Digital Console — journeys data
   Step fields: n=name d=desc ep=endpoint ctl=controller svc=services
   intg=sync integrations, async={w:worker,q:queue,to:[systems]}, tbl=tables,
   st=state transition, ok=on-success, fail=[{at,why,fx}] */

const JOURNEYS = [

{id:"onb-physical", name:"New line — Physical SIM", tag:"APP/WEB", channel:"app/web",
 desc:"Anonymous user configures a new prepaid/postpaid line, verifies identity via Nafath, pays, and the SIM is couriered. Drives the OnboardingOrder AASM — <b>update_order</b> fires after every save. <b>Order placed at:</b> payment#initiate → Payment::CommitWorker.",
 steps:[
  {n:"Create / reuse order", d:"Start the wizard: new order or reuse an abandoned one.", ep:"POST /api/onboarding/orders", ctl:"Api::V1(V5)::Onboarding::OrdersController#create", svc:["find_available_orders_to_be_reused","capture_utm_parameters"], intg:[], tbl:["onboarding_orders"], st:"→ plan_selection (initial / reseted)", ok:"Order id returned; wizard begins.", fail:[{at:"reuse", why:"expired reusable order", fx:"fresh order created instead"}]},
  {n:"Select plan", d:"Pick prepaid/postpaid plan; data-bundle plans auto-reserve a data number.", ep:"POST /api/onboarding/orders/:id/plans", ctl:"Api::V1(V3)::Onboarding::PlansController#create", svc:["OnboardingOrder#save_plan"], intg:["Oracle BSS"], tbl:["onboarding_orders","plans"], st:"update_order → sim_type_selection", ok:"Plan stored; state advances.", fail:[{at:"Oracle data_number", why:"no data numbers in inventory", fx:"data-bundle plan selection fails"}]},
  {n:"Select SIM type", d:"Physical (0) vs eSIM (1).", ep:"POST /api/onboarding/orders/:id/sim_type", ctl:"Api::V3::Onboarding::SimTypeController#create", svc:["save_sim_type"], intg:[], tbl:["onboarding_orders"], st:"→ number_order_type_selection", ok:"SIM type stored."},
  {n:"New vs MNP", d:"Fresh number (0) or port-in (1).", ep:"POST /api/onboarding/orders/:id/numbers/order_type", ctl:"Api::V1::Onboarding::NumbersController#order_type", svc:["save_number_order_type"], intg:[], tbl:["onboarding_orders"], st:"→ number_selection", ok:"Branches to number pick (or MNP info)."},
  {n:"Reserve MSISDN", d:"Browse inventory / vanities and reserve the number in BSS.", ep:"POST /api/onboarding/orders/:id/numbers/reserve", ctl:"Api::V1::Onboarding::NumbersController#reserve", svc:["NumberManager","save_number"], intg:["Oracle BSS"], tbl:["onboarding_orders","numbers","vanities"], st:"→ eligibility_check", ok:"Number held with expiry.", fail:[{at:"Oracle reserve", why:"number taken / inventory error", fx:"409 — user picks another number"}]},
  {n:"Eligibility (CITC)", d:"Line-count / regulatory eligibility for the ID.", ep:"POST /api/onboarding/orders/:id/eligibility/is_eligible", ctl:"Api::V1::Onboarding::EligibilityController#is_eligible", svc:["save_eligibility","SematiAbsherUserType"], intg:["Oracle BSS"], tbl:["onboarding_orders","eligibility_logs","nationalities"], st:"→ account_details", ok:"ID may own another line.", fail:[{at:"CITC check", why:"max lines reached / blocked ID", fx:"journey ends — not eligible"}]},
  {n:"Customer info", d:"Email, mobile, name; v5 adds TCC mobile-ownership check.", ep:"POST /api/onboarding/orders/:id/customer_info", ctl:"Api::V1(V5)::Onboarding::OrdersController#customer_info", svc:["save_customer_info","tcc_mobile_verify (v5)"], intg:["TCC"], tbl:["onboarding_orders"], st:"→ account_verification (OTP auto-sent)", ok:"OTP dispatched to contact number.", fail:[{at:"TCC verify", why:"contact number not owned by this ID", fx:"blocked in prod (v5)"}]},
  {n:"Verify OTP", d:"SMS OTP on the contact number.", ep:"POST /api/otp/verify", ctl:"Api::V1::OtpController#verify", svc:["OtpVerification","handle_onboarding_otp"], intg:["Unifonic / Msegat"], tbl:["otp_verifications"], st:"mobile_number_verified → account_password", ok:"Contact number proven.", fail:[{at:"OTP", why:"wrong code / attempts exceeded (Redis limits)", fx:"resend or lockout"}]},
  {n:"Set password", d:"Future selfcare login credential.", ep:"POST /api/onboarding/orders/:id/profiles/customer_password", ctl:"Api::V1::Onboarding::ProfilesController#create", svc:["save_customer_password"], intg:[], tbl:["onboarding_orders"], st:"→ delivery_details", ok:"has_password set."},
  {n:"Nafath identity", d:"Regulatory KYC: authorize → user approves in Nafath app → callback → poll.", ep:"POST /api/semati/authorize → GET /api/semati/check", ctl:"Api::SematiController#authorize/#check", svc:["IamNew"], intg:["Nafath / IAM"], tbl:["nafath_logs","onboarding_orders"], st:"IAM token cached in Redis (15 min)", ok:"PersonId stored; token ready for activation.", fail:[{at:"Nafath", why:"user rejects / 15-min TTL expires", fx:"re-authorize required"}]},
  {n:"Delivery info", d:"Address + lat/lng, delivery vs pickup, time slot.", ep:"POST /api/onboarding/orders/:id/delivery_info", ctl:"Api::V1::Onboarding::OrdersController#delivery_info", svc:["save_delivery_info"], intg:["Google Maps"], tbl:["onboarding_orders","geofences"], st:"→ payment (payment_guard)", ok:"Order ready to pay.", fail:[{at:"geofence", why:"address outside delivery areas", fx:"pickup or different address"}]},
  {n:"Pay", d:"Initiate with the selected gateway; redirect; gateway webhook or client commit.", ep:"POST /api/payment/initiate (object_type=OnboardingOrder) → POST /payment/:vendor/callback", ctl:"Api::V1::PaymentController#initiate · CallbacksController#payment", svc:["PaymentManager#create_for_onboarding","#initiate_payment"], intg:["HyperPay","Tap","Tamara","SalamPay / Merchalink"], tbl:["payments"], st:"payment pending → success/failed", ok:"Payment success → CommitWorker enqueued.", fail:[{at:"gateway", why:"card declined / 3DS failed", fx:"payment failed — retry allowed"},{at:"number expiry", why:"reservation expired before payment", fx:"expired_guard → order expired"}]},
  {n:"Commit (async)", d:"Post-payment orchestration in Sidekiq.", ep:"— async —", ctl:"Payment::CommitWorker", svc:["Numbers::CommitWorker (extend reservation)","DeliveryManager.create_from_order"], intg:[], async:{w:"Payment::CommitWorker", q:"payment_commit", to:["Oracle BSS","SMSA","OTO","Barq"]}, tbl:["payments","onboarding_orders","delivery_requests"], st:"onboarding_orders.completed = true", ok:"Delivery request created at the chosen vendor.", fail:[{at:"vendor API", why:"shipment creation error", fx:"retry via Sidekiq; ops alert on Slack"}]},
  {n:"ZATCA e-invoice (async)", d:"KSA e-invoicing for the payment.", ep:"— async —", ctl:"ZatcaTransactionWorker::AfterBssWorker", svc:["ZatcaManager"], intg:[], async:{w:"ZatcaTransactionWorker", q:"zatca_transaction", to:["ZATCA (ClearTax)"]}, tbl:["payments","invoices"], st:"—", ok:"INV submitted; QR TLV stored.", fail:[{at:"ClearTax", why:"submission rejected", fx:"no retry (retry: false) — admin reprocess"}]},
  {n:"Delivery tracking", d:"Vendor webhooks normalize ~160 raw states to 6 statuses.", ep:"POST /delivery/:vendor/callback · GET /api/deliveries/requests", ctl:"CallbacksController#delivery · Api::V1::DeliveriesController#requests", svc:["DeliveryManager.process_callback","Oto::SignatureVerifier"], intg:["SMSA","OTO"], tbl:["delivery_requests"], st:"delivery status progression", ok:"Customer sees courier progress; SIM delivered.", fail:[{at:"callback", why:"unsigned/garbled payload (non-OTO vendors unverified)", fx:"status stuck — manual ops fix"}]},
  {n:"Activate SIM", d:"Customer activates the delivered SIM (see Self-activation journey).", ep:"POST /api/activation", ctl:"Api::V1::ActivationController#create", svc:["ActivationManager#activate"], intg:["Semati (CITC)","Oracle BSS"], tbl:["onboarding_orders","raw_sims","activation_logs"], st:"activated = true", ok:"Line live. Selfcare user auto-registered.", fail:[{at:"Semati", why:"error 726 mobile exists", fx:"Remedy ticket auto-created"},{at:"Oracle", why:"provisioning failure", fx:"Semati compensating cancel_mobile_number"}]}
 ]},

{id:"onb-esim", name:"New line — eSIM (QR)", tag:"APP/WEB", channel:"app/web",
 desc:"Same wizard as physical SIM but <b>sim_type = ESIM</b>: delivery is skipped (skip_the_delivery?), the ICCID is reserved from Oracle at activation, and the customer gets the eSIM profile as a QR (SM-DP+ link).",
 steps:[
  {n:"Wizard steps 1–10", d:"Identical to physical-SIM journey with sim_type=1; delivery_details_guard passes straight through.", ep:"(see New line — Physical SIM)", ctl:"Onboarding controllers", svc:["save_sim_type"], intg:["Oracle BSS","Nafath / IAM"], tbl:["onboarding_orders"], st:"… → payment (delivery skipped)", ok:"No delivery info needed."},
  {n:"Pay", d:"Standard payment backbone.", ep:"POST /api/payment/initiate", ctl:"Api::V1::PaymentController#initiate", svc:["PaymentManager#create_for_onboarding"], intg:["HyperPay","Tap","Tamara"], tbl:["payments"], st:"pending → success", ok:"CommitWorker enqueued.", fail:[{at:"gateway", why:"declined", fx:"retry"}]},
  {n:"Complete (no delivery)", d:"Commit without DeliveryManager for pure eSIM.", ep:"— async —", ctl:"Payment::CommitWorker", svc:["Numbers::CommitWorker"], intg:[], async:{w:"Payment::CommitWorker", q:"payment_commit", to:["Oracle BSS"]}, tbl:["onboarding_orders"], st:"completed = true", ok:"Order complete, awaiting activation."},
  {n:"Activate + reserve ICCID", d:"eSIM ICCID allocated from Oracle at activation time.", ep:"POST /api/activation", ctl:"Api::V1::ActivationController#create", svc:["Oracle::Esim#reserve_esim","IccidValidator","ActivationManager#activate"], intg:["Oracle BSS","Semati (CITC)"], tbl:["raw_sims","sim_uploads","onboarding_orders"], st:"activated = true", ok:"Line provisioned.", fail:[{at:"reserve_esim", why:"no eSIM stock", fx:"activation blocked"},{at:"Oracle", why:"provisioning error", fx:"eSIM unreserve + Semati cancel"}]},
  {n:"Fetch eSIM QR", d:"SM-DP+ activation QR from the subscription profile.", ep:"GET /api/onboarding/orders/esim_qr?mobile_number=…", ctl:"Api::V1::Onboarding::OrdersController#esim_qr", svc:["Qr#generate_qr","Oracle::Numbers#esim_qr_code"], intg:["Oracle BSS"], tbl:[], st:"—", ok:"Customer scans QR — eSIM installed."}
 ]},

{id:"mnp", name:"MNP port-in", tag:"APP/WEB", channel:"app/web",
 desc:"New-line wizard with <b>number_order_type = MNP</b>: donor number/operator instead of number pick; activation runs the Semati transfer + Oracle MNP APIs.",
 steps:[
  {n:"Wizard start", d:"Order, plan, SIM type as usual.", ep:"POST /api/onboarding/orders → …/sim_type", ctl:"Onboarding controllers", svc:[], intg:[], tbl:["onboarding_orders"], st:"→ number_order_type_selection", ok:"—"},
  {n:"Choose MNP", d:"order_type=1 branches the state machine.", ep:"POST /api/onboarding/orders/:id/numbers/order_type", ctl:"Api::V1::Onboarding::NumbersController#order_type", svc:["save_number_order_type"], intg:[], tbl:["onboarding_orders"], st:"→ mnp_info (guard is_mnp?)", ok:"—"},
  {n:"Donor info", d:"Donor MSISDN + operator; availability probed in BSS.", ep:"POST /api/onboarding/orders/:id/mnp", ctl:"Api::V1::Onboarding::MnpController#create", svc:["save_mnp_info","mnp_number_available?"], intg:["Oracle BSS"], tbl:["onboarding_orders","mnp_operators"], st:"→ eligibility_check", ok:"Donor number valid for port.", fail:[{at:"availability", why:"number not portable / already Salam", fx:"rejected"}]},
  {n:"Eligibility → Nafath → Pay", d:"Standard steps 6–12 of the physical journey (blank SIM still delivered unless eSIM).", ep:"(shared steps)", ctl:"Onboarding + Semati + Payment controllers", svc:[], intg:["Oracle BSS","Nafath / IAM","HyperPay"], tbl:["onboarding_orders","payments"], st:"… → payment", ok:"—"},
  {n:"Commit", d:"MNP branch: no reservation extension.", ep:"— async —", ctl:"Payment::CommitWorker", svc:["DeliveryManager.create_from_order"], intg:[], async:{w:"Payment::CommitWorker", q:"payment_commit", to:["SMSA","OTO"]}, tbl:["onboarding_orders","delivery_requests"], st:"completed = true", ok:"SIM shipped."},
  {n:"Activate / port", d:"Semati transfer + Oracle MNP with compensations on failure.", ep:"POST /api/activation", ctl:"Api::V1::ActivationController#create → ActivationManager#mnp_activation", svc:["Oracle::Activation#semati_transfer_number","#create_account","#mnp"], intg:["Semati (CITC)","Oracle BSS"], tbl:["onboarding_orders","activation_logs","raw_sims"], st:"activated = true", ok:"Port executed; donor line moves to Salam.", fail:[{at:"Semati transfer", why:"donor operator rejects", fx:"cancel_mobile_number compensation"},{at:"Oracle", why:"MNP order fails", fx:"port aborted; eSIM unreserved"}]},
  {n:"Cancel pending port", d:"Public cancel with OTP.", ep:"POST /api/mnp/cancel_mnp → /api/mnp/cancel_mnp_otp", ctl:"Api::V1::MnpController#cancel_mnp/#cancel_mnp_otp", svc:["MnpManager","AccountManager"], intg:["Oracle BSS","TCC"], tbl:["cancel_mnp_logs","otps"], st:"—", ok:"Port request withdrawn."}
 ]},

{id:"nafath", name:"Nafath / Absher KYC (Semati)", tag:"ALL", channel:"app/web/dealer/kiosk",
 desc:"Regulatory KYC gate used by onboarding, activation, plan change (pre↔post), ownership transfer and SIM replacement. Shared concern <b>Api::SematiController</b> mounted at /api/semati, /api/apollo/semati and /api/sedco/semati.",
 steps:[
  {n:"Start verification", d:"Nafath (citizens/residents v1, visitors v2) or Absher branch.", ep:"POST /api/semati/authorize", ctl:"Api::SematiController#authorize / #absher_authorize", svc:["IamNew#authorize","Oracle::Absher#create_absher_token"], intg:["Nafath / IAM","Absher"], tbl:["nafath_logs","onboarding_orders"], st:"Redis {trans_id}* keys (15 min TTL)", ok:"Random-number challenge shown to user.", fail:[{at:"IAM", why:"service down / invalid ID", fx:"cannot start KYC"}]},
  {n:"User approves in Nafath app", d:"Out-of-band approval on the customer's phone.", ep:"— out of band —", ctl:"Nafath mobile app", svc:[], intg:["Nafath / IAM"], tbl:[], st:"—", ok:"User taps the matching number.", fail:[{at:"user", why:"rejects or ignores challenge", fx:"TTL expiry → re-authorize"}]},
  {n:"IAM callback", d:"Nafath posts the JWT result to the backend.", ep:"POST /eChannels/iam/callback", ctl:"CallbacksController#iam_new", svc:["JWT decode (⚠ no signature verification)"], intg:["Nafath / IAM"], tbl:["nafath_logs","onboarding_orders"], st:"extra_person_id stored; token cached", ok:"Verification result recorded."},
  {n:"Poll result", d:"Client polls until the Redis cache has the outcome.", ep:"GET /api/semati/check", ctl:"Api::SematiController#check", svc:["Redis trans_id cache"], intg:[], tbl:[], st:"—", ok:"Front-end proceeds with wizard."},
  {n:"Re-auth active user", d:"For SIM replacement / spam unlock: ID match + OTP then re-run authorize.", ep:"PATCH /api/semati/authorize_active_user → POST …_otp", ctl:"Api::SematiController#authorize_active_user(_otp)", svc:["AccountManager","Otp (validate_active_user)"], intg:["Oracle BSS","Nafath / IAM"], tbl:["otps","nafath_logs"], st:"—", ok:"Existing customer re-verified."},
  {n:"Register number on Semati", d:"Post-login remediation for unregistered numbers.", ep:"POST /api/users/register_number_on_semati (v2)", ctl:"Api::V2::UsersController#register_number_on_semati", svc:["Semati service"], intg:[], async:{w:"Oracle::RegisterNumberOnSematiWorker", q:"change_plan", to:["Semati (CITC)"]}, tbl:["missing_semati_lists","nafath_logs"], st:"—", ok:"Number registered with regulator."}
 ]},

{id:"activation", name:"SIM self-activation", tag:"APP", channel:"app",
 desc:"Customer who received the SIM activates the line: order lookup by national ID, OTP, ICCID validation, Nafath, then BSS provisioning. v5 adds inventory checks, v12 adds dealer re-pick.",
 steps:[
  {n:"Find pending orders + OTP", d:"Match pending_activation orders by national ID; OTP to verified mobile.", ep:"GET/POST /api/activation/orders", ctl:"Api::V1(V5/V12)::ActivationController#orders", svc:["OnboardingOrder.pending_activation","OtpVerification#deliver!"], intg:["Unifonic / Msegat"], tbl:["onboarding_orders","otp_verifications"], st:"—", ok:"Order list unlocked after OTP."},
  {n:"Verify OTP", d:"Pick the order to activate.", ep:"POST /api/otp/verify", ctl:"Api::V1::OtpController#verify", svc:["OtpVerification"], intg:[], tbl:["otp_verifications"], st:"—", ok:"—", fail:[{at:"OTP", why:"attempt limit", fx:"lockout window"}]},
  {n:"Validate ICCID", d:"Scanned SIM must exist in BSS with state '1' and pass inventory checks.", ep:"GET /api/activation/validate_iccid", ctl:"Api::V1(V5)::ActivationController#validate_iccid", svc:["Oracle::Activation#get_card_package","IccidValidator"], intg:["Oracle BSS"], tbl:["raw_sims"], st:"—", ok:"SIM is activatable.", fail:[{at:"card package", why:"wrong state / visitor inventory", fx:"rejected ICCID"}]},
  {n:"Nafath KYC", d:"Standard Semati flow (see Nafath journey).", ep:"POST /api/semati/authorize → GET /api/semati/check", ctl:"Api::SematiController", svc:["IamNew"], intg:["Nafath / IAM"], tbl:["nafath_logs"], st:"IAM token cached", ok:"Identity proven."},
  {n:"Activate", d:"normal_activation: semati_new_number → create_account → subscriber → supplementary → CSA docs → initial balance.", ep:"POST /api/activation", ctl:"Api::V1::ActivationController#create → ActivationManager#activate", svc:["Oracle::Activation#*","RawSim.redeem"], intg:["Semati (CITC)","Oracle BSS","Absher"], tbl:["onboarding_orders","raw_sims","sim_uploads","activation_logs"], st:"activated = true · activated_platform set", ok:"Line live.", fail:[{at:"Oracle step", why:"any BSS step fails", fx:"compensating Semati cancel_mobile_number"},{at:"Semati 726", why:"mobile already exists", fx:"Remedy::SematiTicketWorker ticket"}]},
  {n:"Auto-register selfcare user", d:"Same request creates the app account from order data.", ep:"(same request)", ctl:"#cleanup_user / #register_user", svc:["User.set_from_Oracle"], intg:["Oracle BSS"], tbl:["users","customers"], st:"—", ok:"User can log in immediately."},
  {n:"eSIM QR (if eSIM)", d:"Profile link in response or via public endpoint.", ep:"GET /api/onboarding/orders/esim_qr", ctl:"Onboarding::OrdersController#esim_qr", svc:["Qr","Oracle::Numbers#esim_qr_code"], intg:["Oracle BSS"], tbl:[], st:"—", ok:"eSIM installed."}
 ]},

{id:"qr-posa", name:"POSA / QR-POSA (dealer till)", tag:"POSA", channel:"POSA",
 desc:"Point-of-sale-activation SIMs. Classic POSA pays at the till; <b>QR-POSA is payment-less</b> — completion writes qr_posa_completions instead of payments, invoiced to ZATCA.",
 steps:[
  {n:"Create order with ICCID", d:"Scanned ICCID routes the flow: QR_POSA vendor ⇒ auto plan + data number.", ep:"POST /api/onboarding/orders (v5, iccid)", ctl:"Api::V5::Onboarding::OrdersController#create", svc:["QrPosaFlow.setup_order!","flow_type_qr_posa!/posa!"], intg:["Oracle BSS"], tbl:["onboarding_orders","raw_sims","sim_uploads"], st:"plan_selection → auto-advanced (QR-POSA)", ok:"ICCID cached 1 day against the order.", fail:[{at:"ICCID", why:"unknown vendor / not in inventory", fx:"order not created"}]},
  {n:"Wizard", d:"Standard steps; delivery skipped (skip_the_delivery?).", ep:"(shared wizard)", ctl:"v1/v3/v5 onboarding controllers", svc:[], intg:["Nafath / IAM"], tbl:["onboarding_orders"], st:"… → payment", ok:"—"},
  {n:"POSA payment (classic)", d:"Gateway payment; QR-POSA orders are REJECTED here.", ep:"POST /api/payment/initiate", ctl:"Api::V1::PaymentController#initiate", svc:["PaymentManager#create_for_onboarding"], intg:["HyperPay"], tbl:["payments"], st:"—", ok:"Paid at till."},
  {n:"QR-POSA completion (payment-less)", d:"Modem validation then complete without payment.", ep:"POST /api/onboarding/orders/:id/complete_qr_posa (v5)", ctl:"Api::V5::Onboarding::OrdersController#complete_qr_posa", svc:["QrPosaFlow.valid_modem?","QrPosaOrderCompleter#complete!"], intg:[], async:{w:"ZatcaTransactionWorker", q:"zatca_transaction", to:["ZATCA (ClearTax)","Oracle BSS"]}, tbl:["qr_posa_completions","onboarding_orders"], st:"completed = true (no payment)", ok:"INV e-invoice from qr_posa_completion.", fail:[{at:"modem", why:"invalid modem serial", fx:"completion blocked"}]},
  {n:"Activation + invoice QR", d:"v5/v12 activation with cached ICCID; TLV QR for the receipt.", ep:"POST /api/activation · GET /zatca/:invoice_number", ctl:"ActivationController · ZatcaController#generate", svc:["ActivationManager","ZatcaManager","Qr (TLV)"], intg:["Semati (CITC)","Oracle BSS","ZATCA (ClearTax)"], tbl:["onboarding_orders","invoices"], st:"activated = true", ok:"Line live; compliant receipt."}
 ]},

{id:"seller", name:"Seller indirect orders", tag:"DMS", channel:"dealer",
 desc:"A logged-in dealer creates orders for walk-in customers; payment is replaced by a <b>wallet deduction</b> from the seller's Oracle self-activation-portal balance; commission books on activation.",
 steps:[
  {n:"Seller login", d:"Password + OTP; JWT in Seller-Authorization header.", ep:"POST /api/sellers/sign_in → /api/sellers/verify_otp", ctl:"Api::V1::Sellers::AuthenticationController", svc:["SelfActivationManager#get_msisdn","JsonWebToken.encode"], intg:["Oracle BSS","Unifonic / Msegat"], tbl:["sellers","otp_verifications"], st:"—", ok:"Dealer session active."},
  {n:"Create order", d:"flow_type_indirect with seller_id; partner QR variant via seller_key.", ep:"POST /api/onboarding/orders (v5)", ctl:"Api::V5::Onboarding::OrdersController#create", svc:["flow_type_indirect!"], intg:[], tbl:["onboarding_orders","sellers"], st:"plan_selection", ok:"—"},
  {n:"Wizard", d:"Plans → number → eligibility → customer info → OTP → password → Nafath (no delivery).", ep:"(shared wizard)", ctl:"Onboarding + Semati controllers", svc:[], intg:["Oracle BSS","Nafath / IAM"], tbl:["onboarding_orders"], st:"… → payment", ok:"—"},
  {n:"Wallet check", d:"Seller balance in the self-activation portal.", ep:"GET /api/invoices/check_balance", ctl:"Api::V1::InvoicesController#check_balance", svc:["SelfActivationManager#balance"], intg:["Oracle BSS"], tbl:[], st:"—", ok:"Sufficient balance.", fail:[{at:"balance", why:"wallet too low", fx:"deduction refused"}]},
  {n:"Deduct from wallet", d:"Order completes WITHOUT a Payment row.", ep:"POST /api/invoices/deduct_amount/:order_id", ctl:"Api::V1::InvoicesController#deduct_amount", svc:["SelfActivationManager#deduct_amount"], intg:["Oracle BSS"], tbl:["seller_deductions","onboarding_orders"], st:"completed = true", ok:"SellerDeduction recorded; ZATCA from deduction."},
  {n:"Invoice customer", d:"Optional Hyperbill payment link to the end customer.", ep:"GET /api/invoices/send_invoice/:id", ctl:"Api::V1::InvoicesController#send_invoice", svc:[], intg:[], async:{w:"Payment::HyperbillSendInvoiceWorker", q:"payment_commit", to:["Hyperbill"]}, tbl:["invoices"], st:"—", ok:"Customer receives pay link.", fail:[{at:"Hyperbill", why:"link creation error", fx:"invoice retried/resend"}]},
  {n:"Customer pays link", d:"Hyperbill/Merchalink callback marks invoice paid.", ep:"POST|GET /hyperbill/callback", ctl:"CallbacksController#hyperbill", svc:["HyperbillResponse","PaymentManager"], intg:["Hyperbill"], tbl:["payments","invoices"], st:"invoice paid", ok:"Funds settled.", fail:[{at:"callback", why:"weak verification (TODO in code)", fx:"security note — trust boundary"}]},
  {n:"Activation + commission", d:"v12 activation; SelfActivationManager#process_commission.", ep:"POST /api/activation (v12)", ctl:"Api::V12::ActivationController#create", svc:["ActivationManager"], intg:["Semati (CITC)","Oracle BSS"], async:{w:"Oracle::CommissionWorker", q:"default", to:["Oracle BSS"]}, tbl:["onboarding_orders","seller_deductions"], st:"activated = true", ok:"Commission booked to the seller."}
 ]},

{id:"dealer-v12", name:"Dealer app servicing (v12)", tag:"DMS", channel:"dealer app · API-key",
 desc:"Server-to-server /api/apps/* namespace for the dealer/POSA application, plus the v12 activation flow letting the agent <b>re-pick a number</b> before activating.",
 steps:[
  {n:"Order QR", d:"Encrypted order-id QR (PNG) + ZATCA TLV QR.", ep:"GET /api/apps/orders/qr/:id · /api/apps/orders/qr_tlv", ctl:"Api::V1::Apps::OrdersController#qr/#qr_tlv", svc:["Qr#encrypt_string"], intg:[], tbl:[], st:"—", ok:"Scannable at the till."},
  {n:"Read order", d:"Order details for the agent.", ep:"GET /api/apps/orders/:id · /get_details/:id", ctl:"Apps::OrdersController#show/#get_details", svc:[], intg:[], tbl:["onboarding_orders","plans","numbers","payments"], st:"—", ok:"—"},
  {n:"Issue physical SIM", d:"Record the handed-out ICCID.", ep:"POST /api/apps/orders/update_issued_sim/:id", ctl:"Apps::OrdersController#update_issued_sim", svc:[], intg:[], tbl:["issued_sims"], st:"—", ok:"ICCID tied to order."},
  {n:"Social-security eligibility", d:"Government subsidised-plan check.", ep:"GET /api/apps/orders/check_social_security_eligibility", ctl:"Apps::OrdersController#check_social_security_eligibility", svc:["SocialSecurityEligibilityManager","PlanRuleMap"], intg:["SSE"], tbl:["plan_rule_maps"], st:"—", ok:"Discounted plan unlocked."},
  {n:"Payment check", d:"Gateway status for the order/checkout.", ep:"GET /api/apps/payment/check · /payment_status/:checkout_id", ctl:"Apps::PaymentController", svc:["PaymentManager#check_status"], intg:["HyperPay"], tbl:["payments","checkouts"], st:"—", ok:"—"},
  {n:"List orders (v12)", d:"Includes expired-number & OT orders; OTP-gated.", ep:"GET/POST /api/activation/orders (v12)", ctl:"Api::V12::ActivationController#orders", svc:[], intg:["Unifonic / Msegat"], tbl:["onboarding_orders"], st:"—", ok:"—"},
  {n:"Re-pick number", d:"Agent swaps an expired reservation for a fresh MSISDN/vanity.", ep:"GET /api/activation/:order_id/numbers · POST …/reserve · DELETE …/unreserve", ctl:"Api::V12::ActivationController#numbers/#reserve/#unreserve", svc:["NumberManager","NumbersPageKey"], intg:["Oracle BSS"], tbl:["numbers","vanities","onboarding_orders"], st:"—", ok:"Order rescued with a new number."},
  {n:"Cancel order", d:"Unreserve + status update.", ep:"POST /api/activation/:order_id/cancel", ctl:"Api::V12::ActivationController#cancel", svc:[], intg:["Oracle BSS"], tbl:["onboarding_orders"], st:"status → cancelled_aged/abandoned", ok:"—"},
  {n:"Activate", d:"Full activation incl. Semati-726 handling and commission for indirect.", ep:"POST /api/activation (v12)", ctl:"Api::V12::ActivationController#create", svc:["ActivationManager"], intg:["Semati (CITC)","Oracle BSS"], async:{w:"Oracle::CommissionWorker", q:"default", to:["Oracle BSS"]}, tbl:["onboarding_orders","seller_deductions"], st:"activated = true", ok:"—", fail:[{at:"Semati 726", why:"mobile already exists", fx:"Remedy ticket + agent guidance"}]}
 ]},

{id:"visitor", name:"Visitor / tourist (Hajj) plans", tag:"POSA/APP", channel:"POSA/app",
 desc:"Visitor buys a visitor plan; SIM handed at immigration/POSA. <b>Nafath v2</b> (visitor) or Absher visa-type identity; number auto-reserved; email OTP; no delivery.",
 steps:[
  {n:"Create visitor order", d:"visitor_hajj_flow flag applies visa type via SematiAbsherUserType.", ep:"POST /api/onboarding/orders (v5)", ctl:"Api::V5::Onboarding::OrdersController#create", svc:["VisitorHajjFlow.apply_visa_type_to_order!"], intg:[], tbl:["onboarding_orders","semati_absher_user_types"], st:"plan_selection", ok:"—"},
  {n:"Select visitor plan", d:"Forces physical SIM; re-applies visa type.", ep:"POST /api/onboarding/orders/:id/plans", ctl:"Onboarding::PlansController#create", svc:["save_plan"], intg:[], tbl:["onboarding_orders","plans"], st:"→ sim_type_selection+", ok:"—"},
  {n:"Scan SIM + auto number", d:"ICCID must be in visitor-hajj inventory; first free number auto-reserved.", ep:"POST /api/onboarding/orders/:id/visitor_hajj_iccid", ctl:"Api::V5::Onboarding::OrdersController#visitor_hajj_iccid", svc:["VisitorHajjFlow.iccid_and_reserve!","auto_reserve_first_number"], intg:["Oracle BSS"], tbl:["onboarding_orders","raw_sims","numbers"], st:"→ eligibility_check", ok:"SIM + number bound.", fail:[{at:"inventory", why:"ICCID not in visitor-hajj vendor stock", fx:"rejected"}]},
  {n:"Eligibility (visa)", d:"Visa type + number; BSS call skipped for visitors.", ep:"POST /api/onboarding/orders/:id/eligibility/is_eligible", ctl:"Onboarding::EligibilityController#is_eligible", svc:["save_eligibility"], intg:[], tbl:["onboarding_orders"], st:"→ account_details", ok:"—"},
  {n:"Customer info (email OTP)", d:"Visitor OTP via email; password guard bypassed.", ep:"POST /api/onboarding/orders/:id/customer_info", ctl:"Api::V5::Onboarding::OrdersController#customer_info", svc:[], intg:["SMTP"], tbl:["onboarding_orders","otp_verifications"], st:"→ account_verification → delivery_details", ok:"—"},
  {n:"Nafath v2 / Absher", d:"Visitor-journey person id.", ep:"POST /api/semati/authorize (use_v2)", ctl:"Api::SematiController", svc:["IamNew v2"], intg:["Nafath / IAM"], tbl:["nafath_logs"], st:"—", ok:"—"},
  {n:"Pay + complete", d:"No delivery request — SIM already in hand.", ep:"POST /api/payment/initiate", ctl:"PaymentController · Payment::CommitWorker", svc:["PaymentManager"], intg:["HyperPay"], async:{w:"Payment::CommitWorker", q:"payment_commit", to:["Oracle BSS"]}, tbl:["payments","onboarding_orders"], st:"completed = true", ok:"—"},
  {n:"Activate", d:"v5 activation with the immigration ICCID.", ep:"POST /api/activation (v5)", ctl:"Api::V5::ActivationController", svc:["ActivationManager (visitor semati config)"], intg:["Semati (CITC)","Oracle BSS"], tbl:["onboarding_orders"], st:"activated = true", ok:"Tourist line live."}
 ]},

{id:"ot", name:"Ownership transfer", tag:"APP", channel:"app",
 desc:"Owner initiates transfer (checkout type 5); recipient accepts by OTP, builds an onboarding order, pays dues and re-activates under their own ID via Nafath. Extra state: <b>initiated → sent → accepted → completed</b>.",
 steps:[
  {n:"Sender creates checkout", d:"checkout_type=5 with vanity + duplicate checks.", ep:"POST /api/checkout (type 5)", ctl:"Api::V1::CheckoutController#create_for_ownership_transfer", svc:["OwnershipTransferManager.check_vanity","pre_send"], intg:[], tbl:["checkouts"], st:"product_selection → contact_details · OT state initiated", ok:"—"},
  {n:"Recipient contact + OTP", d:"TCC ownership check of recipient number (prod).", ep:"POST /api/checkout/:id/customer_info(_otp)", ctl:"CheckoutController#customer_info/#customer_info_otp", svc:["Otp (transfer_new_user)"], intg:["TCC","Unifonic / Msegat"], tbl:["checkouts","otps"], st:"update_state → delivery_details", ok:"—", fail:[{at:"TCC", why:"recipient number not owned by their ID", fx:"blocked"}]},
  {n:"Submit request", d:"SMS invite to recipient; reminders scheduled.", ep:"POST /api/checkout/:id/submit", ctl:"CheckoutController#submit", svc:["Checkout#complete!","OwnershipTransferManager.post_send"], intg:[], async:{w:"Notifier::OwnershipTransferReminderWorker", q:"abandon_order_email_notifier", to:["Unifonic / Msegat"]}, tbl:["checkouts"], st:"OT state sent", ok:"Recipient invited."},
  {n:"Recipient verifies", d:"Public verify + OTP; validity window enforced.", ep:"POST /api/ownership_transfer/verify → /:id/verify_otp", ctl:"Api::V1::OwnershipTransferController", svc:["Setting.ownership_transfer_validity"], intg:["Unifonic / Msegat"], tbl:["otps","checkouts"], st:"OT state accepted", ok:"—", fail:[{at:"expiry", why:"validity window passed", fx:"OT state expired"}]},
  {n:"Recipient builds order", d:"Onboarding order flow_type_ownership_transfer; old owner pre-suspension.", ep:"POST /api/onboarding/orders (v5, order_id=checkout)", ctl:"Api::V5::Onboarding::OrdersController#create", svc:["OwnershipTransferManager.prepare_order","pre_acceptance"], intg:["Oracle BSS"], tbl:["onboarding_orders"], st:"wizard states replayed", ok:"—"},
  {n:"Eligibility / Nafath / plan", d:"Service transfer_ownership_local/global.", ep:"(shared wizard)", ctl:"Onboarding + Semati controllers", svc:[], intg:["Nafath / IAM","Oracle BSS"], tbl:["onboarding_orders","nafath_logs"], st:"… → payment", ok:"—"},
  {n:"Pay dues", d:"Number-expiry check skipped for OT.", ep:"POST /api/payment/initiate (OnboardingOrder)", ctl:"PaymentController#initiate", svc:["PaymentManager#create_for_onboarding"], intg:["HyperPay"], tbl:["payments"], st:"—", ok:"—"},
  {n:"Commit + old-owner termination", d:"OwnershipTransferPost terminates old owner in BSS, re-reserves, notifies.", ep:"— async —", ctl:"Payment::CommitWorker → OwnershipTransferManager.post_acceptance", svc:[], intg:[], async:{w:"OwnershipTransferPost", q:"default", to:["Oracle BSS","Unifonic / Msegat"]}, tbl:["onboarding_orders","checkouts"], st:"OT state completed", ok:"Line moves to recipient."},
  {n:"Re-activate under new owner", d:"add_update_supplementary_ownership_transfer branch.", ep:"POST /api/activation (v12)", ctl:"Api::V12::ActivationController#create", svc:["ActivationManager#normal_activation (OT branch)"], intg:["Semati (CITC)","Oracle BSS"], tbl:["onboarding_orders"], st:"activated = true", ok:"Ownership legally transferred."}
 ]},

{id:"change-plan", name:"Change Plan", tag:"APP", channel:"app",
 desc:"Upgrade/downgrade or prepaid↔postpaid switch. OTP-gated; payment (if due) via a CHANGE_PLAN checkout (type 2); the BSS switch runs in <b>ChangePlanWorker</b>. Pre↔post requires Nafath.",
 steps:[
  {n:"Eligible plans", d:"Filtered by ChangePlanEligibility, bundles, SIM type.", ep:"GET /api/change_plan/plans/prepaid|postpaid (v2)", ctl:"Api::V2::ChangePlanController#prepaid_plans/#postpaid_plans", svc:["ChangePlanEligibility"], intg:[], tbl:["plans","change_plan_eligibilities"], st:"—", ok:"—"},
  {n:"Switch eligibility", d:"CITC check for billing-type switch.", ep:"GET /api/change_plan/eligibility", ctl:"Api::V2::ChangePlanController#check_plan_switching_eligibility", svc:["Oracle::Activation#eligibility"], intg:["Oracle BSS"], tbl:[], st:"—", ok:"—", fail:[{at:"CITC", why:"line count / ID restrictions", fx:"switch refused"}]},
  {n:"Nafath (pre↔post only)", d:"IAM token cached as {mobile}_iam_token_response.", ep:"POST /api/change_plan/iam + semati flow", ctl:"Api::V2::ChangePlanController#change_plan_iam", svc:["IamNew (service change_plan)"], intg:["Nafath / IAM"], tbl:["nafath_logs"], st:"—", ok:"—"},
  {n:"Request change + OTP", d:"Due amount computed in CRM; checkout created/updated.", ep:"PATCH /api/change_plan/otp (v2/v8)", ctl:"Api::V2(V8)::ChangePlanController#change_plan", svc:["ChangePlanManager.calculate_change_plan_amount","Otp (change_plan)"], intg:["Oracle BSS","Unifonic / Msegat"], tbl:["checkouts","otps"], st:"checkout product_selection", ok:"—"},
  {n:"Verify OTP", d:"Oracle account must be ACTIVATED.", ep:"POST /api/change_plan/verify_otp", ctl:"ChangePlanController#change_plan_otp", svc:["Otp#verify!"], intg:["Oracle BSS"], tbl:["otps","checkouts"], st:"—", ok:"—"},
  {n:"Zero-payment path OR pay", d:"Postpaid-to-x with no dues switches synchronously; otherwise gateway payment.", ep:"POST /api/change_plan/process_postpaid OR POST /api/payment/initiate (change_plan)", ctl:"#change_plan_post / PaymentController#handle_change_plan", svc:["ChangePlanManager#switch! (sync)","PaymentManager#create_for_change_on_plan"], intg:["Oracle BSS","HyperPay"], tbl:["checkouts","payments","change_plan_logs"], st:"checkout completed (sync) or paid", ok:"—", fail:[{at:"payment", why:"declined", fx:"checkout stays unpaid"}]},
  {n:"BSS switch (async)", d:"Supplementary update, CSA docs (pre↔post), billing conversion, transactions.", ep:"— async —", ctl:"ChangePlanWorker", svc:["ChangePlanManager#switch!","Oracle::Account#convert_billing_type"], intg:[], async:{w:"ChangePlanWorker", q:"change_plan", to:["Oracle BSS","Semati (CITC)"]}, tbl:["change_plan_logs","checkouts","users"], st:"checkout paid/completed", ok:"Plan switched in BSS.", fail:[{at:"BSS", why:"switch fails mid-sequence (retry: false)", fx:"manual ops replay from change_plan_logs"}]}
 ]},

{id:"balance-transfer", name:"Balance / credit transfer", tag:"APP", channel:"app",
 desc:"(a) Prepaid credit transfer to another Salam number with fees + digital limits; (b) bundle/balance transfer between own numbers.",
 steps:[
  {n:"Eligibility + denominations", d:"Digital transfer limits + fees from settings.", ep:"GET /api/users/profile/denominations_eligibility", ctl:"Api::V1::ProfilesController#denominations_eligibility", svc:["Oracle::Balance#digital_transfer_limit"], intg:["Oracle BSS"], tbl:["credit_denominations"], st:"—", ok:"—"},
  {n:"Target eligibility", d:"Recipient must be an active Salam prepaid.", ep:"GET /api/numbers/credit_transfer_eligibility", ctl:"Api::V1::NumbersController#credit_transfer_eligibility", svc:["Oracle::Subscription"], intg:["Oracle BSS"], tbl:[], st:"—", ok:"—"},
  {n:"Initiate + OTP", d:"Limit checks then OTP (credit_transfer).", ep:"PATCH /api/users/profile/credit_transfer", ctl:"Api::V1::ProfilesController#credit_transfer", svc:["Otp"], intg:["Oracle BSS","Unifonic / Msegat"], tbl:["otps"], st:"—", ok:"—"},
  {n:"Confirm + execute", d:"DEBIT sender (amount+fee), CREDIT recipient; compensating CREDITs on failure; SMS both.", ep:"POST /api/users/profile/credit_transfer_otp", ctl:"Api::V1::ProfilesController#credit_transfer_otp", svc:["Oracle::Transaction"], intg:["Oracle BSS"], async:{w:"Notifier::SmsWorker", q:"sms_notifier", to:["Unifonic / Msegat"]}, tbl:["balance_transfer_logs","otps"], st:"—", ok:"Both parties notified.", fail:[{at:"BSS credit", why:"recipient credit fails after debit", fx:"compensating CREDIT back to sender"}]},
  {n:"Own-numbers transfer check", d:"Transferable bundles/balances list.", ep:"GET /api/users/check_transfer_balance", ctl:"Api::V1::UsersController#check_transfer_balance", svc:["Oracle::Balance#transfer_list"], intg:["Oracle BSS"], tbl:[], st:"—", ok:"—"},
  {n:"Own-numbers transfer", d:"Between MSISDNs of the same account.", ep:"POST /api/users/transfer_balance", ctl:"Api::V1::UsersController#transfer_balance", svc:["Oracle::Balance#transfer"], intg:["Oracle BSS"], tbl:["balance_transfer_logs"], st:"—", ok:"—"}
 ]},

{id:"recharge", name:"Recharge (voucher / card / dynamic)", tag:"APP/WEB", channel:"app/web · incl. anonymous",
 desc:"Scratch-card voucher redemption (also anonymous), denomination card recharge, and dynamic (arbitrary-amount) top-ups — all landing as Oracle subscription transactions.",
 steps:[
  {n:"Validate target", d:"Number/account status; also deactivated-postpaid variant.", ep:"GET /api/recharge/validate_details(_with_account)", ctl:"Api::V1::RechargeController#validate_details", svc:["AccountManager","TotalBillManager"], intg:["Oracle BSS"], tbl:[], st:"—", ok:"—"},
  {n:"Redeem voucher", d:"Voucher PIN redemption (user/guest/anonymous).", ep:"POST /api/recharge/voucher | /api/recharge/anonymous_voucher", ctl:"Api::V1::RechargeController#voucher", svc:["Oracle::Transaction (voucher)","Util.cache_clean"], intg:["Oracle BSS"], tbl:[], st:"—", ok:"Balance credited instantly.", fail:[{at:"voucher", why:"invalid/used PIN", fx:"rejected"}]},
  {n:"Card recharge (denomination)", d:"Gateway payment then BSS transaction (adj 32602).", ep:"POST /api/payment/initiate (recharge, denomination_id)", ctl:"PaymentController#handle_recharge", svc:["PaymentManager#create_for_recharge"], intg:["HyperPay"], async:{w:"Payment::CommitWorker", q:"payment_commit", to:["Oracle BSS"]}, tbl:["payments","recharge_options"], st:"—", ok:"—"},
  {n:"Dynamic recharge", d:"Arbitrary amount within min/max; VAT quoted then stripped in BSS post.", ep:"GET /api/dynamic_recharge/details → POST /api/dynamic_recharge/recharge → payment initiate", ctl:"Api::V1::DynamicRechargesController · PaymentController#handle_dynamic_recharge", svc:["Price (VAT)","PaymentManager#create_for_recharge"], intg:["HyperPay"], async:{w:"Payment::CommitWorker", q:"payment_commit", to:["Oracle BSS"]}, tbl:["payments","settings"], st:"—", ok:"—", fail:[{at:"amount", why:"outside min/max or postpaid line", fx:"rejected"}]}
 ]},

{id:"bill", name:"Bill payment (postpaid)", tag:"APP/WEB", channel:"app/web · incl. anonymous",
 desc:"View bills, download PDF, pay outstanding balance — full or partial, logged-in or anonymous — or pay a Hyperbill/Merchalink link.",
 steps:[
  {n:"Current bill + list", d:"Account balance and bill history.", ep:"GET /api/users/current_bill · GET /api/bill/list", ctl:"Api::V1::UsersController#current_bill · BillsController#list", svc:["Oracle::Account#query_bill","Oracle::Bills"], intg:["Oracle BSS"], tbl:[], st:"—", ok:"—"},
  {n:"Bill PDF", d:"BSS-rendered PDF.", ep:"GET /api/bill/generate_pdf", ctl:"Api::V1::BillsController#generate_pdf", svc:["Oracle::Bills#get_bill_pdf"], intg:["Oracle BSS"], tbl:[], st:"—", ok:"—"},
  {n:"Pay (logged in)", d:"account_transaction clears the bill cache.", ep:"POST /api/payment/initiate (bill)", ctl:"PaymentController#handle_bill", svc:["PaymentManager#create_for_bill","TotalBillManager"], intg:["HyperPay"], async:{w:"Payment::CommitWorker", q:"payment_commit", to:["Oracle BSS"]}, tbl:["payments"], st:"—", ok:"—"},
  {n:"Pay (anonymous, full/partial)", d:"By account id / mobile with partial_payment flag.", ep:"POST /api/payment/initiate (anonymous_bill)", ctl:"PaymentController#handle_anonymous_(partial_)bill", svc:["TotalBillManager.new_from_account_id","PartialBillManager"], intg:["HyperPay"], tbl:["payments"], st:"—", ok:"—"},
  {n:"Invoice-link payment", d:"Hyperbill/Merchalink link callbacks settle the invoice.", ep:"POST|GET /hyperbill/callback · /merchalink/callback", ctl:"CallbacksController#hyperbill/#merchalink", svc:["HyperbillResponse","PaymentManager#create_for_invoice"], intg:["Hyperbill","SalamPay / Merchalink"], tbl:["payments","invoices"], st:"invoice paid", ok:"—", fail:[{at:"callback", why:"weak signature verification", fx:"trust-boundary risk (noted in code)"}]}
 ]},

{id:"renewal", name:"Renewal + advanced postpaid", tag:"APP/WEB", channel:"app · web link",
 desc:"Manual prepaid plan renewal — from balance or by card (checkout type 6); external variant driven by a notification link without login. Advanced postpaid payment (type 7) credits the account ahead of the cycle.",
 steps:[
  {n:"Get renewal checkout", d:"Validates plan + balance.", ep:"GET /api/renewal/checkout", ctl:"Api::V1::RenewalsController#checkout", svc:["create_or_update_checkout_for_renewal"], intg:["Oracle BSS"], tbl:["checkouts"], st:"product_selection → delivery_details", ok:"—"},
  {n:"Request + OTP", d:"OTP msg_type renewal.", ep:"PATCH /api/renewal/renew", ctl:"RenewalsController#renew", svc:["Otp"], intg:["Unifonic / Msegat"], tbl:["otps"], st:"—", ok:"—"},
  {n:"Confirm — balance path", d:"renewal_transaction straight in BSS.", ep:"POST /api/renewal/renew_otp (pay_with=balance)", ctl:"RenewalsController#renew_otp", svc:["Oracle::Transaction#renewal_transaction"], intg:["Oracle BSS"], tbl:["checkouts"], st:"checkout completed", ok:"—", fail:[{at:"balance", why:"insufficient balance", fx:"card path suggested"}]},
  {n:"Confirm — card path", d:"Gateway then subscription+renewal transactions.", ep:"POST /api/payment/initiate (renewal)", ctl:"PaymentController#handle_renewal", svc:["PaymentManager#create_for_renewal"], intg:["HyperPay"], async:{w:"Payment::CommitWorker", q:"payment_commit", to:["Oracle BSS"]}, tbl:["payments","checkouts"], st:"checkout complete!", ok:"—"},
  {n:"External renewal (link)", d:"Unauthenticated checkout-id token from SMS/push link.", ep:"GET /api/external_renewal/checkout → PATCH …/renew → POST …/renew_otp → …/deduct_from_balance | card", ctl:"Api::V1::ExternalRenewalsController", svc:["AccountManager","Oracle::Transaction"], intg:["Oracle BSS","Unifonic / Msegat"], tbl:["checkouts","otps"], st:"—", ok:"Renewal without login."},
  {n:"Advanced postpaid payment", d:"Checkout type 7 → account credit (amount w/o VAT).", ep:"POST /api/checkout (type 7) → POST /api/payment/initiate (advanced_postpaid_payment)", ctl:"CheckoutController#create_for_advanced_postpaid_payment · PaymentController", svc:["PaymentManager#create_for_advanced_postpaid_payment"], intg:["HyperPay"], async:{w:"Payment::CommitWorker", q:"payment_commit", to:["Oracle BSS"]}, tbl:["checkouts","payments"], st:"product_selection → delivery_details", ok:"Account credited."}
 ]},

{id:"sim-replacement", name:"SIM replacement / eSIM swap", tag:"APP/WEB", channel:"app/web",
 desc:"Lost/damaged SIM or physical↔eSIM swap. <b>Double authentication</b> (password / email OTP / SMS OTP / Nafath re-auth), REPLACEMENT checkout (type 3), fee payment, then SimReplacementManager swaps the ICCID in BSS.",
 steps:[
  {n:"Validate number", d:"Subscription profile check.", ep:"GET /api/sim_replacement/validate_mobile_number", ctl:"Api::V1::SimReplacementController#validate_mobile_number", svc:["Oracle::Subscription"], intg:["Oracle BSS"], tbl:[], st:"—", ok:"—"},
  {n:"Validate identity", d:"ID/DOB vs Oracle profile; replacement checkout created (v8 stricter).", ep:"GET /api/sim_replacement/validate_user_details (v1/v8)", ctl:"Api::V1(V8)::SimReplacementController#validate_user_details", svc:["create_checkout_for_replacement"], intg:["Oracle BSS"], tbl:["checkouts"], st:"product_selection", ok:"—", fail:[{at:"identity", why:"ID/DOB mismatch", fx:"blocked"}]},
  {n:"Contact OTP", d:"OTP to the registered contact.", ep:"POST /api/sim_replacement/contact_number_otp", ctl:"#contact_number_otp", svc:["Otp (sim_replacement)"], intg:["Unifonic / Msegat"], tbl:["otps"], st:"—", ok:"—"},
  {n:"Double-auth", d:"Choose second factor: password, email/SMS OTP, or Nafath re-auth.", ep:"GET /:id/double_auth_list → PATCH /:id/double_auth → POST /:id/double_auth_otp", ctl:"#double_auth_list/#double_auth/#double_auth_otp", svc:["Otp","authorize_active_user (Nafath)"], intg:["Nafath / IAM","SMTP","Unifonic / Msegat"], tbl:["otps","checkouts"], st:"update_state → delivery_details/payment (eSIM skips delivery)", ok:"Strong proof of ownership.", fail:[{at:"double auth", why:"all factors fail", fx:"replacement refused"}]},
  {n:"Pay fee", d:"Replacement fee via gateway.", ep:"POST /api/payment/initiate (sim_replacement)", ctl:"PaymentController#handle_sim_replacement", svc:["PaymentManager#create_for_sim_replacement"], intg:["HyperPay"], tbl:["payments"], st:"—", ok:"—"},
  {n:"Deliver new SIM", d:"Physical + non-pickup ⇒ delivery request.", ep:"— async —", ctl:"Payment::CommitWorker", svc:["DeliveryManager.create_from_replacement_checkout"], intg:[], async:{w:"Payment::CommitWorker", q:"payment_commit", to:["SMSA","OTO"]}, tbl:["delivery_requests","checkouts"], st:"checkout paid", ok:"—"},
  {n:"Activate replacement", d:"ICCID swap in BSS; eSIM auto-reserves + QR.", ep:"POST /api/sim_replacement/:id/activate", ctl:"#activate", svc:["SimReplacementManager#proceed","Oracle::Esim#reserve_esim"], intg:["Oracle BSS","Semati (CITC)"], tbl:["checkouts","raw_sims"], st:"checkout completed", ok:"New SIM live; old SIM dead.", fail:[{at:"BSS swap", why:"card swap fails", fx:"old SIM stays active; retry"}]}
 ]},

{id:"termination", name:"Termination + refund", tag:"APP", channel:"app",
 desc:"Terminate a line: settle dues (postpaid), BSS deactivation with Semati release; refunds for recently-paid orders go through the gateway + ZATCA credit note. Retention hooks fire (CVM, Remedy).",
 steps:[
  {n:"Summary screens", d:"Plan + balance overview.", ep:"GET /api/users/profile/plan_summary · balance_summary", ctl:"Api::V1::ProfilesController", svc:["AccountManager"], intg:["Oracle BSS"], tbl:[], st:"—", ok:"—"},
  {n:"Init termination", d:"Payable amount / refundable balance & deposit.", ep:"GET /api/users/profile/terminate_number_init", ctl:"#terminate_number_init", svc:["ProfileManager"], intg:["Oracle BSS"], tbl:[], st:"—", ok:"—"},
  {n:"Request + OTP", d:"line_deactivation OTP; ref cached.", ep:"PATCH …/terminate_number → POST …/terminate_number_otp", ctl:"#terminate_number(_otp)", svc:["Otp"], intg:["Unifonic / Msegat"], tbl:["otps"], st:"—", ok:"—"},
  {n:"Settle dues (postpaid)", d:"balance+deposit via gateway then account_transaction.", ep:"POST /api/payment/initiate (termination)", ctl:"PaymentController#handle_termination", svc:["PaymentManager#create_for_termination"], intg:["HyperPay"], async:{w:"Payment::CommitWorker", q:"payment_commit", to:["Oracle BSS"]}, tbl:["payments"], st:"—", ok:"—"},
  {n:"Execute termination", d:"BSS state transition + Semati release; retention triggers.", ep:"POST /api/users/profile/terminate_number_process", ctl:"#terminate_number_process", svc:["ProfileManager#terminate_mobile_number"], intg:["Oracle BSS","Semati (CITC)"], async:{w:"Notifier::CvmWorker", q:"sms_notifier", to:["CVM"]}, tbl:["termination_logs","users"], st:"—", ok:"Line terminated; CVM mnpTrigger fired.", fail:[{at:"survey", why:"exit survey submitted", fx:"Remedy retention ticket created"}]},
  {n:"Delete selfcare profile", d:"Soft delete.", ep:"DELETE /api/users/profile/cancel_profile", ctl:"#cancel_profile", svc:[], intg:[], tbl:["deleted_users","users"], st:"—", ok:"—"},
  {n:"Refund (order/payment)", d:"Admin/Apollo initiated; gateway refund + ZATCA credit note + number unreserve.", ep:"POST /api/apollo/checkout/refund · ActiveAdmin", ctl:"Api::ApolloCheckoutController#refund · Refund.create_refund", svc:["PaymentManager#refund"], intg:[], async:{w:"Payment::RefundWorker", q:"payment_commit", to:["HyperPay","ZATCA (ClearTax)","Oracle BSS"]}, tbl:["refunds","refund_reasons","payments","installment_refunds"], st:"order status → refunded · number unreserved", ok:"Money back; CRN issued.", fail:[{at:"gateway refund", why:"refund API error", fx:"retry via worker; Slack alert"}]}
 ]},

{id:"saleor", name:"Saleor e-commerce (devices)", tag:"APP/WEB", channel:"app/web",
 desc:"Device shop backed by Saleor GraphQL. Backend wraps the cart in a SALEOR checkout (type 4), adds auth, payment, <b>installments (EMKAN/Tamara/Tasheel)</b>, delivery and ZATCA.",
 steps:[
  {n:"Shop login", d:"OTP login issuing user/guest token.", ep:"POST /api/saleor/login → /api/saleor/verify", ctl:"Api::V1::SaleorController#login/#verify", svc:["login_as_guest/anonymous"], intg:["Oracle BSS","Unifonic / Msegat"], tbl:["guests","users","otps"], st:"—", ok:"—"},
  {n:"Create checkout + attach cart", d:"Saleor cart/order queried over GraphQL into checkouts.extra (v9 = newer middleware).", ep:"POST /api/checkout (type 4) → POST /api/checkout/:id/saleor (v1/v9)", ctl:"Api::V1(V9)::CheckoutController#saleor", svc:["Saleor::Middleware#checkout/order"], intg:["Saleor"], tbl:["checkouts"], st:"product_selection → update_state", ok:"Cart snapshot (items, SKU, prices) stored.", fail:[{at:"GraphQL", why:"cart mismatch / price drift", fx:"re-sync required"}]},
  {n:"Contact + delivery", d:"OTP contact verification then address.", ep:"POST /api/checkout/:id/customer_info(_otp) → …/delivery_info", ctl:"CheckoutController", svc:["Deliverable concern","Otp"], intg:["Unifonic / Msegat"], tbl:["checkouts","otps"], st:"→ contact_details → delivery_details → payment", ok:"—"},
  {n:"Installments (optional)", d:"EMKAN voucher validate → pre_redeem → redeem; Tamara inside payment vendor.", ep:"POST /api/emkan/vouchers/validate_voucher → pre_redeem → redeem", ctl:"Api::V1::Emkan::VouchersController", svc:["Emkan service"], intg:["EMKAN"], async:{w:"Saleor::InstallmentWorker", q:"installment_worker", to:["Saleor"]}, tbl:["installments","installment_vendors","checkouts"], st:"payment_plan = INSTALLMENT", ok:"Financing approved.", fail:[{at:"EMKAN", why:"voucher invalid / limit", fx:"fall back to card"}]},
  {n:"Pay", d:"Standard backbone; Tamara authorize on pending.", ep:"POST /api/payment/initiate (saleor)", ctl:"PaymentController#handle_saleor", svc:["PaymentManager#create_for_saleor"], intg:["HyperPay","Tamara","Tap"], tbl:["payments","checkouts"], st:"pending → success", ok:"—"},
  {n:"Fulfil", d:"Delivery request + Saleor order confirm + stock sync.", ep:"— async —", ctl:"Payment::CommitWorker", svc:["DeliveryManager.create_from_saleor_checkout","SaleorStockProcessor"], intg:[], async:{w:"Delivery::SaleorWorker", q:"delivery", to:["Saleor","SMSA","OTO"]}, tbl:["delivery_requests","checkouts"], st:"checkout completed", ok:"Device shipped; order confirmed in Saleor."},
  {n:"ZATCA invoice", d:"e-invoice for the device sale.", ep:"— async —", ctl:"ZatcaTransactionWorker", svc:["ZatcaManager"], intg:[], async:{w:"ZatcaTransactionWorker", q:"zatca_transaction", to:["ZATCA (ClearTax)"]}, tbl:["invoices","payments"], st:"—", ok:"—"}
 ]},

{id:"datasim", name:"DataSIM (secondary data SIM)", tag:"APP", channel:"app",
 desc:"Companion data SIM for an existing customer (also orderable inside onboarding via require_data_sim). v1 = direct activate; v5 = OTP-gated with IAM.",
 steps:[
  {n:"Eligibility", d:"Plan must have has_data_sim; flags checked.", ep:"GET /api/datasims/is_eligible", ctl:"Api::V1::DatasimsController#is_eligible", svc:[], intg:[], tbl:["users","plans"], st:"—", ok:"—"},
  {n:"OTP (v5)", d:"Activation OTP.", ep:"GET /api/datasims/activate_otp → POST …/activate_otp_verify", ctl:"Api::V5::DatasimsController", svc:["Otp"], intg:["Unifonic / Msegat"], tbl:["otps"], st:"—", ok:"—"},
  {n:"Activate", d:"Card package + data number + subscriber creation with parent-line Semati person.", ep:"POST /api/datasims/activate (v1/v5)", ctl:"Api::V1(V5)::DatasimsController#activate", svc:["Oracle::Activation#get_card_package","Oracle::Numbers (data number)"], intg:["Oracle BSS","Semati (CITC)"], tbl:["users","raw_sims"], st:"require_data_sim set", ok:"Data SIM live.", fail:[{at:"inventory", why:"no data numbers / bad ICCID", fx:"activation blocked"}]},
  {n:"Delivery variant", d:"DATA_SIM checkout (type 1) with delivery request.", ep:"POST /api/checkout (type 1) → …/delivery_info → …/submit", ctl:"Api::V1::CheckoutController", svc:["DeliveryManager.create_from_checkout"], intg:[], async:{w:"Delivery::SmsaWorker", q:"smsa", to:["SMSA"]}, tbl:["checkouts","delivery_requests"], st:"product_selection → delivery_details → payment", ok:"Data SIM couriered."}
 ]},

{id:"apollo", name:"Apollo / Tygo partner channel", tag:"PARTNER", channel:"partner API · API-key",
 desc:"Aggregator partners resell Salam lines at /api/apollo/* (alias /api/tygo/*). Partner collects payment; backend records it via <b>confirm</b> (vendor APOLLO) and refunds via gateway.",
 steps:[
  {n:"Plans + numbers", d:"Catalog + inventory browse/reserve for the partner UI.", ep:"GET /api/apollo/plans · /numbers · POST /numbers/reserve", ctl:"Api::V1::Apollo::PlansController / NumbersController", svc:["NumberManager"], intg:["Oracle BSS"], tbl:["plans","numbers","vanities"], st:"—", ok:"—"},
  {n:"Eligibility", d:"CITC check for the customer ID.", ep:"POST /api/apollo/eligibility", ctl:"Api::V1::Apollo::EligibilityController#create", svc:["Oracle::Activation#eligibility"], intg:["Oracle BSS"], tbl:["eligibility_logs"], st:"—", ok:"—"},
  {n:"Nafath", d:"Partner-mounted Semati flow.", ep:"POST /api/apollo/semati/authorize → GET …/check", ctl:"Api::V1::Apollo::SematiController", svc:["IamNew"], intg:["Nafath / IAM"], tbl:["nafath_logs"], st:"—", ok:"—"},
  {n:"Create order", d:"ApolloOrderManager replays the whole wizard in one call.", ep:"POST /api/apollo/checkout", ctl:"Api::ApolloCheckoutController#create", svc:["ApolloOrderManager#save","create_otp"], intg:["Unifonic / Msegat"], tbl:["onboarding_orders","otps"], st:"wizard states → payment", ok:"—"},
  {n:"OTP confirm", d:"Customer OTP via partner UI.", ep:"POST /api/apollo/checkout/otp_confirm · otp_resend", ctl:"#otp_confirm/#otp_resend", svc:["Otp#verify!"], intg:[], tbl:["otps"], st:"—", ok:"—"},
  {n:"Confirm payment", d:"Partner-collected payment recorded (vendor APOLLO); delivery skipped if not required.", ep:"POST /api/apollo/checkout/confirm", ctl:"#confirm", svc:["PaymentManager#create_for_apollo","Payments::Apollo::Response"], intg:[], async:{w:"Payment::CommitWorker", q:"payment_commit", to:["Oracle BSS"]}, tbl:["payments","onboarding_orders"], st:"completed = true", ok:"—"},
  {n:"Activation", d:"Shared activation concern.", ep:"POST /api/apollo/activation", ctl:"Api::V1::Apollo::ActivationController", svc:["ActivationManager"], intg:["Semati (CITC)","Oracle BSS"], tbl:["onboarding_orders"], st:"activated = true", ok:"—"},
  {n:"eSIM handover", d:"Profile details + QR to the partner.", ep:"GET /api/apollo/checkout/esim_details · esim_qr", ctl:"#esim_details/#esim_qr", svc:["Oracle::Numbers#esim_qr_code","Qr"], intg:["Oracle BSS"], tbl:[], st:"—", ok:"—"},
  {n:"Refund", d:"Gateway refund + ZATCA credit note.", ep:"POST /api/apollo/checkout/refund", ctl:"#refund", svc:["Refund.create_refund"], intg:[], async:{w:"Payment::RefundWorker", q:"payment_commit", to:["HyperPay","ZATCA (ClearTax)"]}, tbl:["refunds","payments"], st:"order → refunded", ok:"—"},
  {n:"SMS relay", d:"Partner-triggered TCC SMS.", ep:"POST /api/apollo/tcc/sms/send", ctl:"Api::V1::Apollo::TccController#send_sms", svc:["Tcc service"], intg:["TCC"], tbl:[], st:"—", ok:"—"}
 ]},

{id:"services", name:"Services / VAS activation", tag:"APP", channel:"app",
 desc:"Boosters, roaming packs, data add-ons per plan; v11 adds OTP confirmation (incl. data-SIM MSISDNs). Postpaid service recharges ride the payment backbone (adj 50594).",
 steps:[
  {n:"Browse", d:"Services, groups, promoted; subscribed state from BSS.", ep:"GET /api/services · /api/services/:service · /service_groups", ctl:"Api::V1::ServicesController", svc:["ServiceManager"], intg:["Oracle BSS"], tbl:["services","service_groups","service_plans","plan_hidden_services"], st:"—", ok:"—"},
  {n:"Activate (v1)", d:"Balance check then provision.", ep:"POST /api/services/:service/activate", ctl:"Api::V1::ServicesController#activate", svc:["ServiceManager#activate"], intg:["Oracle BSS"], tbl:["service_logs"], st:"—", ok:"—", fail:[{at:"balance", why:"insufficient balance", fx:"recharge prompt"}]},
  {n:"Activate (v11, OTP)", d:"OTP msg_type activate_service.", ep:"POST /api/services/:service/activate → …/activate_otp", ctl:"Api::V11::ServicesController", svc:["Otp","ServiceManager"], intg:["Unifonic / Msegat","Oracle BSS"], tbl:["otps","service_logs"], st:"—", ok:"—"},
  {n:"Deactivate", d:"v1 direct; v11 OTP-gated.", ep:"POST /api/services/:service/deactivate(_otp)", ctl:"V1/V11::ServicesController#deactivate", svc:["ServiceManager#deactivate"], intg:["Oracle BSS"], tbl:["service_logs"], st:"—", ok:"—"},
  {n:"Postpaid service recharge", d:"Card payment then subscription transaction (adj 50594).", ep:"POST /api/payment/initiate (postpaid_service_recharge)", ctl:"PaymentController#handle_postpaid_service_recharge", svc:["PaymentManager#create_for_postpaid_service_recharge"], intg:["HyperPay"], async:{w:"Payment::CommitWorker", q:"payment_commit", to:["Oracle BSS"]}, tbl:["payments","services"], st:"—", ok:"—"}
 ]},

{id:"auth", name:"Login, registration & guest", tag:"APP", channel:"app",
 desc:"Password + OTP login for subscribers; registration against an active Salam number (v1/v5/v6/v7 variants); OTP-only guest sessions; device-bound anonymous tokens.",
 steps:[
  {n:"Device auth (anonymous)", d:"Device-bound JWT for pre-purchase browsing.", ep:"POST /api/auth/device", ctl:"Api::V1::AnonymousUsers::AuthenticationController#create", svc:["ApiGuard"], intg:[], tbl:["anonymous_users"], st:"—", ok:"16M anonymous devices in prod."},
  {n:"Sign-in (password)", d:"Oracle profile must be ACTIVATED; OTP sent.", ep:"POST /api/users/sign_in", ctl:"Api::V1::Users::AuthenticationController#create", svc:["Oracle::Subscription#get_subscription_profile","send_otp"], intg:["Oracle BSS","Unifonic / Msegat"], tbl:["users","customers","otps"], st:"—", ok:"—", fail:[{at:"Oracle", why:"account not ACTIVATED", fx:"login refused"}]},
  {n:"Verify OTP", d:"drift 180s; JWT issued.", ep:"POST /api/users/verify", ctl:"#verify", svc:["authenticate_otp","ApiGuard token"], intg:[], tbl:["users"], st:"—", ok:"Session live."},
  {n:"Registration", d:"is_registered → sign_up_otp(+verify) → sign_up; account built from Oracle + onboarding order.", ep:"POST /api/users/sign_up (v1/v5)", ctl:"Users::RegistrationController#create", svc:["User.set_from_Oracle","set_from_onboarding_order"], intg:["Oracle BSS"], tbl:["users","customers","onboarding_orders"], st:"—", ok:"—"},
  {n:"Guest session", d:"OTP-only subscriber session with Redis attempt limits.", ep:"POST /api/guests/sign_in → /api/guests/verify", ctl:"Api::V1::Guests::AuthenticationController", svc:["Otp","Redis limits"], intg:["Oracle BSS","Unifonic / Msegat"], tbl:["guests","otps"], st:"—", ok:"—"},
  {n:"Forgot / reset password", d:"OTP-gated reset.", ep:"POST /api/users/passwords/forgot → otp_verify → reset", ctl:"Api::V1::Users::PasswordsController", svc:["Otp (forgot_password)"], intg:["Unifonic / Msegat","SMTP"], tbl:["otps","users"], st:"—", ok:"—"}
 ]},

{id:"payment-backbone", name:"Payment backbone (shared)", tag:"ALL", channel:"all channels",
 desc:"The machinery every paid journey rides on: vendor selection per object type + platform, initiate, gateway webhook, client commit/poll, async fulfilment, ZATCA, refunds. <b>14 object types</b> ride this rail.",
 steps:[
  {n:"Vendor discovery", d:"PaymentVendor.select_vendor by object type + platform; installment options.", ep:"GET /api/payment/vendor · /api/payment/check", ctl:"Api::V1::PaymentController#vendor/#check", svc:["PaymentVendor.select_vendor"], intg:[], tbl:["payment_vendors"], st:"—", ok:"—"},
  {n:"Initiate", d:"14 object types: OnboardingOrder, Checkout, recharge, dynamic_recharge, bill, anonymous_bill, advanced_postpaid_payment, termination, change_plan, sim_replacement, postpaid_service_recharge, saleor, ownership_transfer, renewal.", ep:"POST /api/payment/initiate", ctl:"#initiate + handle_*", svc:["PaymentManager#create_for_*","validate_amount_limit"], intg:["HyperPay","Tap","Tamara","SalamPay / Merchalink"], tbl:["payments"], st:"payment pending", ok:"Redirect URL / checkout id to client.", fail:[{at:"validation", why:"amount limit / card validation", fx:"rejected before gateway"}]},
  {n:"Gateway webhook", d:"Vendor posts result; parse_response normalizes.", ep:"POST /payment/:vendor/callback (+ legacy vendor routes)", ctl:"CallbacksController#payment", svc:["PaymentManager#parse_response","Payment#update_commit_response"], intg:["HyperPay","Tap","Tamara"], tbl:["payments"], st:"pending → success/failed", ok:"CommitWorker enqueued on success.", fail:[{at:"verification", why:"only HyperPay (AES-GCM) + OTO (HMAC) verify authenticity", fx:"other callbacks weakly verified — hardening candidate"}]},
  {n:"Client confirm / poll", d:"Commit for redirect-return; status polling; Adjust purchase event.", ep:"POST /api/payment/:id/commit · GET /api/payment/:id/status", ctl:"#commit/#status", svc:["AdjustManager#event('purchase')"], intg:["Adjust"], tbl:["payments"], st:"—", ok:"—"},
  {n:"Fulfilment (async)", d:"Per payment_on_type: BSS transactions, delivery, checkout completion, plan switch, OT post-acceptance.", ep:"— async —", ctl:"Payment::CommitWorker", svc:["Oracle::Transaction","DeliveryManager","ChangePlanWorker","OwnershipTransferManager"], intg:[], async:{w:"Payment::CommitWorker", q:"payment_commit", to:["Oracle BSS","SMSA","Saleor"]}, tbl:["payments","onboarding_orders","checkouts","delivery_requests"], st:"object-specific", ok:"Business effect lands."},
  {n:"ZATCA", d:"INV per payment; CRN on refund; PDF + TLV QR.", ep:"— async — · GET /zatca/:invoice_number", ctl:"ZatcaTransactionWorker · ZatcaController#generate", svc:["ZatcaManager"], intg:[], async:{w:"ZatcaTransactionWorker", q:"zatca_transaction", to:["ZATCA (ClearTax)"]}, tbl:["payments","invoices"], st:"—", ok:"KSA compliance."},
  {n:"Refund", d:"Refund.create_refund → gateway → credit note → unreserve.", ep:"(admin / apollo)", ctl:"Payment::RefundWorker", svc:["PaymentManager#refund/refund_status"], intg:[], async:{w:"Payment::RefundWorker", q:"payment_commit", to:["HyperPay","ZATCA (ClearTax)","Oracle BSS"]}, tbl:["refunds","payments"], st:"payment → refunded", ok:"—"}
 ]},

{id:"guest-browse", name:"Guest browsing & lookups", tag:"APP/WEB", channel:"app/web · anonymous",
 desc:"Anonymous device token then plans, numbers/vanities, lookups (nationalities, operators, delivery areas, eSIM devices…), store locator, banners & surveys.",
 steps:[
  {n:"Device auth", d:"Anonymous JWT.", ep:"POST /api/auth/device", ctl:"Api::V1::AnonymousUsers::AuthenticationController#create", svc:["ApiGuard"], intg:[], tbl:["anonymous_users"], st:"—", ok:"—"},
  {n:"Plans + filters", d:"Prepaid/postpaid catalogs, categories, sort/filter options.", ep:"GET /api/plans(… /prepaid /postpaid /categories)", ctl:"Api::V1::PlansController", svc:[], intg:[], tbl:["plans","plan_categories","prices"], st:"—", ok:"—"},
  {n:"Numbers & vanities", d:"Inventory browse incl. enhanced numbers.", ep:"GET /api/numbers · /vanities · /enhanced_numbers", ctl:"Api::V1::NumbersController", svc:["NumberManager"], intg:["Oracle BSS"], tbl:["vanities","tmp_numbers"], st:"—", ok:"—"},
  {n:"Lookups", d:"Nationalities, operators, recharge options, delivery areas/cities, app config, eSIM devices, countries, denominations.", ep:"GET /api/lookup/*", ctl:"Api::V1::LookupController", svc:["DeliveryDay"], intg:[], tbl:["nationalities","mnp_operators","delivery_areas","settings","countries"], st:"—", ok:"—"},
  {n:"Store locator", d:"Nearest stores with distances.", ep:"GET /api/stores/get_stores", ctl:"Api::V1::StoresController#get_stores", svc:["StoresProcessor","DistanceCalculator"], intg:["Google Maps"], tbl:["stores","store_types"], st:"—", ok:"—"},
  {n:"Banners & surveys", d:"Content + campaign surfaces.", ep:"GET /api/categories · GET/POST /api/surveys · POST /api/apps/settings/banner", ctl:"Categories/Surveys/Apps::SettingsController", svc:[], intg:[], tbl:["categories","surveys","apps"], st:"—", ok:"—"}
 ]}
];
