/* infra.js — INFRASTRUCTURE (30 Sep 2026, alpha.120 — CIO requirement). Every server / node of the two HLDs with its physical
 * inventory, a per-host health report in the healthcheck-mail shape, infra alerts separated Mobile / Fixed, and the live
 * map: the HLD cards painted with status, cpu / mem / disk, NIC throughput, the edges with the traffic observed between
 * the hosts behind them. Server: server/src/infra.js. Route #infra (?tab=map|hosts|host|alerts|changes|sources &host=<id>
 * &diagram=mvno|fixed &seg= &q=). Dark mode through tokens; phone / iPad: tiles wrap, tables become cards. */
(function(){
  "use strict";
  const esc=s=>String(s==null?"":s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;");
  const API=window.API_BASE||window.CONSOLE_BASE||"";
  const api=(p,o)=>window.fetch(API+p,Object.assign({headers:{"Content-Type":"application/json"}},o||{})).then(r=>r.json().then(j=>{ if(!r.ok) throw new Error(j.error||("HTTP "+r.status)); return j; }));
  const SES=()=>window.opsSession?window.opsSession():{}; const caps=()=>{ const s=SES(); return (s.me&&s.me.caps)||{}; }; const canManage=()=>!!caps().manageSync;
  const ksa=iso=>{ if(!iso) return "—"; const d=new Date(iso); return isNaN(d)?"—":d.toLocaleString("en-GB",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",timeZone:"Asia/Riyadh"}); };
  const age=iso=>{ if(!iso) return "—"; const m=(Date.now()-new Date(iso).getTime())/60000; if(m<1) return "now"; if(m<60) return Math.round(m)+" min"; if(m<48*60) return Math.round(m/60)+" h"; return Math.round(m/1440)+" d"; };
  const n0=v=>v==null?"—":Number(v).toLocaleString("en-US"); const pct=v=>v==null?"—":Math.round(v)+"%";
  const bps=b=>b==null?"—":b>=1048576?(b/1048576).toFixed(1)+" MB/s":b>=1024?(b/1024).toFixed(0)+" kB/s":Math.round(b)+" B/s";
  const gb=mb=>mb==null?"—":(mb/1024).toFixed(mb>=10240?0:1)+" GB";
  const toast=m=>{ if(window.opsToast) window.opsToast(m); else console.warn(m); };
  const S={ tab:"map", diagram:"mvno", seg:"all", q:"", status:"all", host:"", data:null, det:null, map:null, timer:null, mapTimer:null, ready:false };
  const SEGL={mobile:"Mobile",fixed:"Fixed",shared:"Shared"};

  const CSS=`
  #view-infra .if-wrap{display:flex;flex-direction:column;gap:14px}
  #view-infra .if-head{display:flex;align-items:flex-start;gap:12px;flex-wrap:wrap} #view-infra .if-head h2{margin:0;font-size:20px} #view-infra .if-head .sub{color:var(--muted);font-size:12.5px;max-width:980px;line-height:1.45}
  #view-infra .if-head .sp{margin-left:auto;display:flex;gap:8px;align-items:center;flex-wrap:wrap}
  #view-infra .if-btn{border:1px solid var(--line);background:var(--card);color:var(--ink);border-radius:10px;padding:7px 12px;font:inherit;font-size:12.5px;font-weight:700;cursor:pointer} #view-infra .if-btn:hover{border-color:var(--green)} #view-infra .if-btn.p{background:var(--green);border-color:var(--green);color:#fff} #view-infra .if-btn[disabled]{opacity:.5;cursor:default}
  #view-infra .if-live{display:inline-flex;align-items:center;gap:6px;font-size:12px;color:var(--muted);border:1px solid var(--line);border-radius:999px;padding:5px 11px;background:var(--card)} #view-infra .if-live i{width:8px;height:8px;border-radius:50%;background:var(--good);display:inline-block} #view-infra .if-live.stale i{background:#d97706} #view-infra .if-live.err i{background:#dc2626}
  #view-infra .if-tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:10px}
  #view-infra .if-tile{border:1px solid var(--line);border-radius:14px;padding:12px 14px;background:var(--card);min-width:0} #view-infra .if-tile .l{font-size:10.5px;font-weight:800;letter-spacing:.06em;text-transform:uppercase;color:var(--muted)} #view-infra .if-tile .v{font-size:24px;font-weight:800;color:var(--ink);line-height:1.15;margin-top:3px} #view-infra .if-tile .v small{font-size:12px;color:var(--muted);font-weight:600;margin-left:6px} #view-infra .if-tile .s{font-size:11.5px;color:var(--muted);margin-top:4px;line-height:1.4}
  #view-infra .if-tile.crit{border-color:#dc2626} #view-infra .if-tile.warn{border-color:#d97706}
  #view-infra .if-tabs{display:flex;gap:4px;flex-wrap:wrap;border-bottom:1px solid var(--line)} #view-infra .if-tab{background:transparent;border:none;border-bottom:3px solid transparent;padding:9px 12px;font:inherit;font-size:13px;font-weight:700;color:var(--muted);cursor:pointer} #view-infra .if-tab.on{color:var(--green);border-bottom-color:var(--green)} #view-infra .if-tab b{font-size:10.5px;padding:1px 7px;border-radius:999px;border:1px solid var(--line);margin-left:5px;color:var(--muted)}
  #view-infra .if-tools{display:flex;gap:8px;flex-wrap:wrap;align-items:center} #view-infra .if-chip{border:1px solid var(--line);background:var(--card);color:var(--ink);border-radius:999px;padding:5px 11px;font:inherit;font-size:12px;font-weight:700;cursor:pointer} #view-infra .if-chip.on{border-color:var(--green);color:var(--green);background:var(--green-bg)} #view-infra .if-in{font:inherit;font-size:12.5px;padding:6px 11px;border:1px solid var(--line);border-radius:999px;background:var(--card);color:var(--ink);min-width:200px}
  #view-infra .if-tablew{overflow:auto;border:1px solid var(--line);border-radius:12px} #view-infra table.if{width:100%;border-collapse:collapse;font-size:12.5px;min-width:760px} #view-infra table.if th{position:sticky;top:0;background:var(--card2);color:var(--muted);font-size:10.5px;letter-spacing:.06em;text-transform:uppercase;text-align:left;padding:9px 10px;border-bottom:1px solid var(--line);white-space:nowrap} #view-infra table.if td{padding:8px 10px;border-bottom:1px solid var(--line-soft);vertical-align:top;color:var(--ink)} #view-infra table.if tr[data-host]{cursor:pointer} #view-infra table.if tr[data-host]:hover td{background:var(--green-bg)}
  #view-infra .if-st{display:inline-block;padding:2px 9px;border-radius:999px;font-size:10.5px;font-weight:800;border:1px solid var(--line);color:var(--ink-soft);background:var(--card2)} #view-infra .if-st.ok{color:var(--green);border-color:var(--green-line)} #view-infra .if-st.warn{color:#b45309;border-color:#f59e0b} #view-infra .if-st.crit{color:#b91c1c;border-color:var(--red-line)} #view-infra .if-st.unknown{color:var(--muted)}
  #view-infra .if-bar{display:inline-block;width:60px;height:7px;border-radius:4px;background:var(--line);overflow:hidden;vertical-align:middle;margin-right:5px} #view-infra .if-bar i{display:block;height:100%;background:var(--green)} #view-infra .if-bar.warn i{background:#f59e0b} #view-infra .if-bar.crit i{background:#dc2626}
  #view-infra .if-card{border:1px solid var(--line);border-radius:14px;background:var(--card);padding:14px 16px} #view-infra .if-card h4{margin:0 0 8px;font-size:13px} #view-infra .if-card h4 span{color:var(--muted);font-weight:400;font-size:12px}
  #view-infra .if-grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px} #view-infra .if-grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}
  #view-infra .if-kv{display:grid;grid-template-columns:150px 1fr;gap:5px 12px;font-size:12.5px} #view-infra .if-kv div:nth-child(odd){color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.05em;padding-top:2px}
  #view-infra .mono{font-family:ui-monospace,Menlo,monospace;font-size:11.5px}
  #view-infra .if-map{border:1px solid var(--line);border-radius:14px;overflow:hidden;background:#0b1020;position:relative} #view-infra .if-map iframe{width:100%;height:78vh;min-height:560px;border:0;display:block;background:#0b1020}
  #view-infra .if-legend{display:flex;gap:14px;flex-wrap:wrap;font-size:11.5px;color:var(--muted);padding:8px 12px;border-top:1px solid var(--line);background:var(--card)} #view-infra .if-legend i{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:5px;vertical-align:middle}
  #view-infra .if-spark{width:100%;height:56px;display:block}
  #view-infra .if-note{font-size:12px;color:var(--muted);line-height:1.5}
  #view-infra .if-form{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:8px} #view-infra .if-form label{font-size:11px;color:var(--muted);display:block;margin-bottom:3px;text-transform:uppercase;letter-spacing:.05em} #view-infra .if-form input,#view-infra .if-form select{width:100%;box-sizing:border-box;font:inherit;font-size:12.5px;padding:6px 9px;border:1px solid var(--line);border-radius:8px;background:var(--card2);color:var(--ink)}
  @media (max-width:860px){ #view-infra .if-grid2,#view-infra .if-grid3{grid-template-columns:1fr} #view-infra .if-kv{grid-template-columns:110px 1fr} #view-infra .if-map iframe{height:62vh} #view-infra table.if{min-width:0} #view-infra table.if thead{display:none} #view-infra table.if tr{display:block;border-bottom:1px solid var(--line);padding:6px 0} #view-infra table.if td{display:flex;gap:10px;border:0;padding:3px 10px} #view-infra table.if td::before{content:attr(data-l);min-width:84px;color:var(--muted);font-size:10.5px;text-transform:uppercase;letter-spacing:.05em;padding-top:2px} }`;

  function ensureView(){
    if(document.getElementById("ifCss")) return;
    const st=document.createElement("style"); st.id="ifCss"; st.textContent=CSS; document.head.appendChild(st);
    let v=document.getElementById("view-infra"); if(!v){ v=document.createElement("section"); v.id="view-infra"; v.className="view"; document.querySelector("main")?.appendChild(v); }
    v.innerHTML=`<div class="if-wrap">
      <div class="if-head"><div><h2>🖧 Infrastructure</h2><div class="sub">Every server and node of the two architecture diagrams — physical inventory, a health report per host in the same shape as the healthcheck mail, infrastructure alerts separated Mobile / Fixed, and the live map: the diagram cards painted with status, cpu · memory · disk and network throughput, the edges with the traffic observed between the hosts behind them. Read-only probes from the console box; no agent installed anywhere.</div></div>
        <div class="sp"><span class="if-live" id="ifLive"><i></i> loading</span><button class="if-btn" id="ifDisc" title="try the console's read-only ssh key on every host not yet flagged; the ones that answer get inventory and metrics from the next tick">⌕ Discover SSH access</button><button class="if-btn" id="ifRun" title="probe every host now (the scheduler does it every minute)">↻ Probe now</button><button class="if-btn" id="ifInv" title="re-read the inventory of every reachable host (daily otherwise)">⟳ Inventory</button></div></div>
      <div class="if-tiles" id="ifTiles"></div>
      <div class="if-tabs" id="ifTabs"></div>
      <div id="ifPanel"></div></div>`;
    v.querySelector("#ifRun").addEventListener("click",()=>run(false)); v.querySelector("#ifInv").addEventListener("click",()=>run(true));
    v.querySelector("#ifDisc").addEventListener("click",async()=>{ const b=v.querySelector("#ifDisc"); b.disabled=true; b.textContent="… trying every host"; try{ const r=await api("/api/infra/discover",{method:"POST",body:"{}"}); if(r.reason) toast(r.reason); else toast(`ssh: ${r.found} of ${r.tried} host(s) answer · ${r.newly} newly flagged${r.refused.length?" · refused: "+r.refused.slice(0,3).map(x=>x.ip).join(", ")+(r.refused.length>3?" …":""):""}`); if(r.newly) await run(true); else await load(); }catch(e){ toast(e.message); } finally{ b.disabled=false; b.textContent="⌕ Discover SSH access"; } });
    v.addEventListener("click",e=>{ const t=e.target.closest("[data-act]"); if(!t) return; const a=t.dataset.act;
      if(a==="tab"){ S.tab=t.dataset.tab; renderTabs(); renderPanel(); setHash(); }
      else if(a==="host"){ openHost(t.dataset.host); }
      else if(a==="seg"){ S.seg=t.dataset.seg; renderPanel(); setHash(); }
      else if(a==="status"){ S.status=t.dataset.status; renderPanel(); }
      else if(a==="diagram"){ S.diagram=t.dataset.diagram; renderPanel(); setHash(); }
      else if(a==="save-host"){ saveHost(t.dataset.host); }
      else if(a==="addhost"){ renderAddHost(); }
      else if(a==="addhost-save"){ addHost(); }
      else if(a==="addhost-cancel"){ const b=document.getElementById("ifAddHost"); if(b) b.innerHTML=""; }
      else if(a==="back"){ S.tab="hosts"; S.host=""; renderTabs(); renderPanel(); setHash(); } });
    v.addEventListener("input",e=>{ if(e.target.id==="ifQ"){ S.q=e.target.value.trim(); renderHostsTable(); } });
    const tr=document.querySelector("tr[data-host]"); void tr;
    document.querySelector("#view-infra").addEventListener("click",e=>{ const r=e.target.closest("tr[data-host]"); if(r&&!e.target.closest("a,button")) openHost(r.dataset.host); });
  }
  function setHash(){ if(!window.setConsoleHash) return; const q=[`tab=${S.tab}`]; if(S.tab==="map") q.push("diagram="+S.diagram); if(S.host&&S.tab==="host") q.push("host="+S.host); if(S.seg!=="all") q.push("seg="+S.seg); try{ window.setConsoleHash("infra?"+q.join("&")); }catch(_){} }
  async function run(inv){ const b=document.getElementById(inv?"ifInv":"ifRun"); b.disabled=true; b.textContent="… probing"; try{ const r=await api("/api/infra/run",{method:"POST",body:JSON.stringify({inventory:inv})}); toast(r.running?"a probe run is already in progress":`probed ${r.hosts} host(s) · ${r.reachable} reachable · ${r.ms} ms`); await load(); }catch(e){ toast(e.message); } finally{ b.disabled=false; b.textContent=inv?"⟳ Inventory":"↻ Probe now"; } }

  async function load(){ try{ S.data=await api("/api/infra/overview"); }catch(e){ document.getElementById("ifTiles").innerHTML=`<div class="if-note">${esc(e.message)}</div>`; return; } renderLive(); renderTiles(); renderTabs(); renderPanel(); }
  function renderLive(){ const el=document.getElementById("ifLive"); const lr=S.data.last_run; if(!lr){ el.className="if-live stale"; el.innerHTML="<i></i> no probe run yet — first one 70 s after start"; return; } if(lr.error){ el.className="if-live err"; el.innerHTML=`<i></i> last run failed · ${esc(lr.error)}`; return; }
    const stale=(Date.now()-new Date(lr.at).getTime())>5*60e3; el.className="if-live"+(stale?" stale":""); const src=lr.by_source||{}; el.innerHTML=`<i></i> ${S.data.running?"probing now":"probed "+age(lr.at)+" ago"} · ${lr.reachable}/${lr.hosts} reachable · local ${src.local||0} · ssh ${src.ssh||0} · ports ${src.ports||0} · exporter ${src.node_exporter||0} · instana ${src.instana||0} · every ${S.data.sources.interval_sec} s`; }
  function renderTiles(){ const el=document.getElementById("ifTiles"); const segs=S.data.by_segment||[]; const all=S.data.hosts||[];
    const tile=(l,v,s,cls)=>`<div class="if-tile ${cls||""}"><div class="l">${l}</div><div class="v">${v}</div><div class="s">${s}</div></div>`;
    el.innerHTML=segs.map(s=>tile(`${SEGL[s.segment]||s.segment} · hosts`,`${n0(s.hosts)}<small>${s.crit?s.crit+" CRIT":""}${s.warn?" · "+s.warn+" WARN":""}</small>`,`${s.ok} OK · ${s.unknown||0} unknown · ${s.unreachable} unreachable · ${n0(s.cpus)} cpu · ${gb(s.ram_mb)} RAM known`,s.crit?"crit":s.warn?"warn":"")).join("")
      +tile("Alerts · infra",`<span id="ifAlertN">…</span>`,"open infra alerts (rules infra_* · fixed_infra_*)","")
      +tile("Changes · 24 h",n0((S.data.changes||[]).filter(c=>Date.now()-new Date(c.at).getTime()<864e5).length),"inventory drift · reboots · new listeners · status flips","");
    api("/api/alerts?status=open&segment=all").then(j=>{ const rows=(j.alerts||j.rows||j||[]); const n=(Array.isArray(rows)?rows:[]).filter(a=>/(^|_)infra_/.test(a.rule_key||"")).length; const e=document.getElementById("ifAlertN"); if(e) e.textContent=n0(n); }).catch(()=>{ const e=document.getElementById("ifAlertN"); if(e) e.textContent="—"; }); }
  function renderTabs(){ const hs=S.data?S.data.hosts:[]; const T=[["map","Map"],["hosts",`Hosts<b>${hs.length}</b>`],["host","Host"],["alerts","Alerts"],["changes",`Changes<b>${(S.data&&S.data.changes||[]).length}</b>`],["sources","Sources"]];
    document.getElementById("ifTabs").innerHTML=T.filter(t=>t[0]!=="host"||S.host).map(([k,l])=>`<button class="if-tab ${S.tab===k?"on":""}" data-act="tab" data-tab="${k}">${l}</button>`).join(""); }
  function renderPanel(){ const el=document.getElementById("ifPanel"); if(!S.data){ el.innerHTML=""; return; } if(S.mapTimer){ clearInterval(S.mapTimer); S.mapTimer=null; }
    ({map:renderMap,hosts:renderHosts,host:renderHost,alerts:renderAlerts,changes:renderChanges,sources:renderSources}[S.tab]||renderMap)(el); }

  /* ---------------------------------------------------------------- map */
  function renderMap(el){ const d=S.data.diagrams||[]; const src=S.diagram==="fixed"?"fixed-diagrams/salam-fixed-digital-bss-hld.html":"mvno-rodod-hld.html";
    el.innerHTML=`<div class="if-wrap"><div class="if-tools">${d.map(x=>`<button class="if-chip ${S.diagram===x.key?"on":""}" data-act="diagram" data-diagram="${x.key}">${esc(x.title)}</button>`).join("")}<span class="if-note" id="ifMapNote">loading live data…</span></div>
      <div class="if-map"><iframe id="ifFrame" src="${src}?embed=1" title="architecture diagram"></iframe>
        <div class="if-legend"><span><i style="background:#34f5c5"></i>OK</span><span><i style="background:#f59e0b"></i>WARN</span><span><i style="background:#ef4444"></i>CRIT / unreachable (dashed card)</span><span><i style="background:#64748b"></i>unknown · no source</span><span><i style="background:#8aa0c7"></i>external partner (not probed)</span><span>bars = cpu · mem · disk of the hosts behind the card</span><span>edges: <b>bright + animated</b> traffic observed in 5 min · thin = quiet · dotted grey = not observable (no source on either side)</span></div></div>
      <div id="ifUnmapped"></div></div>`;
    S.ready=false; const push=async()=>{ try{ S.map=await api(`/api/infra/map?diagram=${S.diagram}`); const f=document.getElementById("ifFrame"); if(f&&f.contentWindow) f.contentWindow.postMessage({type:"infra-live",nodes:S.map.nodes,edges:S.map.edges},"*");
        const live=S.map.edges.filter(e=>e.state==="live").length, obs=S.map.edges.filter(e=>e.state!=="unobserved").length; const note=document.getElementById("ifMapNote"); if(note) note.textContent=`${Object.values(S.map.nodes).filter(n=>n.hosts.length).length} cards bound to hosts · ${live} edge(s) with traffic · ${obs}/${S.map.edges.length} observable · painted ${ksa(S.map.at)}`;
        const u=document.getElementById("ifUnmapped"); if(u) u.innerHTML=S.map.unmapped.length?`<div class="if-card"><h4>Seen but unmapped <span>· peers the hosts talk to that no card claims — bind them to a card or add them as hosts (Hosts tab) so the map stays honest</span></h4><div class="if-tablew"><table class="if"><thead><tr><th>Peer IP</th><th>Seen from</th><th>Connections · 15 min</th></tr></thead><tbody>${S.map.unmapped.map(x=>`<tr><td data-l="Peer" class="mono">${esc(x.dst_ip)}</td><td data-l="From">${x.sources} host(s)</td><td data-l="Conns">${n0(x.conns)}</td></tr>`).join("")}</tbody></table></div></div>`:""; }
      catch(e){ const note=document.getElementById("ifMapNote"); if(note) note.textContent=e.message; } };
    window.addEventListener("message",onMsg); function onMsg(ev){ const d=ev.data||{}; if(d.type==="infra-ready"){ S.ready=true; push(); } else if(d.type==="infra-node"&&S.map){ const nd=S.map.nodes[d.id]; if(nd&&nd.hosts.length===1) openHost(nd.hosts[0].id); else if(nd&&nd.hosts.length>1){ S.tab="hosts"; S.q=nd.label; renderTabs(); renderPanel(); } } }
    setTimeout(()=>{ if(!S.ready) push(); },2500); S.mapTimer=setInterval(push,30000); }

  /* ---------------------------------------------------------------- hosts */
  function bar(v,warn,crit){ if(v==null) return '<span class="if-note">—</span>'; return `<span class="if-bar ${v>=crit?"crit":v>=warn?"warn":""}"><i style="width:${Math.min(100,Math.max(0,v))}%"></i></span>${Math.round(v)}%`; }
  function renderHosts(el){ const segs=["all","mobile","fixed","shared"];
    el.innerHTML=`<div class="if-wrap"><div class="if-tools">${segs.map(s=>`<button class="if-chip ${S.seg===s?"on":""}" data-act="seg" data-seg="${s}">${s==="all"?"All":SEGL[s]}</button>`).join("")}<span style="width:8px"></span>${["all","crit","warn","ok","unknown"].map(s=>`<button class="if-chip ${S.status===s?"on":""}" data-act="status" data-status="${s}">${s==="all"?"Any status":s.toUpperCase()}</button>`).join("")}<input class="if-in" id="ifQ" placeholder="host · ip · role · os" value="${esc(S.q)}"><span class="if-note" id="ifCount"></span>${canManage()?`<button class="if-btn" data-act="addhost" style="margin-left:auto">+ Add host</button>`:""}</div><div id="ifAddHost"></div><div id="ifHosts"></div></div>`;
    renderHostsTable(); }
  function renderHostsTable(){ const el=document.getElementById("ifHosts"); if(!el) return; let rows=(S.data.hosts||[]); if(S.seg!=="all") rows=rows.filter(h=>h.segment===S.seg); if(S.status!=="all") rows=rows.filter(h=>h.status===S.status); if(S.q){ const q=S.q.toLowerCase(); rows=rows.filter(h=>`${h.label} ${h.hostname||""} ${h.ip} ${(h.ips||[]).join(" ")} ${h.role} ${h.os||""} ${h.node_id||""}`.toLowerCase().includes(q)); }
    const c=document.getElementById("ifCount"); if(c) c.textContent=rows.length+" host(s)";
    el.innerHTML=`<div class="if-tablew"><table class="if"><thead><tr><th>Host</th><th>Segment · role</th><th>Status</th><th>CPU</th><th>Memory</th><th>Disk</th><th>Net</th><th>Inventory</th><th>Sources</th><th>Seen</th></tr></thead><tbody>${rows.map(h=>{ const m=h.last_metrics||{}; const src=(m.sources||[]).join(" · ")||(h.reachable===false?"none":"—");
      return `<tr data-host="${h.id}" class="${h.enabled?"":"na"}"><td data-l="Host"><b>${esc(h.label||h.ip)}</b><div class="if-note mono">${esc(h.ip)}${h.hostname&&h.hostname!==h.label?" · "+esc(h.hostname):""}${h.enabled?"":" · disabled"}</div></td>
        <td data-l="Segment"><span class="if-st">${esc(SEGL[h.segment]||h.segment)}</span> <span class="if-note">${esc(h.role||"")}</span></td>
        <td data-l="Status"><span class="if-st ${esc(h.status)}">${esc(h.status.toUpperCase())}</span>${h.reachable===false?'<div class="if-note" style="color:#dc2626">unreachable</div>':""}${(m.probes||[]).length?`<div class="if-note">${esc(m.probes.slice(0,3).join(" · "))}</div>`:""}</td>
        <td data-l="CPU">${bar(m.cpu_pct,75,90)}${m.load15!=null?`<div class="if-note">load15 ${m.load15}${m.nproc?" / "+m.nproc+" cpu":""}</div>`:""}</td><td data-l="Memory">${bar(m.mem_pct,85,95)}</td><td data-l="Disk">${bar(m.disk_pct,80,90)}</td>
        <td data-l="Net">${m.rx_bps!=null?`↓${bps(m.rx_bps)}<div class="if-note">↑${bps(m.tx_bps)} · ${n0(m.conns)} conn</div>`:'<span class="if-note">—</span>'}</td>
        <td data-l="Inventory">${h.cpus||h.ram_mb?`${h.cpus||"?"} cpu · ${gb(h.ram_mb)}<div class="if-note">${esc(h.os||"")}${h.virt?" · "+esc(h.virt):""}</div>`:'<span class="if-note">not read yet</span>'}</td>
        <td data-l="Sources"><span class="if-note">${esc(src)}${h.ssh?" · ssh✓":""}${h.instana_id?" · instana":""}</span></td><td data-l="Seen" class="if-note">${h.last_seen?age(h.last_seen)+" ago":"never"}</td></tr>`; }).join("")}</tbody></table></div>${rows.length?"":'<div class="if-note" style="padding:12px">No host in this filter.</div>'}`; }

  function renderAddHost(){ const el=document.getElementById("ifAddHost"); if(!el) return; const nodes=S.data.nodes||[];
    el.innerHTML=`<div class="if-card" style="margin-bottom:10px"><h4>Add a host <span>· a server the diagrams do not print (a node behind a VIP, a passerelle, the UPG servers …) — probed from the next tick</span></h4><div class="if-form">
      <div><label>IP</label><input id="ahIp" placeholder="172.31.43.17"></div><div><label>Label</label><input id="ahL" placeholder="DIGAPI-GWP01"></div><div><label>Segment</label><select id="ahS"><option value="mobile">Mobile</option><option value="fixed">Fixed</option><option value="shared">Shared</option></select></div><div><label>Role</label><select id="ahR">${["app","edge","db","integration","network","monitoring","partner","other"].map(r=>`<option>${r}</option>`).join("")}</select></div>
      <div><label>Service ports</label><input id="ahP" placeholder="443, 3000 (learned from the host once ssh works)"></div><div><label>SSH with the console key</label><select id="ahSSH"><option value="1">yes</option><option value="0">no — ports only</option></select></div><div><label>Via passerelle (optional)</label><input id="ahVia" placeholder="172.31.43.17 or user@172.31.43.17"></div>
      <div><label>Bind to a diagram card</label><select id="ahN"><option value="">— none —</option>${nodes.map(n=>`<option value="${esc(n.diagram)}|${esc(n.node_id)}">${esc(n.diagram==="fixed"?"Fixed":"MVNO")} · ${esc(n.label)}</option>`).join("")}</select></div></div>
      <div style="margin-top:10px;display:flex;gap:8px"><button class="if-btn p" data-act="addhost-save">Add host</button><button class="if-btn" data-act="addhost-cancel">Cancel</button></div></div>`; el.querySelector("#ahIp").focus(); }
  async function addHost(){ const g=x=>document.getElementById(x); const ip=g("ahIp").value.trim(); if(!/^\d+\.\d+\.\d+\.\d+$/.test(ip)){ toast("a valid IPv4 address is required"); return; } const nb=g("ahN").value.split("|");
    const body={ip,label:g("ahL").value.trim()||ip,segment:g("ahS").value,role:g("ahR").value,service_ports:g("ahP").value.split(/[,\s]+/).map(Number).filter(Boolean),ssh:g("ahSSH").value==="1",ssh_via:g("ahVia").value.trim(),diagram:nb[0]||null,node_id:nb[1]||null};
    try{ const h=await api("/api/infra/hosts",{method:"POST",body:JSON.stringify(body)}); toast(`host ${h.ip} added — probed at the next tick`); g("ahIp").value=""; g("ahL").value=""; await load(); }catch(e){ toast(e.message); } }

  /* ---------------------------------------------------------------- host page (the healthcheck report) */
  async function openHost(id){ S.host=String(id); S.tab="host"; renderTabs(); setHash(); const el=document.getElementById("ifPanel"); el.innerHTML='<div class="if-note" style="padding:12px">loading host…</div>'; try{ S.det=await api("/api/infra/hosts/"+id); renderHost(el); }catch(e){ el.innerHTML=`<div class="if-note">${esc(e.message)}</div>`; } }
  function spark(id,series,key,max){ const c=document.getElementById(id); if(!c) return; const ctx=c.getContext("2d"); const W=c.width=c.clientWidth*2, H=c.height=112; ctx.clearRect(0,0,W,H); const v=series.map(s=>s[key]).map(x=>x==null?null:Number(x)); const mx=max||Math.max(1,...v.filter(x=>x!=null)); ctx.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue("--green").trim()||"#0f9d58"; ctx.lineWidth=2; ctx.beginPath(); let started=false; v.forEach((x,i)=>{ if(x==null){ started=false; return; } const px=i/(Math.max(1,v.length-1))*W, py=H-4-(x/mx)*(H-8); if(!started){ ctx.moveTo(px,py); started=true; } else ctx.lineTo(px,py); }); ctx.stroke(); }
  function renderHost(el){ const d=S.det; if(!d||String((d.host||{}).id)!==S.host){ if(S.host) openHost(S.host); return; } const h=d.host, inv=h.inventory||{}, m=h.last_metrics||{};
    const kv=(k,v)=>`<div>${k}</div><div>${v==null||v===""?"—":v}</div>`;
    el.innerHTML=`<div class="if-wrap"><div class="if-tools"><button class="if-chip" data-act="back">← Hosts</button><b style="font-size:16px">${esc(h.label||h.ip)}</b> <span class="if-st ${esc(h.status)}">${esc(h.status.toUpperCase())}</span> <span class="if-note mono">${esc(h.ip)}${h.hostname?" · "+esc(h.hostname):""} · ${esc(SEGL[h.segment]||h.segment)} · ${esc(h.role||"")}${h.node_id?" · card "+esc(h.node_id):""}</span><span style="margin-left:auto" class="if-note">${h.reachable===false?'<span style="color:#dc2626;font-weight:700">unreachable</span> · ':""}sources ${esc((m.sources||[]).join(", ")||"none")} · probed ${h.status_at?age(h.status_at)+" ago":"never"}</span></div>
      <div class="if-grid3">
        <div class="if-card"><h4>Health report <span>· the healthcheck mail, live</span></h4>${d.probes.length?`<table class="if" style="min-width:0"><thead><tr><th>Probe</th><th>Level</th><th>Value</th><th>Threshold</th></tr></thead><tbody>${d.probes.map(p=>`<tr><td data-l="Probe"><b>${esc(p.probe)}</b>${p.note?`<div class="if-note">${esc(p.note)}</div>`:""}</td><td data-l="Level"><span class="if-st ${esc(p.level.toLowerCase())}">${esc(p.level)}</span></td><td data-l="Value" class="mono">${esc(p.value||"—")}</td><td data-l="Threshold" class="if-note">${esc(p.threshold||"—")}</td></tr>`).join("")}</tbody></table>`:'<div class="if-note">no probe yet</div>'}</div>
        <div class="if-card"><h4>Physical inventory <span>· ${h.inventory_at?"read "+ksa(h.inventory_at):"not read yet — needs ssh, node exporter or Instana"}</span></h4><div class="if-kv">${kv("CPU",inv.cpus?`${inv.cpus} × ${esc(inv.cpu_model||"?")}${inv.sockets?` · ${inv.sockets} socket(s) · ${inv.cores_per_socket||"?"} cores · ${inv.threads_per_core||"?"} thr/core`:""}`:null)}${kv("RAM",inv.ram_mb?gb(inv.ram_mb)+(inv.swap_mb?` · swap ${gb(inv.swap_mb)}`:""):null)}${kv("Disks",(inv.disks||[]).length?inv.disks.map(x=>`${esc(x.dev)} ${esc(x.size)}${x.model?" "+esc(x.model):""}`).join("<br>"):null)}${kv("Filesystems",(inv.filesystems||[]).length?inv.filesystems.map(x=>`${esc(x.mount)} ${x.size_gb} GB`).join("<br>"):null)}${kv("Network",(inv.nics||[]).length?inv.nics.map(x=>`${esc(x.name)} ${esc(x.cidr)}`).join("<br>"):(h.ips||[]).join(", "))}${kv("OS",inv.os?`${esc(inv.os)}${inv.kernel?" · "+esc(inv.kernel):""}`:null)}${kv("Virtualisation",inv.virt||inv.hypervisor)}${kv("Booted",inv.boot_at?`${esc(inv.boot_at)} (${age(inv.boot_at)} up)`:null)}${kv("Agents",(inv.agents||[]).join(", ")||(h.instana_id?"instana":null))}${kv("NTP",inv.ntp)}${kv("Listening",(inv.listening||[]).length?inv.listening.map(x=>`${x.port}${x.proc?" "+esc(x.proc):""}`).join(" · "):null)}${kv("pm2",(inv.pm2||[]).length?inv.pm2.map(x=>`${esc(x.name)} ${esc(x.status)}${x.mem_mb?" "+x.mem_mb+" MB":""}`).join("<br>"):null)}${kv("Units",(inv.units||[]).length?inv.units.length+" running":null)}</div></div>
        <div class="if-card"><h4>Last 24 h</h4><div class="if-note">CPU %</div><canvas class="if-spark" id="ifSpCpu"></canvas><div class="if-note">Memory %</div><canvas class="if-spark" id="ifSpMem"></canvas><div class="if-note">Load15</div><canvas class="if-spark" id="ifSpLoad"></canvas><div class="if-note">Network in (B/s)</div><canvas class="if-spark" id="ifSpRx"></canvas><div class="if-note">${d.series.length} sample(s) · ${d.history.reduce((a,x)=>a+x.crit,0)} CRIT · ${d.history.reduce((a,x)=>a+x.warn,0)} WARN probe rows in 7 d</div></div></div>
      <div class="if-grid2">
        <div class="if-card"><h4>Connections out <span>· last 15 min, from ss on the host</span></h4>${d.flows.length?`<table class="if" style="min-width:0"><thead><tr><th>To</th><th>Port</th><th>Conns</th></tr></thead><tbody>${d.flows.map(f=>`<tr ${f.dst_id?`data-host="${f.dst_id}"`:""}><td data-l="To">${f.dst_label?`<b>${esc(f.dst_label)}</b><div class="if-note mono">${esc(f.dst_ip)}</div>`:`<span class="mono">${esc(f.dst_ip)}</span> <span class="if-note">unmapped</span>`}</td><td data-l="Port" class="mono">${f.dst_port}</td><td data-l="Conns">${n0(f.conns)}</td></tr>`).join("")}</tbody></table>`:'<div class="if-note">nothing observed — needs ssh (or local) on this host</div>'}</div>
        <div class="if-card"><h4>Connections in <span>· seen from other probed hosts</span></h4>${d.inbound.length?`<table class="if" style="min-width:0"><thead><tr><th>From</th><th>Port</th><th>Conns</th></tr></thead><tbody>${d.inbound.map(f=>`<tr ${f.src_id?`data-host="${f.src_id}"`:""}><td data-l="From">${f.src_label?`<b>${esc(f.src_label)}</b>`:""}<div class="if-note mono">${esc(f.src_ip)}</div></td><td data-l="Port" class="mono">${f.dst_port}</td><td data-l="Conns">${n0(f.conns)}</td></tr>`).join("")}</tbody></table>`:'<div class="if-note">nothing observed</div>'}</div></div>
      <div class="if-grid2">
        <div class="if-card"><h4>Changes <span>· inventory drift · reboots · listeners · status</span></h4>${d.changes.length?`<table class="if" style="min-width:0"><thead><tr><th>When</th><th>Kind</th><th>Before → after</th></tr></thead><tbody>${d.changes.slice(0,30).map(c=>`<tr><td data-l="When" class="if-note">${ksa(c.at)}</td><td data-l="Kind"><b>${esc(c.kind)}</b> ${esc(c.field||"")}</td><td data-l="Change" class="mono" style="font-size:11px">${esc(JSON.stringify(c.before))} → ${esc(JSON.stringify(c.after))}${c.note?`<div class="if-note">${esc(c.note)}</div>`:""}</td></tr>`).join("")}</tbody></table>`:'<div class="if-note">no change recorded yet</div>'}</div>
        <div class="if-card"><h4>Host settings <span>· who owns it, which ports mean "up", may we ssh</span></h4><div class="if-form"><div><label>Label</label><input id="ifL" value="${esc(h.label||"")}" ${canManage()?"":"disabled"}></div><div><label>Segment</label><select id="ifS" ${canManage()?"":"disabled"}>${["mobile","fixed","shared"].map(s=>`<option value="${s}" ${h.segment===s?"selected":""}>${SEGL[s]}</option>`).join("")}</select></div><div><label>Role</label><select id="ifR" ${canManage()?"":"disabled"}>${["edge","app","db","integration","network","monitoring","partner","other"].map(s=>`<option ${h.role===s?"selected":""}>${s}</option>`).join("")}</select></div><div><label>Service ports</label><input id="ifP" value="${esc((h.service_ports||[]).join(", "))}" placeholder="443, 3306" ${canManage()?"":"disabled"}></div><div><label>IPs</label><input id="ifI" value="${esc((h.ips||[h.ip]).join(", "))}" ${canManage()?"":"disabled"}></div><div><label>Owner team</label><input id="ifO" value="${esc(h.owner_team||"")}" ${canManage()?"":"disabled"}></div><div><label>SSH allowed</label><select id="ifSSH" ${canManage()?"":"disabled"}><option value="1" ${h.ssh?"selected":""}>yes — the console key is on this host</option><option value="0" ${h.ssh?"":"selected"}>no</option></select></div><div><label>Via passerelle</label><input id="ifVia" value="${esc(h.ssh_via||"")}" placeholder="172.31.43.17 or user@ip (ProxyJump)" ${canManage()?"":"disabled"}></div><div><label>SSH user (if not the default)</label><input id="ifU" value="${esc(h.ssh_user||"")}" placeholder="console_ro" ${canManage()?"":"disabled"}></div><div><label>Enabled</label><select id="ifE" ${canManage()?"":"disabled"}><option value="1" ${h.enabled?"selected":""}>probed</option><option value="0" ${h.enabled?"":"selected"}>ignored</option></select></div><div style="grid-column:1/-1"><label>Notes</label><input id="ifN" value="${esc(h.notes||"")}" ${canManage()?"":"disabled"}></div></div>${canManage()?`<div style="margin-top:10px"><button class="if-btn p" data-act="save-host" data-host="${h.id}">Save host</button></div>`:'<div class="if-note" style="margin-top:8px">manageSync to edit</div>'}</div></div></div>`;
    spark("ifSpCpu",d.series,"cpu_pct",100); spark("ifSpMem",d.series,"mem_pct",100); spark("ifSpLoad",d.series,"load15"); spark("ifSpRx",d.series,"rx_bps"); }
  async function saveHost(id){ const g=x=>document.getElementById(x); const body={label:g("ifL").value.trim(),segment:g("ifS").value,role:g("ifR").value,service_ports:g("ifP").value.split(/[,\s]+/).map(Number).filter(Boolean),ips:g("ifI").value.split(/[,\s]+/).filter(Boolean),owner_team:g("ifO").value.trim(),ssh:g("ifSSH").value==="1",ssh_via:g("ifVia").value.trim(),ssh_user:g("ifU").value.trim(),enabled:g("ifE").value==="1",notes:g("ifN").value.trim()};
    try{ await api("/api/infra/hosts/"+id,{method:"PUT",body:JSON.stringify(body)}); toast("Host saved — applied at the next probe"); await load(); openHost(id); }catch(e){ toast(e.message); } }

  /* ---------------------------------------------------------------- alerts · changes · sources */
  async function renderAlerts(el){ el.innerHTML='<div class="if-note" style="padding:12px">loading…</div>'; let rows=[]; try{ const j=await api("/api/alerts?status=open&segment=all"); rows=(j.alerts||j.rows||(Array.isArray(j)?j:[])).filter(a=>/(^|_)infra_/.test(a.rule_key||"")); }catch(e){ el.innerHTML=`<div class="if-note">${esc(e.message)}</div>`; return; }
    el.innerHTML=`<div class="if-wrap"><div class="if-note">Infrastructure rules live in the same alert engine as everything else — Mobile rules <span class="mono">infra_*</span>, Fixed rules <span class="mono">fixed_infra_*</span> — so they land on the right side of the segment filter, reach their responder team (Fixed: infra-l2 · Mobile: mobile-digital-l2 until a Mobile infra responder is named) and are triaged by Agent 2. Tune thresholds in Alerts › Alert rules; the "Affected cases" of every infra alert lists the hosts behind the number. Open <a href="#alerts" style="color:var(--green)">Alerts</a> for the full ladder.</div>
      ${rows.length?`<div class="if-tablew"><table class="if"><thead><tr><th>Fired</th><th>Rule</th><th>Segment</th><th>Severity</th><th>Observed</th><th>Team</th><th></th></tr></thead><tbody>${rows.map(a=>`<tr><td data-l="Fired" class="if-note">${ksa(a.fired_at)}</td><td data-l="Rule"><b>${esc(a.name)}</b><div class="if-note mono">${esc(a.rule_key)}</div></td><td data-l="Segment">${esc(a.segment||"mvno")}</td><td data-l="Severity"><span class="if-st ${a.severity==="P1"?"crit":a.severity==="P2"?"warn":""}">${esc(a.severity)}</span></td><td data-l="Observed">${esc(a.observed_value)} (n=${esc(a.sample)})</td><td data-l="Team">${esc(a.team||"—")}</td><td><a href="#${a.segment==="fixed"?"fixed-alerts":"alerts"}?id=${a.id}" class="if-chip" style="text-decoration:none">open</a></td></tr>`).join("")}</tbody></table></div>`:'<div class="if-card"><b>No open infrastructure alert.</b><div class="if-note">Rules: host unreachable (P1) · service port down (P2) · disk ≥ 90 % (P2) · memory ≥ 95 % (P2) · load per core ≥ 2.5 (P3), each for Mobile and for Fixed.</div></div>'}</div>`; }
  async function renderChanges(el){ el.innerHTML='<div class="if-note" style="padding:12px">loading…</div>'; let rows=[]; try{ rows=(await api("/api/infra/changes?days=30")).rows; }catch(e){ el.innerHTML=`<div class="if-note">${esc(e.message)}</div>`; return; }
    el.innerHTML=`<div class="if-wrap"><div class="if-note">Everything that changed on a host in the last 30 days: RAM / CPU / disks / NICs / OS (inventory drift), reboots, ports that started or stopped listening, status flips, and edits made here. Drift is a P4 informational signal today; the register is the evidence when "nothing changed" is claimed.</div>
      ${rows.length?`<div class="if-tablew"><table class="if"><thead><tr><th>When</th><th>Host</th><th>Kind</th><th>Before → after</th></tr></thead><tbody>${rows.map(c=>`<tr data-host="${c.host_id}"><td data-l="When" class="if-note">${ksa(c.at)}</td><td data-l="Host"><b>${esc(c.label||c.ip)}</b><div class="if-note mono">${esc(c.ip)} · ${esc(SEGL[c.segment]||c.segment)}</div></td><td data-l="Kind"><b>${esc(c.kind)}</b> ${esc(c.field||"")}</td><td data-l="Change" class="mono" style="font-size:11px">${esc(JSON.stringify(c.before))} → ${esc(JSON.stringify(c.after))}${c.note?`<div class="if-note">${esc(c.note)}</div>`:""}</td></tr>`).join("")}</tbody></table></div>`:'<div class="if-note">No change recorded yet — the first inventory read sets the baseline.</div>'}</div>`; }
  function renderSources(el){ const s=S.data.sources||{}; const hs=S.data.hosts||[]; const cov=k=>hs.filter(h=>((h.last_metrics||{}).sources||[]).includes(k)).length; const th=s.thresholds||{};
    el.innerHTML=`<div class="if-wrap"><div class="if-grid2">
      <div class="if-card"><h4>Coverage <span>· which host is seen by what — the honest table before any dashboard</span></h4><table class="if" style="min-width:0"><thead><tr><th>Source</th><th>Configured</th><th>Hosts covered</th><th>What it gives</th></tr></thead><tbody>
        <tr><td data-l="Source"><b>Local</b></td><td data-l="Configured"><span class="if-st ok">always</span></td><td data-l="Hosts">${cov("local")}</td><td data-l="Gives" class="if-note">the console box: /proc, df, ss</td></tr>
        <tr><td data-l="Source"><b>SSH</b> <span class="if-note">read-only, the log-collector key</span></td><td data-l="Configured">${s.ssh?`<span class="if-st ok">on</span> <span class="if-note">${esc(s.ssh_user||"")}</span>`:'<span class="if-st warn">off</span> <span class="if-note">INFRA_SSH_USER / INFRA_SSH_KEY (or API_LOG_USER / API_LOG_KEY) in .env</span>'}</td><td data-l="Hosts">${cov("ssh")} / ${hs.filter(h=>h.ssh).length} flagged</td><td data-l="Gives" class="if-note">inventory (lscpu, meminfo, lsblk, df, ip, ss -ltnp, pm2), metrics every tick, connections per peer → the map edges</td></tr>
        <tr><td data-l="Source"><b>Service ports</b></td><td data-l="Configured"><span class="if-st ok">always</span></td><td data-l="Hosts">${cov("ports")}</td><td data-l="Gives" class="if-note">TCP connect to the ports printed on the card (443/80, 3306/5432, :3000…) — reachability with no access at all</td></tr>
        <tr><td data-l="Source"><b>Node exporter</b> <span class="if-note">:9100</span></td><td data-l="Configured"><span class="if-st ok">auto-detected</span></td><td data-l="Hosts">${cov("node_exporter")} / ${hs.filter(h=>h.node_exporter).length} known</td><td data-l="Gives" class="if-note">load, memory, filesystems without a shell</td></tr>
        <tr><td data-l="Source"><b>Instana</b> <span class="if-note">REST, read-only token</span></td><td data-l="Configured">${s.instana?`<span class="if-st ok">on</span> <span class="if-note">${esc(s.instana_url||"")}</span>`:'<span class="if-st warn">off</span> <span class="if-note">INSTANA_URL + INSTANA_TOKEN in .env, firewall 152 → Instana backend</span>'}</td><td data-l="Hosts">${hs.filter(h=>h.instana_id).length}</td><td data-l="Gives" class="if-note">host inventory for every agent-monitored host, hosts the diagrams do not know</td></tr></tbody></table></div>
      <div class="if-card"><h4>How it works</h4><div class="if-note" style="font-size:12.5px;line-height:1.6"><p style="margin:0 0 8px"><b>Seed.</b> The hosts and the map bindings come from the two HLD files themselves — the card ids, labels and the IPs printed on them (${hs.filter(h=>h.source==="hld").length} hosts) — so the diagram stays the single source of truth. Retired cards (Optiva) are seeded disabled. A person then fixes segment, role, ports and the ssh flag on the host page.</p><p style="margin:0 0 8px"><b>Tick.</b> Every ${s.interval_sec} s, six hosts at a time, 10 s per host: metrics (local / ssh / node exporter), service ports, then the probes → status (worst probe) → the row you see. Inventory every ${s.inventory_hours} h or on demand. Nothing is written on any host; no sudo.</p><p style="margin:0 0 8px"><b>Thresholds.</b> disk WARN ${th.diskWarn} % · CRIT ${th.diskCrit} % — memory WARN ${th.memWarn} % · CRIT ${th.memCrit} % — load15 per core WARN ${th.loadWarn} · CRIT ${th.loadCrit} — swap WARN ${th.swapWarn} % (env INFRA_*_WARN / _CRIT).</p><p style="margin:0 0 8px"><b>Mails.</b> ${s.mails?`${s.mails} address(es) get the per-segment digest on a change of the segment's level (INFRA_HEALTH_EMAILS)`:"set INFRA_HEALTH_EMAILS in .env to get the per-segment digest on a change of level"} — the same CRIT / WARN / OK shape as the console healthcheck.</p><p style="margin:0"><b>What is still missing.</b> The ssh key on the hosts of the diagrams that the log collectors do not reach yet (Mobile: TCS · Fixed: the Fixed squad), an Instana read-only token, NTP on every box. The Coverage table above is the list to bring to them.</p></div></div></div>
      <div class="if-card"><h4>Last runs</h4><div class="if-tablew"><table class="if" style="min-width:0"><thead><tr><th>At</th><th>Kind</th><th>ms</th><th>Hosts</th><th>Reachable</th><th>By source</th><th>Errors</th></tr></thead><tbody>${(S.data.runs||[]).map(r=>`<tr><td data-l="At" class="if-note">${ksa(r.at)}</td><td data-l="Kind">${esc(r.kind)}</td><td data-l="ms">${n0(r.ms)}</td><td data-l="Hosts">${r.hosts}</td><td data-l="Reachable">${r.reachable}</td><td data-l="Source" class="if-note">${esc(Object.entries(r.by_source||{}).filter(([,v])=>v).map(([k,v])=>k+" "+v).join(" · "))}</td><td data-l="Errors" class="if-note">${Object.keys(r.errors||{}).length?esc(Object.entries(r.errors).slice(0,4).map(([k,v])=>k+": "+v).join(" · ")):"none"}</td></tr>`).join("")}</tbody></table></div></div></div>`; }

  /* ---------------------------------------------------------------- open */
  window.openInfra=function(qs){
    ensureView(); const src=qs||location.hash; const P=k=>{ const m=new RegExp("(?:^|[?&])"+k+"=([^&]+)").exec(src); return m?decodeURIComponent(m[1]):""; };
    if(/\?/.test(src)){ S.q=""; S.seg="all"; }
    if(/^(map|hosts|host|alerts|changes|sources)$/.test(P("tab"))) S.tab=P("tab"); if(/^(mvno|fixed)$/.test(P("diagram"))) S.diagram=P("diagram"); if(/^(all|mobile|fixed|shared)$/.test(P("seg"))) S.seg=P("seg"); if(/^\d+$/.test(P("host"))){ S.host=P("host"); S.tab="host"; } if(P("q")) S.q=P("q");
    setHash(); load().then(()=>{ if(S.tab==="host"&&S.host) openHost(S.host); });
    if(S.timer) clearInterval(S.timer);
    S.timer=setInterval(()=>{ const v=document.getElementById("view-infra"); if(!v||!v.classList.contains("active")){ clearInterval(S.timer); S.timer=null; if(S.mapTimer){ clearInterval(S.mapTimer); S.mapTimer=null; } return; } if(document.visibilityState==="visible"&&S.tab!=="map"&&S.tab!=="host") load(); },60000);
  };
})();
