/* App error-code catalog - GENERATED from selfcare-backend 2.36.0 source
 * (error_codes.rb constants + locales/en.yml messages), categorized by constant-name rules.
 * Used by the Monitoring app-errors panel, alert metrics and Yusr error-code answers. */
const CATEGORIES = {
  rate_limit: { label: 'Rate limiting', color: '#e11d48', cls: 'business', desc: 'IpRetrial / OTP retry / client-log throttles - flawed gap-logic can block legit users (shared CGNAT IPs).' },
  nafath: { label: 'Nafath / identity', color: '#7c3aed', cls: 'business', desc: 'Nafath digital-identity flow states (pending / rejected tokens).' },
  auth: { label: 'Auth & session', color: '#6366f1', cls: 'business', desc: 'Login, tokens, credentials, sessions - spikes can also indicate credential-stuffing.' },
  otp: { label: 'OTP', color: '#0891b2', cls: 'business', desc: 'OTP validation errors (invalid / expired codes).' },
  payment: { label: 'Payments & billing', color: '#ea580c', cls: 'business', desc: 'Payment, recharge, voucher, invoice and bill errors - incl. the postpaid amount-cap case.' },
  eligibility: { label: 'Eligibility', color: '#0d9488', cls: 'business', desc: 'Customer/plan eligibility (HRSD, freelancer, nationality, Optiva eligibility family -20000s).' },
  transfer: { label: 'Transfers & ownership', color: '#db2777', cls: 'business', desc: 'Credit transfer and ownership-transfer guards.' },
  backend: { label: 'Backend / providers', color: '#ef4444', cls: 'technical', desc: 'BSS/provider failures: Optiva, TCC, backend unreachable, generic -501.' },
  order_flow: { label: 'Orders & SIM flow', color: '#2563eb', cls: 'business', desc: 'Onboarding orders, checkout, reservations, ICCID/eSIM/POSA, MNP, Saleor, numbers.' },
  plan_service: { label: 'Plans & services', color: '#64748b', cls: 'business', desc: 'Plan state/registration and per-service enablement (IDD, roaming, data, PayGo).' },
  validation: { label: 'Validation & input', color: '#d97706', cls: 'business', desc: 'Input validation: mobile numbers, customer info, formats, mismatches, not-found.' },
  crash: { label: 'App crashes', color: '#b91c1c', cls: 'technical', desc: 'Unhandled Ruby exceptions (nil errors etc.) surfacing as generic -501 - always an app bug.' },
  other: { label: 'Other', color: '#94a3b8', cls: 'business', desc: 'Uncatalogued codes.' }
};

const CATALOG = {
  '-20003': { c: 'OPTIVA_INTERNAL_ERROR', cat: 'backend', en: 'Backend General Error' },
  '-20002': { c: 'PLAN_NOT_ELIGIBLE', cat: 'eligibility', en: 'Plan not eligible' },
  '-20001': { c: 'BUNDLE_NOT_ELIGIBLE', cat: 'eligibility', en: 'Bundle not eligible' },
  '-20000': { c: 'SUBSCRIBER_OR_DONOR_NOT_ELIGIBLE', cat: 'eligibility', en: 'Subscriber or donor not eligible' },
  '-10002': { c: 'PAYMENT_PENDING', cat: 'payment', en: 'Sorry your payment is still in processing, please try again after 30' },
  '-10001': { c: 'PAYMENT_INVALID', cat: 'payment', en: 'Sorry your payment couldn\'t be processed. Please try again using a' },
  '-10000': { c: 'INVALID_DEVICE_ID', cat: 'validation', en: '' },
  '-800': { c: 'CLIENT_LOG_RATE_LIMITED', cat: 'rate_limit', en: '' },
  '-705': { c: 'PLAN_NOT_REGISTERED', cat: 'plan_service', en: 'Sorry, your plan is not available on the digital channels. Please check' },
  '-704': { c: 'IP_RETRIES_EXCEEDED', cat: 'rate_limit', en: 'Sorry, you have exceeded the maximum allowed requests based on your IP.' },
  '-703': { c: 'OTP_RETRIES_EXCEEDED', cat: 'rate_limit', en: 'Sorry, you have exceeded the maximum allowed OTP retries.' },
  '-702': { c: 'TCC_GENERAL_ERROR', cat: 'backend', en: '|-' },
  '-701': { c: 'REJECTED_NAFATH_TOKEN', cat: 'nafath', en: '' },
  '-700': { c: 'PENDING_NAFATH_TOKEN', cat: 'nafath', en: '' },
  '-622': { c: 'RESOURCE_NOT_FOUND', cat: 'validation', en: '' },
  '-621': { c: 'INVALID_REQUEST', cat: 'validation', en: '' },
  '-620': { c: 'NEW_PLAN_NOT_REGISTERED', cat: 'plan_service', en: 'Sorry, your plan is not available on the digital channels. Please check' },
  '-619': { c: 'NEW_IP_RETRIES_EXCEEDED', cat: 'rate_limit', en: 'Sorry, you have exceeded the maximum allowed requests based on your IP.' },
  '-618': { c: 'NEW_OTP_RETRIES_EXCEEDED', cat: 'rate_limit', en: 'Sorry, you have exceeded the maximum allowed OTP retries.' },
  '-617': { c: 'NEW_TCC_GENERAL_ERROR', cat: 'backend', en: '|-' },
  '-616': { c: 'NEW_REJECTED_NAFATH_TOKEN', cat: 'nafath', en: 'Your Nafath request status is rejected' },
  '-615': { c: 'NEW_PENDING_NAFATH_TOKEN', cat: 'nafath', en: 'You Nafath request status is still pending' },
  '-614': { c: 'REPLACEMENT_FLOW_MISMATCH', cat: 'order_flow', en: 'Sorry, There is a mismatch between your replacement request type and' },
  '-613': { c: 'NUMBER_NOT_REGISTERED', cat: 'order_flow', en: 'Mobile number is not registered in Salam Mobile.' },
  '-612': { c: 'INVALID_PASSWORD', cat: 'auth', en: 'Invalid password. Please check and try again.' },
  '-611': { c: 'NOT_FOUND_REPLACEMENT_REQUEST', cat: 'order_flow', en: 'You don\'t have a replacement request.' },
  '-610': { c: 'DUPLICATED_REPLACEMENT_REQUEST', cat: 'order_flow', en: 'You already have a replacement request in progress.' },
  '-609': { c: 'DATA_MISMATCH', cat: 'validation', en: 'The provided details do not match our records, please check them and' },
  '-608': { c: 'EMAIL_IS_REGISTERED', cat: 'auth', en: 'The provided email already exists, try another one' },
  '-607': { c: 'INVALID_PLAN_ID', cat: 'plan_service', en: 'Invalid plan ID' },
  '-606': { c: 'PLAN_REFERENCE_NOT_CORRECT', cat: 'plan_service', en: 'Invalid plan reference ID' },
  '-604': { c: 'CREDIT_TRANSFER_LIMIT_EXCEEDED', cat: 'transfer', en: 'You have reached your allowed balance transfer limit.' },
  '-603': { c: 'TARGET_MOBILE_IS_SUSPENDED', cat: 'validation', en: 'The mobile number you are trying to transfer credit to is suspended' },
  '-602': { c: 'INVALID_SALAM_NUMBER', cat: 'order_flow', en: 'The recipient mobile number is not a valid salam number.' },
  '-601': { c: 'CREDIT_TRANSFER_INVALID_AMOUNT', cat: 'transfer', en: 'Transfer amount should be more than 10 SAR and less than 50% of your' },
  '-600': { c: 'CREDIT_TRANSFER_INVALID_PLAN', cat: 'transfer', en: 'Your current plan doesn\'t support balance transfer' },
  '-518': { c: 'LOCAL_DATA_CONSUMED', cat: 'plan_service', en: 'You have consumed all your local data' },
  '-517': { c: 'DUPLICATED_ACTIVE_SERVICE', cat: 'plan_service', en: 'You already have an existing bundle active until %{expiration_date}' },
  '-516': { c: 'PLAN_IS_SUSPENDED', cat: 'plan_service', en: 'You need to activate your plan first to activate the bundle' },
  '-515': { c: 'DUE_AMOUNT_NOT_PAID', cat: 'other', en: 'You need to pay your due amount first to activate the bundle.' },
  '-514': { c: 'PLAN_NOT_ELIGIBLE_FOR_IDD', cat: 'eligibility', en: '' },
  '-513': { c: 'ACCOUNT_PENDING', cat: 'plan_service', en: 'The account is not ready! please try again later.' },
  '-512': { c: 'ACCOUNT_SUSPENDED', cat: 'plan_service', en: 'The account is suspended' },
  '-511': { c: 'PLAN_NOT_ELIGIBLE_FOR_THIS_SERVICE', cat: 'eligibility', en: 'The selected plan is not eligible for this service' },
  '-510': { c: 'PLAN_NOT_ELIGIBLE_FOR_CREDIT_TRANSFER', cat: 'eligibility', en: 'Sender or Recipient plan is not eligible for credit transfer' },
  '-509': { c: 'SERVICE_SUSPENDED', cat: 'plan_service', en: 'This service is suspended' },
  '-508': { c: 'PLAN_NOT_ELIGIBLE_FOR_PAYGO_SERVICE', cat: 'eligibility', en: '' },
  '-507': { c: 'PLAN_NOT_ELIGIBLE_FOR_ROAMING', cat: 'eligibility', en: 'Your plan is not eligible for roaming service' },
  '-506': { c: 'PLAN_OPTION_NO_UPDATE', cat: 'plan_service', en: 'You have already activated this service' },
  '-505': { c: 'INVALID_INVOICE_ID', cat: 'payment', en: '' },
  '-504': { c: 'INVALID_SERVICE', cat: 'plan_service', en: 'Invalid booster' },
  '-503': { c: 'PLAN_NOT_ELIGIBLE_FOR_DATA_SERVICE', cat: 'eligibility', en: 'Your plan is not eligible for data booster' },
  '-502': { c: 'MERCHALINK_GENERAL_ERROR', cat: 'payment', en: '' },
  '-501': { c: 'BACKEND_GENERAL_ERROR', cat: 'backend', en: 'Backend General Error' },
  '-500': { c: 'BACKEND_NOT_REACHABLE', cat: 'backend', en: 'Backend Not Reachable' },
  '-301': { c: 'INVALID_SELLER_CREDNTIALS', cat: 'validation', en: 'Invalid email or password. Please check and try again.' },
  '-300': { c: 'INVALID_LOGIN_CREDENTIALS', cat: 'auth', en: 'Invalid number or password. Please check and try again.' },
  '-236': { c: 'MNP_NUMBER_ACCEPTED', cat: 'order_flow', en: 'Port-in number is already accepted' },
  '-235': { c: 'MNP_NUMBER_NOT_MATCHING_ID', cat: 'order_flow', en: 'Port-in number not matching nationality id number' },
  '-234': { c: 'MNP_ORDER_NOT_SUBMITTED', cat: 'order_flow', en: 'This number has already Ported in successfully ' },
  '-232': { c: 'MNP_ORDER_NOT_FOUND', cat: 'order_flow', en: 'Port-in order not found in Salam systems' },
  '-231': { c: 'BUNDLE_EXPIRED', cat: 'plan_service', en: 'Your bundle is expired' },
  '-230': { c: 'INVALID_DATA_BALANCE', cat: 'plan_service', en: 'You can\'t share data less than %{min_value} or exceeds %{max_value}' },
  '-229': { c: 'INSUFFICIENT_DATA_BALANCE', cat: 'plan_service', en: 'Insufficient data balance' },
  '-228': { c: 'INVALID_ADVANCED_POSTPAID_PAYMENT', cat: 'payment', en: 'Invalid Payment Amount' },
  '-227': { c: 'BILL_PDF_NOT_FOUND', cat: 'payment', en: 'PDF file for your bill was not found. Please try again later!' },
  '-226': { c: 'BILL_NOT_FOUND', cat: 'payment', en: 'No bill was found for your number. Please try again later!' },
  '-225': { c: 'PLAN_NOT_ACTIVE', cat: 'plan_service', en: 'Sorry, you cannot renew your plan at this moment! Please recharge your' },
  '-224': { c: 'OTP_VALIDATION_EXPIRED', cat: 'otp', en: 'Your transaction already expired, please start over again.' },
  '-223': { c: 'INVALID_RECHARGE_AMOUNT', cat: 'payment', en: 'Recharge amount should be more than %{min_value} SAR and less than %{max_value}' },
  '-222': { c: 'INVALID_TASHEEL_CARD', cat: 'payment', en: 'The credit card number you entered is not accepted on Baseeta. Please' },
  '-221': { c: 'OWNERSHIP_TRANSFER_INVALID_VANITY_NUMBER', cat: 'transfer', en: 'Sorry, this service is not currently available.' },
  '-220': { c: 'OWNERSHIP_TRANSFER_CANT_BE_DELETED', cat: 'transfer', en: 'Transfer request cannot be withdrawn as the receiver has initiated the' },
  '-219': { c: 'OWNERSHIP_TRANSFER_REQUEST_EXPIRED', cat: 'transfer', en: 'The Ownership request expired. You have to accept the request in %s hours' },
  '-218': { c: 'TRANSFERER_USING_HIS_OWN_ID', cat: 'transfer', en: 'You must enter a different ID. You are using the same ID as the transferer.' },
  '-217': { c: 'TRANSFEREE_ALREADY_HAVE_ACTIVE_REQUEST', cat: 'transfer', en: 'This ID HAS a pending request. The ID number you are using to initiate' },
  '-216': { c: 'YOU_ALREADY_HAVE_ACTIVE_REQUEST', cat: 'validation', en: 'You already have an active line ownership transfer request on this number.' },
  '-215': { c: 'INVALID_CHECKOUT', cat: 'order_flow', en: 'Invalid checkout' },
  '-214': { c: 'PENDING_PAYMENT', cat: 'payment', en: '' },
  '-213': { c: 'INVALID_CHECKOUT_TYPE', cat: 'order_flow', en: '' },
  '-212': { c: 'INVALID_ACCOUNT_LOOKUP_DETAILS', cat: 'plan_service', en: '' },
  '-211': { c: 'INVALID_VALIDATION', cat: 'validation', en: '' },
  '-210': { c: 'ALREADY_REGISTERED', cat: 'validation', en: 'Mobile number already registered' },
  '-209': { c: 'PROFILE_DELETED', cat: 'auth', en: 'Sorry, you can not login with this account, as you have previously deleted' },
  '-205': { c: 'EXPIRED_ACCESS_TOKEN', cat: 'auth', en: '' },
  '-204': { c: 'MISSING_ACCESS_TOKEN', cat: 'auth', en: '' },
  '-203': { c: 'INVALID_ACCESS_TOKEN', cat: 'auth', en: '' },
  '-202': { c: 'MISSING_REFRESH_TOKEN', cat: 'auth', en: '' },
  '-201': { c: 'INVALID_REFRESH_TOKEN', cat: 'auth', en: '' },
  '-152': { c: 'INSUFFICIENT_BALANCE', cat: 'payment', en: 'Insufficient balance' },
  '-151': { c: 'VOUCHER_RECHARGE_FAILED', cat: 'payment', en: 'Voucher Recharge failed' },
  '-146': { c: 'FREELANCER_ELIGIBILITY_REQUIRED', cat: 'eligibility', en: 'Freelancer plans require the freelancer eligibility endpoint. Please call freelancer_is_eligible instead.' },
  '-145': { c: 'SAUDI_NATIONALITY_NOT_CONFIGURED', cat: 'eligibility', en: 'Saudi Arabia nationality is not configured. Please contact support.' },
  '-144': { c: 'FREELANCER_HRSD_ERROR', cat: 'eligibility', en: 'Freelancer eligibility service is temporarily unavailable. Please try again later.' },
  '-143': { c: 'FREELANCER_PLAN_REQUIRED', cat: 'eligibility', en: 'This eligibility check is only available for freelancer plans.' },
  '-142': { c: 'FREELANCER_CERTIFICATE_NOT_ELIGIBLE', cat: 'eligibility', en: 'Freelancer certificate validation failed. Please check your certificate number and try again.' },
  '-141': { c: 'INVALID_SAUDI_CITIZEN_ID', cat: 'eligibility', en: 'Freelancer plans are available for Saudi citizens only. Please enter a valid Saudi national ID.' },
  '-140': { c: 'INVALID_FREELANCER_CERTIFICATE', cat: 'eligibility', en: 'Invalid freelancer certificate number. Expected format FL- followed by 9 digits.' },
  '-138': { c: 'RESUME_RESERVATION_EXPIRED', cat: 'order_flow', en: '' },
  '-137': { c: 'RESUME_ORDER_NOT_ELIGIBLE', cat: 'eligibility', en: '' },
  '-136': { c: 'RESUME_TOKEN_EXPIRED', cat: 'auth', en: '' },
  '-135': { c: 'RESUME_TOKEN_INVALID', cat: 'auth', en: '' },
  '-134': { c: 'INVALID_QR_POSA_ICCID', cat: 'order_flow', en: 'This QR POSA ICCID is invalid or has already been used. Please check with customer support.' },
  '-133': { c: 'INVALID_MODEM_SN', cat: 'order_flow', en: 'The modem serial number does not match this ICCID. Please check and try again.' },
  '-132': { c: 'SALEOR_CHANGED_CHECKOUT', cat: 'order_flow', en: 'Cart has been updated!' },
  '-131': { c: 'SALEOR_INVALID_CHECKOUT', cat: 'order_flow', en: 'Invalid checkout!' },
  '-130': { c: 'SALEOR_INVALID_INVENTORY', cat: 'order_flow', en: 'Some of the items in your cart are no longer available. Return to your' },
  '-129': { c: 'VISITOR_HAJJ_VISA_TYPE_NOT_CONFIGURED', cat: 'other', en: 'No enabled Semati user type named "Hajj Visitor". Add or enable it in CMS.' },
  '-128': { c: 'VISITOR_HAJJ_ICCID_NOT_IN_INVENTORY', cat: 'order_flow', en: 'This ICCID is not in the Hajj visitor SIM inventory, or has already been used.' },
  '-127': { c: 'VISITOR_HAJJ_ICCID_CONFLICT', cat: 'order_flow', en: 'The ICCID does not match the one already stored for this order.' },
  '-126': { c: 'VISITOR_HAJJ_PHONE_MISMATCH', cat: 'validation', en: 'The mobile number must match the reserved line for this order.' },
  '-125': { c: 'INVALID_ESIM_ICCID', cat: 'order_flow', en: 'The provided eSIM ICCID does not exist. Please check with the customer' },
  '-124': { c: 'ORDER_PREPARE_FAILED', cat: 'order_flow', en: 'We are unable to create you order as it seems your number is expired.' },
  '-123': { c: 'EXISTING_MNP_NUMBER', cat: 'order_flow', en: 'You already have a port-in request with the following orderID %{checkout_id}' },
  '-122': { c: 'NO_ORDERS_FOUND_WITHIN_DETAILS', cat: 'order_flow', en: 'No orders found under the provided details' },
  '-121': { c: 'ORDER_DETAILS_MISMATCH', cat: 'order_flow', en: 'The provided details do not have orders pending for activation, please' },
  '-120': { c: 'SERVICE_UNAVAILABLE', cat: 'plan_service', en: 'Sorry, this service is not available right now, please try it later' },
  '-119': { c: 'ORDER_NOT_READY_FOR_PAYMENT', cat: 'payment', en: '' },
  '-118': { c: 'INVALID_POSA_ICCID', cat: 'order_flow', en: 'The provided ICCID does not exist. Please check with the customer support.' },
  '-117': { c: 'RESERVATION_NOT_FOUND', cat: 'order_flow', en: '' },
  '-116': { c: 'INVALID_EMAIL_FORMAT', cat: 'validation', en: 'Invalid email address format, please check it and try again!' },
  '-115': { c: 'NUMBER_EXPIRED', cat: 'order_flow', en: 'Your reservation for this number has been expired. Please select a new' },
  '-114': { c: 'NO_NUMBERS_AVAILABLE', cat: 'order_flow', en: 'We are sorry, no numbers available at the moment. Please try again later.' },
  '-113': { c: 'NUMBER_ALREADY_RESERVERED', cat: 'order_flow', en: 'Number already reserved' },
  '-112': { c: 'INVALID_MOBILE_NUMBER', cat: 'order_flow', en: 'Invalid Mobile Number' },
  '-111': { c: 'INVALID_IAM', cat: 'auth', en: 'Invalid or expired IAM token' },
  '-110': { c: 'INVALID_ICCID', cat: 'order_flow', en: 'ICCID is invalid or has been used' },
  '-109': { c: 'INVALID_TOKEN', cat: 'auth', en: 'Invalid Token' },
  '-108': { c: 'INVALID_AREA_ID', cat: 'validation', en: 'Invalid Area ID' },
  '-107': { c: 'INVALID_MNP_INFO', cat: 'order_flow', en: 'Invalid MNP Info' },
  '-106': { c: 'INVALID_TRANSACTION', cat: 'validation', en: 'Invalid Transaction' },
  '-105': { c: 'NOT_ORDERS_FOUND', cat: 'order_flow', en: 'Order not found' },
  '-104': { c: 'INVALID_DELIVERY_INFO', cat: 'order_flow', en: 'Invalid Delivery Info' },
  '-103': { c: 'INVALID_OTP', cat: 'otp', en: 'Invalid OTP Code' },
  '-102': { c: 'INVALID_CUSTOMER_INFO', cat: 'validation', en: 'Invalid Customer Info' },
  '-101': { c: 'INVALID_ONBOARDING_PLAN', cat: 'order_flow', en: 'Invalid Onboarding Plan' },
  '-100': { c: 'INVALID_ONBOARDING_ORDER_ID', cat: 'order_flow', en: 'Invalid Order ID' }
};

/* classify one api_error_events row -> category key */
function classify(code, exception_class) {
  if (exception_class && Number(code) === -501) return 'crash';
  const e = CATALOG[String(code)];
  return e ? e.cat : 'other';
}
function describe(code) {
  const e = CATALOG[String(code)];
  if (!e) return null;
  const cat = CATEGORIES[e.cat] || CATEGORIES.other;
  return { code: Number(code), constant: e.c, message: e.en || null, category: e.cat,
    category_label: cat.label, class: cat.cls, category_desc: cat.desc };
}
module.exports = { CATEGORIES, CATALOG, classify, describe };
