/* fixedExec.js — Fixed › Executive + Operations pages: ONE endpoint, computed from the read models.
 *
 *   GET /api/fixed/exec?range=7d|30d        (gate: view 'fixed')
 *
 * Replaces the two static pages generated by the "Fixed Operations AI Agent" (index.html /
 * executive.html, hard-coded to 2026-06-21) with the same story read live:
 *   orders & conversion   → order_attempts   (sda_ops public + beta, via fixed360.summary)
 *   pipeline / pileup     → order_attempts.step_reached for everything not COMPLETED
 *   API errors + budget   → error_events (both schemas), threshold from alert_rules fixed_error_spike
 *   active alerts         → alert_events FIRED in the window (sda_ops.public)
 *   top ongoing issues    → error_events by category: open, first seen, 7-day sparkline, trend
 * SADAD / SFTP / revenue have NO feed in this console yet — they are reported as "not wired",
 * never as a green tick, so an executive cannot read a healthy status we did not measure.
 * Every number carries its window; nothing here is written anywhere. */
const db = require('./db');
const f360 = require('./fixed360');

const n = v => Number(v) || 0;
const pct = (a, b) => b > 0 ? Math.round((a / b) * 1000) / 10 : 0;
const dayKey = d => new Date(new Date(d).getTime() + 3 * 3600e3).toISOString().slice(0, 10);   // KSA day

const ERR_DAY = `SELECT (date_trunc('day', occurred_at AT TIME ZONE 'Asia/Riyadh'))::date::text AS day,
                        count(*)::int AS n, count(*) FILTER (WHERE NOT resolved)::int AS open
                   FROM error_events WHERE occurred_at >= $1 AND occurred_at < $2 GROUP BY 1 ORDER BY 1`;
const ERR_CAT = `SELECT category, count(*)::int AS total, count(*) FILTER (WHERE NOT resolved)::int AS open,
                        min(occurred_at) AS first_seen, max(occurred_at) AS last_seen
                   FROM error_events WHERE occurred_at >= $1 AND occurred_at < $2
                  GROUP BY 1 ORDER BY open DESC, total DESC LIMIT 10`;
const ERR_CAT_DAY = `SELECT category, (date_trunc('day', occurred_at AT TIME ZONE 'Asia/Riyadh'))::date::text AS day, count(*)::int AS n
                       FROM error_events WHERE occurred_at >= $1 AND occurred_at < $2 GROUP BY 1,2`;
const STEPS = `SELECT oa.channel, oa.step_reached AS step, oa.outcome::text AS outcome, count(*)::int AS n
                 FROM order_attempts oa WHERE oa.started_at >= $1 AND oa.started_at < $2 AND oa.outcome <> 'COMPLETED'
                GROUP BY 1,2,3 ORDER BY 4 DESC LIMIT 60`;

const pools = () => [...new Set([db.ops, db.opsBeta].filter(Boolean))];   // same pool twice = one query
const both = async (sql, params) => (await Promise.all(pools().map(p => p.query(sql, params).then(r => r.rows, () => [])))).flat();
const mergeDays = rows => { const m = {}; for (const r of rows) { const k = m[r.day] || (m[r.day] = { day: r.day, n: 0, open: 0 }); k.n += n(r.n); k.open += n(r.open); } return Object.values(m).sort((a, b) => a.day < b.day ? -1 : 1); };

async function errorBudget() {   // /day threshold the Fixed alert rule already uses; 50 if the rule is absent
  try {
    const r = await db.ops.query(`SELECT threshold FROM alert_rules WHERE key IN ('fixed_error_spike') AND enabled LIMIT 1`);
    const t = n((r.rows[0] || {}).threshold); return t > 0 ? t : 50;
  } catch (_) { return 50; }
}
async function firedAlerts(fromIso) {
  try {
    return (await db.ops.query(`SELECT rule_key, rule_name, team, severity, metric_value, threshold, metric_text, fired_at
                                  FROM alert_events WHERE status='FIRED' AND fired_at >= $1 ORDER BY fired_at DESC LIMIT 50`, [fromIso])).rows;
  } catch (_) { return []; }
}
const trendOf = (series) => {           // last 2 days vs the 2 before: ▼ improving / ▲ worsening / → stable
  const v = series.slice(-4); if (v.length < 4) return 'stable';
  const a = (v[0] + v[1]) / 2, b = (v[2] + v[3]) / 2; if (a === 0 && b === 0) return 'stable';
  const d = (b - a) / Math.max(a, 1); return d <= -0.2 ? 'improving' : d >= 0.2 ? 'worsening' : 'stable';
};

async function exec(q = {}) {
  if (!db.ops && !db.opsBeta) return { configured: false, reason: 'OPS_DATABASE_URL / OPS_BETA_DATABASE_URL not set' };
  const range = q.range === '30d' ? '30d' : '7d';
  const days = range === '30d' ? 30 : 7;
  const now = new Date(), D = 864e5;
  const to = now.toISOString(), from = new Date(now - days * D).toISOString();
  const from24 = new Date(now - D).toISOString(), from48 = new Date(now - 2 * D).toISOString();

  const [today, prev, series, errDaysRaw, errCats, errCatDays, steps, budget, alerts] = await Promise.all([
    f360.summary({ range: '24h' }),
    f360.summary({ from: from48, to: from24 }),
    f360.summary({ range }),
    both(ERR_DAY, [from, to]),
    both(ERR_CAT, [from, to]),
    both(ERR_CAT_DAY, [from, to]),
    both(STEPS, [from, to]),
    errorBudget(),
    firedAlerts(from),
  ]);

  // ---- orders per day (fill missing days with 0 so the chart has a stable x-axis)
  const byDay = {}; for (const r of series.byDay || []) byDay[dayKey(r.day)] = { n: n(r.n), completed: n(r.completed) };
  const errDays = {}; for (const r of mergeDays(errDaysRaw)) errDays[r.day] = r;
  const daysArr = []; for (let i = days - 1; i >= 0; i--) { const k = dayKey(now - i * D); daysArr.push({ day: k, orders: (byDay[k] || {}).n || 0, completed: (byDay[k] || {}).completed || 0, errors: (errDays[k] || {}).n || 0, openErrors: (errDays[k] || {}).open || 0 }); }

  // ---- 24 h KPIs with deltas vs the previous 24 h
  const k = today.kpis || {}, kp = prev.kpis || {};
  const outcomes = Object.fromEntries((today.outcomes || []).map(o => [o.outcome, n(o.n)]));
  const errors24 = daysArr.slice(-1)[0] ? daysArr.slice(-1)[0].errors : 0;   // today (KSA) — same bucket the chart shows
  const errors24Exact = (await both(`SELECT count(*)::int AS n FROM error_events WHERE occurred_at >= $1`, [from24])).reduce((a, r) => a + n(r.n), 0);
  const delta = (a, b) => b > 0 ? Math.round(((a - b) / b) * 100) : (a > 0 ? 100 : 0);

  // ---- pipeline: where the not-completed attempts are sitting
  const stepMap = {}; for (const s of steps) { const key = s.step || '(no step)'; const x = stepMap[key] || (stepMap[key] = { step: key, n: 0, channels: {}, outcomes: {} }); x.n += n(s.n); x.channels[s.channel] = (x.channels[s.channel] || 0) + n(s.n); x.outcomes[s.outcome] = (x.outcomes[s.outcome] || 0) + n(s.n); }
  const pipeline = Object.values(stepMap).sort((a, b) => b.n - a.n).slice(0, 18);
  const pileup = pipeline.find(p => /CustomerProfile$/i.test(p.step)) || pipeline[0] || null;

  // ---- top ongoing issues: categories with a sparkline and a trend
  const catDays = {}; for (const r of errCatDays) { (catDays[r.category] = catDays[r.category] || {})[r.day] = (catDays[r.category][r.day] || 0) + n(r.n); }
  const catMerged = {}; for (const c of errCats) { const x = catMerged[c.category] || (catMerged[c.category] = { category: c.category, total: 0, open: 0, first_seen: c.first_seen, last_seen: c.last_seen }); x.total += n(c.total); x.open += n(c.open); if (c.first_seen < x.first_seen) x.first_seen = c.first_seen; if (c.last_seen > x.last_seen) x.last_seen = c.last_seen; }
  const issues = Object.values(catMerged).sort((a, b) => b.open - a.open || b.total - a.total).slice(0, 8).map(c => {
    const spark = daysArr.map(d => (catDays[c.category] || {})[d.day] || 0);
    return { ...c, spark, trend: trendOf(spark), daysOngoing: Math.max(1, Math.round((now - new Date(c.first_seen)) / D)) };
  });

  // ---- alerts by severity (P1 = critical here; the Fixed rules use P1..P3)
  const sev = { P1: 0, P2: 0, P3: 0 }; for (const a of alerts) sev[a.severity] = (sev[a.severity] || 0) + 1;
  const alerts24 = alerts.filter(a => new Date(a.fired_at) >= new Date(from24));

  // ---- SLO tiles: measured ones from the data, unmeasured ones honestly marked
  const naf = (today.integrations || {}).nafath || {}, man = (today.integrations || {}).manafith || {};
  const conv7 = pct(n((series.kpis || {}).completed), n((series.kpis || {}).attempts));
  const slos = [
    { key: 'error_budget', name: 'API error budget', actual: `${errors24Exact} / 24 h`, target: `≤ ${budget} / day`, ok: errors24Exact <= budget, measured: true },
    { key: 'conversion', name: 'Order conversion', actual: `${k.conversion || 0}%`, target: `≥ ${Math.max(0, conv7 - 5)}% (7-day avg − 5 pp)`, ok: n(k.conversion) >= Math.max(0, conv7 - 5), measured: n(k.attempts) > 0 },
    { key: 'nafath', name: 'Nafath failure rate', actual: naf.total ? `${naf.failRate}%` : '—', target: '≤ 25%', ok: !naf.total || naf.failRate <= 25, measured: !!naf.total },
    { key: 'manafith', name: 'Manafith denials', actual: man.total ? `${man.deniedRate}%` : '—', target: '≤ 10%', ok: !man.total || man.deniedRate <= 10, measured: !!man.total },
    { key: 'sadad', name: 'SADAD availability', actual: '—', target: 'UP · ≤ 500 ms', ok: null, measured: false, note: 'no SADAD probe is wired into this console yet' },
    { key: 'sftp', name: 'SFTP ODB sync', actual: '—', target: 'SUCCESS daily', ok: null, measured: false, note: 'no SFTP job feed is wired into this console yet' },
  ];

  // ---- overall status + the three-line executive summary (rule-based, deterministic)
  const critical = sev.P1 + (errors24Exact > budget ? 1 : 0) + (pileup && pileup.n >= 1000 ? 1 : 0);
  const warnings = sev.P2 + slos.filter(s => s.measured && s.ok === false && s.key !== 'error_budget').length;
  const status = critical > 0 ? 'CRITICAL' : warnings > 0 ? 'WARNING' : 'HEALTHY';
  const summary = [];
  if (critical) summary.push(`${critical} critical signal(s): ${[sev.P1 ? `${sev.P1} P1 alert(s) fired` : null, errors24Exact > budget ? `API errors ${errors24Exact} above the ${budget}/day budget` : null, pileup && pileup.n >= 1000 ? `${pileup.n} attempts sitting at ${pileup.step}` : null].filter(Boolean).join(', ')}.`);
  else summary.push(`No critical signal in the last 24 h${warnings ? `; ${warnings} warning(s) to watch` : ''}.`);
  summary.push(`${n(k.attempts).toLocaleString('en-US')} order attempts in 24 h (${delta(n(k.attempts), n(kp.attempts)) >= 0 ? '+' : ''}${delta(n(k.attempts), n(kp.attempts))}% vs the previous 24 h), ${n(k.completed).toLocaleString('en-US')} completed — ${k.conversion || 0}% conversion against a ${conv7}% ${days}-day average.`);
  const worst = issues[0]; if (worst) summary.push(`Largest open error category: ${worst.category} (${worst.open} open, ${worst.trend}, ${worst.daysOngoing} d ongoing).`);
  else summary.push('No open Fixed error category in the window.');

  return {
    configured: true, generatedAt: now.toISOString(), range, days, window: { from, to },
    source: today.source, freshness: today.freshness, provisional: 'SADAD / SFTP / revenue are not measured by this console — shown as not wired',
    status, summary,
    kpis: {
      attempts: n(k.attempts), attemptsPrev: n(kp.attempts), attemptsDelta: delta(n(k.attempts), n(kp.attempts)),
      completed: n(k.completed), completedPrev: n(kp.completed), conversion: n(k.conversion), conversionPrev: n(kp.conversion), conversion7d: conv7,
      withOrder: n(k.withOrder), activeDealers: n(k.activeDealers),
      stuck: n(outcomes.STALLED) + n(outcomes.IN_PROGRESS), cancelled: n(outcomes.CANCELLED), expired: n(outcomes.EXPIRED),
      errors24: errors24Exact, errorsPrev: (daysArr.slice(-2)[0] || {}).errors || 0, errorBudget: budget, errorsToday: errors24,
      critical, warnings, alertsFired: alerts.length, alerts24: alerts24.length, bySeverity: sev,
      pileup: pileup ? { step: pileup.step, n: pileup.n } : null,
    },
    days: daysArr, pipeline, issues, alerts: alerts.slice(0, 12), slos,
    byWorkflow: series.byWorkflow || [], byChannel: series.byChannel || [],
  };
}

function mount(app, { requireView } = {}) {
  const gate = requireView ? requireView('fixed') : (req, res, next) => next();
  app.get('/api/fixed/exec', gate, async (req, res) => {
    try { res.json(await exec(req.query)); }
    catch (e) { res.status(e.status || 500).json({ error: e.message }); }
  });
}
module.exports = { mount, exec };
