/* opsReportsDecks.js — the two weekly decks of Operations reports, generated by the console (9 Oct 2026, alpha.157)
 *
 *   Operational Weekly Executive Report        5 slides: cover · executive brief · executive areas · focus next week · thank you
 *   Application Operational weekly status report   cover · operations domains · per domain a divider + the vendor's own
 *                                              slides (on the Salam master) · thank you — one PowerPoint section per domain
 *
 * WHEN. Automatically, as soon as every team the decks use has submitted its report for the week (or, when Settings say
 * so, once ITSM approved them): the 1-minute tick of opsReports.js checks the week being reported and the one before.
 * A report changed afterwards (a new file, a resubmission) rebuilds both decks; ITSM can also build them at any time
 * ("Build now" — the decks then say which reports are missing). Built once per change across consoles (opsr_jobs).
 * WHAT. Settings › Weekly decks (console_settings 'opsreports'.deck):
 *   domains  the sections of the complete deck, in order: name (a line break with "\n"), a note under the title, and the
 *            team whose files go in — which file (words of its name, "a|b") and which slides (opsDeck.js: auto · all ·
 *            "2-7" · "from:…" · "until:…"). A PDF goes in page by page.
 *   areas    the 6 rows of the executive table: name + the teams it summarises.
 * The executive text (brief, headline lines, the 6 rows, focus for next week) is written from the submitted reports —
 * headline, KPIs against target, ITSM counters, risks, support asked, actions — and ITSM can edit it in the console;
 * an edited text is kept when the decks are rebuilt (until "Back to automatic").
 *
 *   GET  /api/opsreports/decks?week=          what the decks wait for, the last build, the executive text
 *   GET  /api/opsreports/decks/:id/download   the .pptx                                   (everyone with the view)
 *   POST /api/opsreports/decks/generate       build both now { week }                    (ITSM editors · admins)
 *   PUT  /api/opsreports/decks/content        edit the executive text { week, content } · { week, reset: true }
 * Stored in opsr_decks (one row per week and kind, the file in bytea). Template: server/templates/opsreports-deck-template.pptx. */
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const deck = require('./opsDeck');

const TEMPLATE = path.join(__dirname, '..', 'templates', 'opsreports-deck-template.pptx');
const lc = s => String(s || '').trim().toLowerCase();
const str = (v, n) => { const s = v == null ? '' : String(v).replace(/\r/g, '').trim(); return s ? s.slice(0, n) : null; };
const keyOf = v => lc(v).replace(/[^a-z0-9_]+/g, '_').slice(0, 40);
const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
const DAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
const DECK_EXT = /\.(pptx|pdf)$/i;

/* ---------------------------------------------------------------- settings */
const DEFAULT_DECK = {
  auto: true, when: 'submitted', maxPdfPages: 30,
  domains: [
    { name: 'MVNO - Legacy', sources: [{ team: 'tcs_legacy' }] },
    { name: 'MVNO - Digital', sources: [{ team: 'tcs_mvno' }] },
    { name: 'SALAM - Digital Channels', sources: [{ team: 'portals' }] },
    { name: 'Transformation Program\nMVNO-IMPACT', sources: [{ team: 'oracle_impact' }] },
    { name: 'Transformation Program\nApollo', sources: [{ team: 'tech_platforms', file: 'Technology Platforms', slides: 'from:Apollo Managed Services' }] },
    { name: 'Fixed – FTTH BSS & OSS\nIncluding DB Usage', sources: [{ team: 'whale_ftth' }] },
    { name: 'ERP Operations', sources: [{ team: 'oracle_css' }] },
    { name: 'Technology Platform', sources: [{ team: 'tech_platforms', file: 'Technology Platforms', slides: 'until:ZSmart Hardware Weekly Report; until:Apollo Managed Services' }] },
    { name: 'RAFM Operations', sources: [{ team: 'subex_rafm' }] }
  ],
  areas: [
    { name: 'MVNO – Legacy & Digital Channels Operations', teams: ['tcs_legacy', 'tcs_mvno', 'portals'] },
    { name: 'Transformation Program – MVNO Impact & Apollo', teams: ['oracle_impact'] },
    { name: 'Fixed B2C – FTTX OSS & BSS Managed Services', teams: ['whale_ftth'] },
    { name: 'ERP, HCM, SCM & SaaS Projects', teams: ['oracle_css'] },
    { name: 'Technology Platform & DB Operations', teams: ['tech_platforms'] },
    { name: 'Revenue Assurance & Fraud Management Operations', teams: ['subex_rafm'] }
  ]
};
function normDeck(raw) {
  const o = raw && typeof raw === 'object' ? raw : DEFAULT_DECK;
  const pdf = Number(o.maxPdfPages);
  return {
    auto: o.auto !== false, when: o.when === 'approved' ? 'approved' : 'submitted',
    maxPdfPages: Number.isFinite(pdf) ? Math.min(60, Math.max(1, Math.round(pdf))) : 30,
    domains: (Array.isArray(o.domains) ? o.domains : DEFAULT_DECK.domains).slice(0, 30).map(d => {
      d = d && typeof d === 'object' ? d : {};
      return { name: str(String(d.name || '').split('\n').map(s => s.trim()).filter(Boolean).slice(0, 3).join('\n'), 120), note: str(d.note, 300),
        sources: (Array.isArray(d.sources) ? d.sources : []).slice(0, 5).map(s => s && typeof s === 'object' ? { team: keyOf(s.team), file: str(s.file, 120), slides: str(s.slides, 200) || 'auto' } : null).filter(s => s && s.team) };
    }).filter(d => d.name),
    areas: (Array.isArray(o.areas) ? o.areas : DEFAULT_DECK.areas).slice(0, 6).map(a => {
      a = a && typeof a === 'object' ? a : {};
      return { name: str(a.name, 120), teams: [...new Set((Array.isArray(a.teams) ? a.teams : String(a.teams || '').split(/[\s,;]+/)).map(keyOf).filter(Boolean))].slice(0, 10) };
    }).filter(a => a.name)
  };
}

/* ---------------------------------------------------------------- context from opsReports.js */
let X = null;                                                  // { C, ensure, loadCfg, cfg, teams, who, claim, defaultWeek, addDays, isDay, fmtDay, listActions, nameOf, people }
const C = () => X.C();
let _table = null;
function ensureTable() {
  if (_table) return _table;
  _table = (async () => {
    await X.ensure();
    await C().query(`CREATE TABLE IF NOT EXISTS opsr_decks (
        id bigserial PRIMARY KEY, week date NOT NULL, kind text NOT NULL, name text, mime text, size int, sha256 text, data bytea, slides int,
        content jsonb, report jsonb, sig text, partial boolean NOT NULL DEFAULT false, missing text[] NOT NULL DEFAULT '{}', trigger text, error text,
        created_by text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (week, kind))`);
  })().catch(e => { _table = null; throw e; });
  return _table;
}
const BUSY = new Map();                                        // week → promise (this process)

/* ---------------------------------------------------------------- what the decks need for one week */
const teamBy = k => X.teams().find(t => t.key === k) || null;
function usedKeys(cfg) {
  const s = new Set(); cfg.domains.forEach(d => d.sources.forEach(x => s.add(x.team))); cfg.areas.forEach(a => a.teams.forEach(k => s.add(k)));
  return [...s];
}
async function plan(week) {
  const cfg = X.cfg().deck;
  const keys = usedKeys(cfg), unknown = keys.filter(k => !teamBy(k)), req = keys.map(teamBy).filter(t => t && t.active);
  const reps = (await C().query(`SELECT r.id, r.team_id, r.status, r.data, r.late, r.submitted_at, r.updated_at FROM opsr_reports r WHERE r.week=$1`, [week])).rows;
  const files = (await C().query(`SELECT id, report_id, team_id, name, size, created_at FROM opsr_files WHERE week=$1 ORDER BY created_at, id`, [week])).rows;
  const doneSt = cfg.when === 'approved' ? ['approved'] : ['submitted', 'approved'];
  const teams = req.map(t => {
    const rep = reps.find(r => Number(r.team_id) === t.id);
    return { key: t.key, id: t.id, name: t.name, vendor: t.vendor, status: rep ? rep.status : 'missing', done: !!rep && doneSt.includes(rep.status), late: !!(rep && rep.late),
      files: files.filter(f => Number(f.team_id) === t.id).length, deckFiles: files.filter(f => Number(f.team_id) === t.id && DECK_EXT.test(f.name)).length };
  });
  const sig = crypto.createHash('sha256').update(JSON.stringify({ cfg: { d: cfg.domains, a: cfg.areas, w: cfg.when, p: cfg.maxPdfPages },
    r: req.map(t => { const r = reps.find(x => Number(x.team_id) === t.id); return r ? [t.key, Number(r.id), r.status, r.updated_at && new Date(r.updated_at).toISOString()] : [t.key]; }),
    f: files.filter(f => req.some(t => t.id === Number(f.team_id))).map(f => Number(f.id)) })).digest('hex');
  return { week, teams, unknown, ready: teams.length > 0 && teams.every(t => t.done), waiting: teams.filter(t => !t.done), sig, reps, files, doneSt };
}

/* the files of one source: the team's report files of the week that can go in a deck (pptx · pdf) whose name holds
   one of the words of `file` ("a|b"), the latest upload of a name only. Without words: the decks (pptx) — a PDF only
   when the team sent no deck — and never a mail saved as PDF ("Fw …", "Re …": the cover mail ITSM keeps with it). */
const MAIL_PDF = /^(fw|fwd|re|tr)\b[\s:_-]/i;
function sourceFiles(p, src) {
  const t = teamBy(src.team); if (!t) return [];
  const words = (src.file || '').split('|').map(lc).filter(Boolean);
  const byName = new Map();
  p.files.filter(f => Number(f.team_id) === t.id && DECK_EXT.test(f.name) && (!words.length || words.some(w => lc(f.name).includes(w))))
    .forEach(f => byName.set(lc(f.name), f));
  let fl = [...byName.values()];
  if (!words.length) { fl = fl.filter(f => !(/\.pdf$/i.test(f.name) && MAIL_PDF.test(f.name))); if (fl.some(f => /\.pptx$/i.test(f.name))) fl = fl.filter(f => /\.pptx$/i.test(f.name)); }
  return fl;
}

/* ---------------------------------------------------------------- the executive text, from the reports */
const clip = (s, n) => { s = String(s || '').replace(/\s+/g, ' ').trim(); if (s.length <= n) return s; const cut = s.slice(0, n - 1), i = cut.lastIndexOf(' '); return (i > n * 0.6 ? cut.slice(0, i) : cut).replace(/[\s,;:·–-]+$/, '') + '…'; };
const dot = s => /[.!?…]$/.test(s) ? s : s + '.';
function sentences(arr, n) {
  let out = '';
  for (const s0 of arr) { const s = String(s0 || '').replace(/\s+/g, ' ').trim(); if (!s) continue; const t = dot(s);
    if (!out) { out = clip(t, n); continue; } if (out.length + 1 + t.length <= n) out += ' ' + t; else break; }
  return out;
}
const shortArea = n => { const x = String(n || '').replace(/\s+operations$/i, '').trim(), p = x.split(/\s[–—-]\s/); return p[p.length - 1] || x; };
const short = t => { const n = String(t.name || t.key).replace(/\s+operations?$/i, '').trim(); const parts = n.split(/\s[–—-]\s/); return parts[parts.length - 1] || n; };
const fmtN = v => typeof v === 'number' ? (Math.abs(v) >= 1000 ? v.toLocaleString('en-US') : String(Math.round(v * 100) / 100)) : String(v);
const kv = k => k.value == null ? '—' : fmtN(k.value) + (k.unit === '%' ? '%' : k.unit ? ' ' + k.unit : '');
const rangeShort = (a, b) => `${X.fmtDay(a)} – ${X.fmtDay(b)} ${b.slice(0, 4)}`;
const rangeLong = (a, b) => { const d1 = new Date(a + 'T00:00:00Z'), d2 = new Date(b + 'T00:00:00Z');
  return `${d1.getUTCDate()} ${MONTHS[d1.getUTCMonth()]}${d1.getUTCFullYear() !== d2.getUTCFullYear() ? ' ' + d1.getUTCFullYear() : ''} – ${d2.getUTCDate()} ${MONTHS[d2.getUTCMonth()]} ${d2.getUTCFullYear()}`; };

async function autoContent(week, p) {
  const cfg = X.cfg(), dk = cfg.deck, to = X.addDays(week, 6);
  const active = X.teams().filter(t => t.active);
  const repOf = t => { const r = p.reps.find(x => Number(x.team_id) === t.id); return r && ['submitted', 'approved', 'returned'].includes(r.status) ? r : null; };
  const reported = active.filter(repOf), missing = active.filter(t => !repOf(t)), late = reported.filter(t => repOf(t).late);
  const acts = await X.listActions().catch(() => []);
  const ragOf = t => { const r = repOf(t); return r && r.data ? (r.data.rag || r.data.ragAuto || null) : null; };

  // the 6 executive areas
  const rows = dk.areas.map(a => {
    const ts = a.teams.map(teamBy).filter(t => t && t.active), many = ts.length > 1;
    const outs = [], att = [];
    ts.forEach(t => {
      const r = repOf(t), d = (r && r.data) || {}, pre = many ? short(t) + ': ' : '';
      if (!r) { outs.push(`${pre}report not received`); att.push(`${short(t)} report missing`); return; }
      const kp = (d.kpis || []).filter(k => k.value != null).slice(0, 2).map(k => `${k.name} ${kv(k)}`).join(', ');
      outs.push(pre + (d.headline || (d.highlights || [])[0] || kp || 'reported, no headline'));
      if (d.support) att.push(d.support);
      (d.risks || []).filter(x => x.severity === 'high').slice(0, 2).forEach(x => att.push(x.title));
      (d.kpis || []).filter(k => k.status === 'missed').slice(0, 2).forEach(k => att.push(`${k.name} ${kv(k)} (target ${k.cmp === '<=' ? '≤' : '≥'} ${fmtN(k.target)}${k.unit === '%' ? '%' : ''})`));
      if ((d.lowlights || [])[0]) att.push(d.lowlights[0]);
      const ws = acts.filter(x => x.teamId === t.id && x.overdue).length; if (ws) att.push(`${ws} ${short(t)} action${ws > 1 ? 's' : ''} past ETA`);
    });
    return [a.name, sentences(outs, 150) || 'No team mapped to this area.', sentences(att, 115) || 'No escalation this week.'];
  });

  // brief
  const red = dk.areas.filter(a => a.teams.some(k => { const t = teamBy(k); return t && ragOf(t) === 'red'; })).map(a => a.name);
  const amber = dk.areas.filter(a => !red.includes(a.name) && a.teams.some(k => { const t = teamBy(k); return t && ragOf(t) === 'amber'; })).map(a => a.name);
  const attention = [];
  reported.forEach(t => { const d = repOf(t).data || {}; (d.risks || []).filter(x => x.severity === 'high').slice(0, 1).forEach(x => attention.push(clip(x.title, 80))); if (d.support) attention.push(clip(d.support, 80)); });
  const brief = clip([
    `${reported.length} of ${active.length} teams reported for ${rangeShort(week, to)}${late.length ? ` (${late.length} after the due time)` : ''}${missing.length ? `; not received: ${missing.map(short).join(', ')}` : ''}.`,
    red.length ? `Red: ${red.map(shortArea).join(', ')}.` : '', amber.length ? `Amber: ${amber.map(shortArea).join(', ')}.` : '', !red.length && !amber.length && reported.length ? 'All reported areas are green.' : '',
    attention.length ? `Leadership attention: ${attention.slice(0, 2).join('; ')}.` : ''
  ].filter(Boolean).join(' '), 420);

  // headline lines
  const kpis = [], sum = {};
  reported.forEach(t => { const d = repOf(t).data || {}; (d.kpis || []).forEach(k => kpis.push({ ...k, team: t }));
    Object.entries(d.counters || {}).forEach(([k, v]) => { if (v != null) sum[k] = (sum[k] || 0) + Number(v); }); });
  const rated = kpis.filter(k => k.status), off = rated.filter(k => k.status !== 'met');
  const headlines = [];
  if (rated.length) headlines.push(`• KPIs: ${rated.length - off.length} of ${rated.length} on target${off.length ? ' · off target: ' + off.slice(0, 2).map(k => `${k.name} ${kv(k)} (${short(k.team)})`).join(', ') : ''}`);
  const inc = [['inc_opened', 'opened'], ['inc_resolved', 'resolved'], ['p1', 'P1'], ['p2', 'P2'], ['sla_breached', 'SLA breached']].filter(([k]) => sum[k] != null).map(([k, l]) => /^P|SLA/.test(l) ? `${l} ${sum[k]}` : `${sum[k]} ${l}`);
  if (inc.length) headlines.push('• Incidents: ' + inc.join(' · '));
  const chg = [['chg_done', 'done'], ['chg_failed', 'failed'], ['chg_emergency', 'emergency']].filter(([k]) => sum[k] != null).map(([k, l]) => `${sum[k]} ${l}`);
  if (chg.length) headlines.push('• Changes: ' + chg.join(' · '));
  const open = acts.length, overdue = acts.filter(a => a.overdue).length, salam = acts.filter(a => a.status === 'waiting_salam' || a.salamDep).length;
  headlines.push(`• Reports: ${reported.length} of ${active.length} received${late.length ? ` (${late.length} late)` : ''} · actions: ${open} open, ${overdue} overdue, ${salam} waiting on Salam`);

  // focus for next week
  const focus = [], seen = new Set(), add = s => { s = clip(s, 165); const k = lc(s).slice(0, 60); if (s && !seen.has(k)) { seen.add(k); focus.push(s); } };
  // one escalation per team first (high risks, then support asked), red teams before amber, then a second round
  const rank = t => ({ red: 0, amber: 1, green: 2 }[ragOf(t)] == null ? 3 : { red: 0, amber: 1, green: 2 }[ragOf(t)]);
  const asks = reported.slice().sort((a, b) => rank(a) - rank(b)).map(t => { const d = repOf(t).data || {};
    return [...(d.risks || []).filter(x => x.severity === 'high').map(x => `${short(t)}: ${x.title}${x.mitigation ? ' — ' + x.mitigation : ''}`), ...(d.support ? [`${short(t)}: ${d.support}`] : [])]; });
  for (let round = 0; round < 2; round++) asks.forEach(l => { if (l[round] && focus.length < 4) add(l[round]); });
  active.forEach(t => { const n = acts.filter(a => a.teamId === t.id && a.overdue && (a.status === 'waiting_salam' || a.salamDep)).length; if (n) add(`Salam owners to clear the ${n} overdue ${short(t)} action${n > 1 ? 's' : ''} waiting on Salam.`); });
  reported.filter(t => ['red', 'amber'].includes(ragOf(t))).forEach(t => { const d = repOf(t).data || {}; if ((d.nextWeek || [])[0]) add(`${short(t)}: ${d.nextWeek[0]}`); });
  if (missing.length) add(`Get the ${missing.map(short).join(', ')} report${missing.length > 1 ? 's' : ''} in the pack by ${DAYS[cfg.dueDay]} ${cfg.dueTime}.`);
  if (late.length) add(`Every report on time: due ${DAYS[cfg.dueDay]} ${cfg.dueTime} KSA (${late.length} late this week).`);
  if (!focus.length) add(`Keep the weekly rhythm: every report by ${DAYS[cfg.dueDay]} ${cfg.dueTime} KSA.`);

  return { cover_sub: `Weekly Executive Report · ${rangeShort(week, to)}`, brief_title: `Executive Weekly Brief | ${rangeLong(week, to)}`, brief,
    headlines: headlines.slice(0, 4).map(h => clip(h, 160)), rows, focus: focus.slice(0, 6), edited: false, autoAt: new Date().toISOString() };
}
function normContent(c, base) {
  c = c && typeof c === 'object' ? c : {}; base = base || {};
  const ln = (v, n, m) => (Array.isArray(v) ? v : String(v || '').split('\n')).map(s => str(s, m)).filter(Boolean).slice(0, n);
  const rows = (Array.isArray(c.rows) ? c.rows : base.rows || []).slice(0, 6).map(r => [0, 1, 2].map(i => str((r || [])[i], 400) || ''));
  return { cover_sub: str(c.cover_sub, 160) || base.cover_sub || '', brief_title: str(c.brief_title, 160) || base.brief_title || '', brief: str(c.brief, 900) || '',
    headlines: ln(c.headlines, 5, 220), rows, focus: ln(c.focus, 7, 260) };
}

/* ---------------------------------------------------------------- build */
const fileNames = week => { const to = X.addDays(week, 6), d1 = new Date(week + 'T00:00:00Z'), d2 = new Date(to + 'T00:00:00Z'), M = m => MONTHS[m].slice(0, 3), dd = n => String(n).padStart(2, '0');
  return { exec: `Operational_Weekly_Executive_Report_${d1.getUTCDate()}${M(d1.getUTCMonth())}-${dd(d2.getUTCDate())}${M(d2.getUTCMonth())}-${d2.getUTCFullYear()}.pptx`,
    complete: `Application_Operational_weekly_status_report_${dd(d2.getUTCDate())}_${M(d2.getUTCMonth())}_${d2.getUTCFullYear()}.pptx` }; };
const PPTX = 'application/vnd.openxmlformats-officedocument.presentationml.presentation';
async function store(week, kind, o) {
  const sha = o.buf ? crypto.createHash('sha256').update(o.buf).digest('hex') : null;
  await C().query(`INSERT INTO opsr_decks (week, kind, name, mime, size, sha256, data, slides, content, report, sig, partial, missing, trigger, error, created_by, created_at)
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb,$11,$12,$13,$14,$15,$16, now())
      ON CONFLICT (week, kind) DO UPDATE SET name=EXCLUDED.name, mime=EXCLUDED.mime, size=EXCLUDED.size, sha256=EXCLUDED.sha256, data=EXCLUDED.data, slides=EXCLUDED.slides,
        content=EXCLUDED.content, report=EXCLUDED.report, sig=EXCLUDED.sig, partial=EXCLUDED.partial, missing=EXCLUDED.missing, trigger=EXCLUDED.trigger, error=EXCLUDED.error,
        created_by=EXCLUDED.created_by, created_at=now()`,
    [week, kind, o.name, PPTX, o.buf ? o.buf.length : null, sha, o.buf || null, o.slides || null, o.content ? JSON.stringify(o.content) : null, o.report ? JSON.stringify(o.report) : null,
      o.sig || null, !!o.partial, o.missing || [], o.trigger || null, o.error || null, o.by || null]);
}
async function savedContent(week) {
  const r = await C().query(`SELECT content FROM opsr_decks WHERE week=$1 AND kind='exec'`, [week]);
  return r.rowCount ? r.rows[0].content : null;
}
async function buildExecFor(week, p, tpl, content) {
  const ex = await deck.buildExec({ template: tpl, content });
  return ex;
}
async function domainInputs(week, p) {
  const dk = X.cfg().deck, range = rangeShort(week, X.addDays(week, 6));
  const want = new Map();
  const doms = dk.domains.map(d => {
    const notes = d.note ? [d.note] : [], sources = [];
    d.sources.forEach(s => {
      const t = teamBy(s.team), st = p.teams.find(x => x.key === s.team);
      if (!t) { notes.push(`Team “${s.team}” is not in Operations reports › Teams`); sources.push({ label: s.team, missing: 'unknown team' }); return; }
      if (!t.active) { sources.push({ label: t.name, missing: 'team inactive' }); return; }
      if (!st || !st.done) { notes.push(`${t.name}: report not received for ${range}`); sources.push({ label: t.name, missing: st ? st.status : 'missing' }); return; }
      const fl = sourceFiles(p, s);
      if (!fl.length) {
        const all = p.files.filter(f => Number(f.team_id) === t.id).map(f => f.name);
        const r = p.reps.find(x => Number(x.team_id) === t.id), hl = r && r.data && r.data.headline;
        notes.push(`${t.name}: no slide deck in this week's report${all.length ? ` (${all.slice(0, 2).join(', ')})` : ''}${hl ? ' — ' + clip(hl, 120) : ''}`);
        sources.push({ label: t.name, missing: 'no pptx / pdf' }); return;
      }
      fl.forEach(f => { want.set(Number(f.id), null); sources.push({ label: t.name, fileId: Number(f.id), name: f.name, slides: s.slides }); });
    });
    return { name: d.name, note: notes, sources };
  });
  if (want.size) {
    const r = await C().query(`SELECT id, data FROM opsr_files WHERE id = ANY($1::bigint[])`, [[...want.keys()]]);
    r.rows.forEach(x => want.set(Number(x.id), x.data));
  }
  doms.forEach(d => d.sources.forEach(s => { if (s.fileId) s.buf = want.get(s.fileId) || null; if (s.fileId && !s.buf) s.missing = 'file not found'; }));
  return doms;
}
function generate(week, { by, trigger } = {}) {
  if (BUSY.has(week)) return BUSY.get(week);
  const job = (async () => {
    await ensureTable(); await X.loadCfg();
    const t0 = Date.now();
    const p = await plan(week);
    const tpl = await fs.promises.readFile(TEMPLATE);
    const names = fileNames(week);
    const saved = await savedContent(week);
    const content = saved && saved.edited ? saved : await autoContent(week, p);
    const missing = p.waiting.map(t => t.name);
    const common = { sig: p.sig, partial: !p.ready, missing, trigger: trigger || 'manual', by: by || null };
    const ex = await buildExecFor(week, p, tpl, content);
    await store(week, 'exec', { ...common, name: names.exec, buf: ex.buf, slides: ex.slides, content });
    const cp = await deck.buildComplete({ template: tpl, date: deck.coverDate(X.addDays(week, 6)), domains: await domainInputs(week, p), maxPdfPages: X.cfg().deck.maxPdfPages });
    await store(week, 'complete', { ...common, name: names.complete, buf: cp.buf, slides: cp.slides, report: cp.report });
    const out = { week, ready: p.ready, missing, exec: { slides: ex.slides, size: ex.buf.length }, complete: { slides: cp.slides, size: cp.buf.length }, ms: Date.now() - t0 };
    console.log(`[opsreports] decks ${week} built (${trigger || 'manual'}${p.ready ? '' : ', partial'}) · exec ${ex.slides} slides · complete ${cp.slides} slides · ${out.ms} ms`);
    return out;
  })().finally(() => BUSY.delete(week));
  BUSY.set(week, job);
  return job;
}

/* every minute (opsReports.tick): build when every team the decks use is in, or rebuild when one of them changed */
let lastErr = 0;
async function auto() {
  if (!X) return;
  const dk = X.cfg().deck; if (!dk || !dk.auto) return;
  if (!fs.existsSync(TEMPLATE)) { if (Date.now() - lastErr > 3600e3) { lastErr = Date.now(); console.error('[opsreports] decks: template missing at ' + TEMPLATE); } return; }
  await ensureTable();
  const w0 = X.defaultWeek();
  for (const week of [w0, X.addDays(w0, -7)]) {
    if (BUSY.has(week)) continue;
    const p = await plan(week); if (!p.ready) continue;
    const cur = await C().query(`SELECT sig FROM opsr_decks WHERE week=$1 AND kind='complete'`, [week]);
    if (cur.rowCount && cur.rows[0].sig === p.sig) continue;
    const key = `deck:${week}:${p.sig.slice(0, 16)}`;
    if (!(await X.claim(key))) continue;
    try {
      const out = await generate(week, { by: 'schedule', trigger: 'auto' });
      await C().query(`UPDATE opsr_jobs SET ok=true, result=$2::jsonb WHERE key=$1`, [key, JSON.stringify({ exec: out.exec, complete: out.complete })]);
    } catch (e) {
      console.error(`[opsreports] decks ${week}:`, e.message);
      await C().query(`UPDATE opsr_jobs SET result=$2::jsonb WHERE key=$1`, [key, JSON.stringify({ error: e.message })]).catch(() => {});
    }
  }
}

/* ---------------------------------------------------------------- read */
async function summary(week, withContent) {
  await ensureTable();
  const rows = (await C().query(`SELECT id, kind, name, size, slides, content, report, sig, partial, missing, trigger, error, created_by, created_at FROM opsr_decks WHERE week=$1`, [week])).rows;
  const meta = k => { const r = rows.find(x => x.kind === k); return r && r.size ? { id: Number(r.id), name: r.name, size: r.size, slides: r.slides, partial: r.partial, missing: r.missing || [],
    trigger: r.trigger, createdBy: r.created_by, createdAt: r.created_at, sig: r.sig, report: k === 'complete' ? r.report : undefined } : null; };
  const ex = rows.find(x => x.kind === 'exec');
  return { exec: meta('exec'), complete: meta('complete'), content: withContent && ex ? ex.content : undefined, edited: !!(ex && ex.content && ex.content.edited) };
}

/* the decks of every week since `from` (Library) */
async function list(from) {
  await ensureTable();
  return (await C().query(`SELECT id, to_char(week,'YYYY-MM-DD') week, kind, name, size, slides, partial, created_at FROM opsr_decks WHERE week >= $1 AND size IS NOT NULL ORDER BY week DESC, kind DESC`, [from])).rows
    .map(r => ({ id: Number(r.id), week: r.week, kind: r.kind, name: r.name, size: r.size, slides: r.slides, partial: r.partial, createdAt: r.created_at }));
}

/* ---------------------------------------------------------------- routes */
function mount(app, ctx) {
  X = ctx;
  const ok = fn => async (req, res) => { try { await fn(req, res); } catch (e) { res.status(e.status || 500).json({ error: e.message }); } };
  const editor = req => { const w = X.who(req); return w.editor && !w.readOnly ? w : null; };
  const weekQ = v => { const w = X.isDay(v) ? X.weekOf(v) : X.defaultWeek(); return w; };

  app.get('/api/opsreports/decks', ok(async (req, res) => {
    await X.ensure(); await X.loadCfg(); await ensureTable();
    const week = weekQ(req.query.week), p = await plan(week), s = await summary(week, true), w = X.who(req), dk = X.cfg().deck;
    const dir = await X.people().catch(() => ({}));
    let preview = null;
    if (!s.content && w.editor) preview = await autoContent(week, p).catch(() => null);
    res.json({ week, auto: dk.auto, when: dk.when, ready: p.ready, building: BUSY.has(week), templateOk: fs.existsSync(TEMPLATE),
      teams: p.teams.map(t => ({ key: t.key, name: t.name, vendor: t.vendor, status: t.status, done: t.done, late: t.late, files: t.files, deckFiles: t.deckFiles })),
      unknown: p.unknown, stale: !!(s.complete && s.complete.sig !== p.sig),
      exec: s.exec && { ...s.exec, sig: undefined, createdByName: X.nameOf(dir, s.exec.createdBy) },
      complete: s.complete && { ...s.complete, sig: undefined, createdByName: X.nameOf(dir, s.complete.createdBy) },
      content: w.editor ? (s.content || preview) : undefined, edited: s.edited, canBuild: !!editor(req), areas: dk.areas.map(a => a.name) });
  }));
  app.get('/api/opsreports/decks/:id/download', ok(async (req, res) => {
    await ensureTable();
    const r = await C().query(`SELECT name, mime, data, kind, to_char(week,'YYYY-MM-DD') week FROM opsr_decks WHERE id=$1`, [req.params.id]);
    if (!r.rowCount || !r.rows[0].data) return res.status(404).json({ error: 'no such deck' });
    const f = r.rows[0];
    if (X.audit) X.audit(req, 'opsreports.deck.download', String(req.params.id), { kind: f.kind, week: f.week });
    res.setHeader('Content-Type', f.mime || PPTX);
    res.setHeader('Content-Disposition', `attachment; filename="${String(f.name).replace(/[^\w.\- ()]+/g, '_')}"`);
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.end(f.data);
  }));
  app.post('/api/opsreports/decks/generate', ok(async (req, res) => {
    const w = editor(req); if (!w) return res.status(403).json({ error: 'ITSM editors and admins only' });
    if (!fs.existsSync(TEMPLATE)) return res.status(500).json({ error: 'the deck template is missing on this server (server/templates/opsreports-deck-template.pptx) — deploy again' });
    const week = weekQ((req.body || {}).week);
    const out = await generate(week, { by: w.email, trigger: 'manual' });
    if (X.audit) X.audit(req, 'opsreports.deck.generate', week, { partial: !out.ready, exec: out.exec.slides, complete: out.complete.slides });
    res.json({ ok: true, ...out });
  }));
  app.put('/api/opsreports/decks/content', ok(async (req, res) => {
    const w = editor(req); if (!w) return res.status(403).json({ error: 'ITSM editors and admins only' });
    await ensureTable(); await X.loadCfg();
    const b = req.body || {}, week = weekQ(b.week), p = await plan(week);
    const auto = await autoContent(week, p);
    const content = b.reset ? auto : { ...normContent(b.content, auto), edited: true, editedBy: w.email, editedAt: new Date().toISOString() };
    const tpl = await fs.promises.readFile(TEMPLATE);
    const ex = await buildExecFor(week, p, tpl, content);
    const cur = await C().query(`SELECT sig, partial, missing, trigger FROM opsr_decks WHERE week=$1 AND kind='exec'`, [week]);
    const c0 = cur.rows[0] || {};
    await store(week, 'exec', { name: fileNames(week).exec, buf: ex.buf, slides: ex.slides, content, sig: c0.sig || null, partial: c0.sig ? c0.partial : !p.ready,
      missing: c0.sig ? c0.missing : p.waiting.map(t => t.name), trigger: b.reset ? 'reset' : 'edited', by: w.email });
    if (X.audit) X.audit(req, 'opsreports.deck.content', week, { reset: !!b.reset });
    res.json({ ok: true, content, slides: ex.slides });
  }));
}

module.exports = { mount, auto, summary, list, generate, plan, autoContent, normDeck, DEFAULT_DECK, TEMPLATE };
