/* Built-in alert rules — seeded into alert_rules. Mirrors the Salam Ops
 * console rule set and extends it across the MVNO journeys/integrations.
 * operator: gt gte lt lte eq  ·  severity: P1..P4  ·  window in hours
 * active_from/active_to: KSA hours (null = always). dim: dimension filter. */

const { METRICS } = require('./metrics');

const CATALOG = Object.entries(METRICS).map(([key, m]) => ({
  key, label: m.label, unit: m.unit, higher_is_bad: m.higherIsBad, source_tables: m.sourceTables
}));

const RULES = [
  // ---------- P1 : platform-wide, money-at-risk ----------
  { key: 'payment_fail_storm', name: 'Payment failure storm (P1)', severity: 'P1', team: 'Digital Ops',
    metric_key: 'payment_fail_rate', operator: 'gte', threshold: 0.40, window_hours: 1, min_sample: 30,
    description: 'Card/gateway failures above 40% in the last hour — treat as a platform-wide payment incident.',
    runbook: '1) Troubleshoot → Payment/gateway: see which gateway dominates (UPG/Tap/HyperPay) and the top decline code·message. 2) One gateway failing → page that provider; spread across all → suspect our checkout/token service. 3) Use the decline drill-down for a systemic code (auth/3DS/CVV). 4) If platform-wide, open a P1 and consider pausing the failing gateway/route. 5) Page Payments L2.' },
  { key: 'payment_zatca_gap', name: 'ZATCA reporting gap (P1)', severity: 'P1', team: 'Digital Ops',
    metric_key: 'zatca_unreported', operator: 'gte', threshold: 800, window_hours: 3, min_sample: 0,
    description: 'Successful payments not reported to ZATCA surging past the steady backlog (~500) — e-invoicing pipeline stalling.',
    runbook: '1) Payments succeeded but are not reaching ZATCA (ClearTax) — check the e-invoicing worker/queue is running and not erroring. 2) Look for auth/cert expiry or ClearTax 5xx in logs. 3) The backlog clears once the pipeline resumes — confirm the count falls. 4) Engage the ZATCA/ClearTax integration owner if the worker is healthy but rejects persist. 5) Compliance-sensitive: keep the incident updated.' },
  { key: 'payment_stuck_storm', name: 'Payments stuck "Initiated" — Tap callback failing (P1)', severity: 'P1', team: 'Digital Ops',
    metric_key: 'payment_stuck_initiated', operator: 'gte', threshold: 700, window_hours: 1, min_sample: 0,
    description: 'Payments left Initiated/pending >30min surging (~4x the ~170/hr abandonment baseline) — Tap→app confirmation (webhook) likely down: customers charged while the app shows unpaid. Reconcile with Tap; replay callbacks. Authoritative paging = the Tap-confirmed mismatch metric.',
    runbook: '1) Confirm the Tap/UPG callback endpoint is up (webhook 200s). 2) In Troubleshoot → Payment stuck, grab the payment_reference_ids. 3) Reconcile each ref against Tap (CAPTURED?). 4) Replay/settle the confirmation so the app flips to success (or refund if not captured). 5) Page BSS/Payments L2 if the callback pipeline is down.' },
  { key: 'payment_stuck_spike', name: 'Payments stuck "Initiated" spike (P2)', severity: 'P2', team: 'Digital Ops',
    metric_key: 'payment_stuck_initiated', operator: 'gte', threshold: 400, window_hours: 1, min_sample: 0,
    description: 'Unconfirmed payments (Initiated >30min) ~2.5x the ~170/hr abandonment baseline — early sign of a Tap callback / reconciliation problem.',
    runbook: '1) Early sign of the Tap-callback / reconciliation lag. 2) Troubleshoot → Payment stuck: note the trend and grab a few payment_reference_ids. 3) Spot-check them against Tap (CAPTURED but app shows unpaid?). 4) If it keeps climbing toward the P1 threshold, treat as the Tap-callback incident (see Payments stuck storm). 5) No mass action yet — watch and reconcile samples.' },
  { key: 'payment_duplicate', name: 'Duplicate charge suspected — customers deducted twice (P1)', severity: 'P1', team: 'Digital Ops',
    metric_key: 'payment_duplicate_suspect', operator: 'gte', threshold: 25, window_hours: 6, min_sample: 0,
    description: 'Same customer+amount charged 2+ times within 30min surging (~3.5x the ~7/6h baseline) — suspected double deduction (UPG/Tap captured twice). Reconcile with Tap by order id; refund confirmed duplicates. Authoritative paging = the Tap-confirmed duplicate metric.',
    runbook: '1) Troubleshoot → Payment duplicate: list the customer/amount/refs. 2) In Tap, look up the order id — 2 CAPTURED charges = real duplicate. 3) Refund the extra capture; log the case. 4) If volume is rising, engage UPG/Tap on the double-capture root cause (retry/idempotency).' },
  { key: 'activation_fail_storm', name: 'Activation failure storm (P1)', severity: 'P1', team: 'Digital Ops',
    metric_key: 'activation_fail_rate', operator: 'gte', threshold: 0.70, window_hours: 1, min_sample: 20,
    description: 'BSS activation failures well above the ~45% baseline — a genuine storm, not the chronic level.',
    runbook: '1) Troubleshoot → Activation (BSS): identify the failing step / Oracle BSS error. 2) Check BSS availability and the Semati/MSISDN provisioning alerts — activation often fails downstream of Semati. 3) If BSS is up, isolate the dominant activation error code. 4) Page BSS / Digital Ops L2; hold retries if BSS is down to avoid a pile-up.' },
  { key: 'semati_fail_storm', name: 'Semati provisioning storm (P1)', severity: 'P1', team: 'Digital Ops',
    metric_key: 'semati_fail_rate', operator: 'gte', threshold: 0.75, window_hours: 1, min_sample: 20,
    description: 'MSISDN provisioning failing well above the ~55% baseline (SEMATI_FAILED / MOBILE_EXISTS) — real deterioration.',
    runbook: '1) Troubleshoot → Semati: separate provider errors (715 / transport — see the Semati provider alerts) from business failures (MOBILE_EXISTS / SEMATI_FAILED). 2) 715/transport dominate → provider-down path (contact TCC). 3) MOBILE_EXISTS dominates → number-pool / duplicate issue, not an outage. 4) Correlate with the CITC composite alert. 5) Page Digital Ops L2.' },
  { key: 'nafath_fail_storm', name: 'Nafath failure storm (P1)', severity: 'P1', team: 'Digital Ops',
    metric_key: 'nafath_fail_rate', operator: 'gte', threshold: 0.50, window_hours: 1, min_sample: 20,
    description: 'Identity verification (Nafath) failing above 50% within the hour — blocks new-line onboarding; page on-call.',
    runbook: '1) Troubleshoot → Nafath/identity: confirm the failure type (timeout, rejected, provider 5xx). 2) Check the CITC composite alert — if Semati is also breaching, it is a shared CITC/Absher upstream issue. 3) If Nafath-only, verify our IAM/Absher integration (token/cert). 4) Nafath gates new-line onboarding — open a P1 and page on-call.' },

  // ---------- P1 : Semati (TCC) provider connectivity — incident #28713 ----------
  { key: 'semati_provider_down', name: 'Semati provider unreachable (715 / connection reset) (P1)', severity: 'P1', team: 'Digital Ops',
    metric_key: 'semati_provider_error_rate', operator: 'gte', threshold: 0.50, window_hours: 0.25, min_sample: 8,
    description: 'Over half of Semati calls in the last 15 min are returning 715 "Service is not available" or transport errors (Connection reset / SSLException / HTTP 408) — the TCC provider is down or unreachable. Blocks eligibility + activation. Same signature as #28713.',
    runbook: '1) Troubleshoot → Semati: confirm the codes — 715 = provider app refusing ("Service Not Available"); 5002/408/Connection reset = transport/TLS. Intermittent 715 is the #28713 / #28812 signature (also shows in ELIGIBILITY, not just activation). 2) Check the CITC composite alert — if Nafath is also breaching, it is a shared TCC/CITC upstream issue (not our side). 3) Contact TCC Customer Success (customersuccess@tcc-ict.com, +966920003604) — now the PRIMARY TCC support channel (Semati Support is being retired). If the Semati portal is unreachable you cannot self-submit a request, so email Customer Success directly and open the P-ticket. 4) If transport-only: check our egress/DNS/TLS to semati.tcc-ict.com (login + eligibility/v2). 5) Blast radius: this blocks Activation, MNP, Eligibility, Change Plan and SIM Swap — flag all in the incident. Keep the ticket updated; page Digital Ops L2.' },
  { key: 'semati_login_down', name: 'Semati login endpoint down — gates everything (P1)', severity: 'P1', team: 'Digital Ops',
    metric_key: 'semati_provider_error_rate', operator: 'gte', threshold: 0.50, window_hours: 0.25, min_sample: 5,
    dim: { endpoint: 'login' },
    description: 'The Semati login endpoint is failing ≥50% in the last 15 min. Login gates every downstream Semati call (eligibility/provisioning), so this is the earliest hard-impact signal — treat as provider-down even if eligibility still shows some success.',
    runbook: '1) Login gates every downstream Semati call — treat as provider-down. 2) Troubleshoot → Semati: confirm login 715/transport codes. 3) Distinguish credentials rejected (auth) vs endpoint unreachable (transport) to semati.tcc-ict.com. 4) Contact TCC Customer Success (customersuccess@tcc-ict.com, +966920003604); page Digital Ops L2.' },
  { key: 'semati_eligibility_down', name: 'Semati eligibility endpoint down (P2)', severity: 'P2', team: 'Digital Ops',
    metric_key: 'semati_provider_error_rate', operator: 'gte', threshold: 0.50, window_hours: 0.25, min_sample: 5,
    dim: { endpoint: 'eligibility' },
    description: 'The Semati ELIGIBILITY endpoint is failing ≥50% in the last 15 min (715 / transport) — eligibility checks blocked, which gates new-SIM and MNP. This is exactly where INC0012977 surfaced. Fires on its own when only eligibility is hit; grouped under provider-down when the whole provider is out.',
    runbook: '1) Troubleshoot → Semati (eligibility endpoint): confirm 715 "Service Not Available". 2) Correlate with the provider-down / CITC composite alert. 3) Contact TCC Customer Success (customersuccess@tcc-ict.com, +966920003604) — Semati Support is being retired. 4) Blocks Eligibility → Activation / MNP; flag the blast radius.' },
  { key: 'semati_hard_down', name: 'Semati zero-success watchdog (P1)', severity: 'P1', team: 'Digital Ops',
    metric_key: 'semati_success_volume', operator: 'lte', threshold: 0, window_hours: 1, min_sample: 20,
    description: 'Semati was called ≥20 times in the last hour with zero successes — a hard outage. Fires even when a percentage looks noisy; the min-sample gate keeps it quiet when there is genuinely no traffic.',
    runbook: '1) Zero Semati successes with real traffic = hard outage. 2) Follow the Semati provider-unreachable runbook: confirm 715/transport codes, check the CITC composite, contact TCC. 3) Zero-success means do not wait for percentages — page on-call now.' },
  { key: 'citc_upstream_down', name: 'CITC upstream degraded — Semati + Nafath together (P1)', severity: 'P1', team: 'Digital Ops',
    metric_key: 'citc_upstream_degraded', operator: 'gte', threshold: 0.40, window_hours: 0.5, min_sample: 10,
    description: 'Both Semati AND Nafath are failing ≥40% at the same time — the shared TCC/CITC path is degraded, so this is provider-side, not ours. One P1 instead of a storm of per-endpoint pages.',
    runbook: '1) This is almost certainly upstream (TCC/CITC), not the DMS. 2) Confirm with TCC Customer Success (customersuccess@tcc-ict.com) — ask if a restart/maintenance is in progress on the source. 3) Post a single incident + status update; do not chase each endpoint separately. 4) Watch for recovery on both providers before closing.' },

  // ---------- P2 : degradations ----------
  { key: 'semati_provider_degraded', name: 'Semati provider errors rising (P2)', severity: 'P2', team: 'Digital Ops',
    metric_key: 'semati_provider_error_rate', operator: 'gte', threshold: 0.20, window_hours: 0.5, min_sample: 15,
    description: 'Semati 715 / transport errors ≥20% over 30 min — early degradation before a full outage. Watch for it climbing toward the P1 threshold.',
    runbook: '1) Early Semati degradation (715/transport 20–50%). 2) Troubleshoot → Semati: watch the error-rate trend — if it climbs toward 50% it escalates to the provider-down P1. 3) Pre-warn TCC if the trend is steep. 4) No mass action yet.' },
  { key: 'semati_transport_errors', name: 'Semati transport/TLS errors (P2)', severity: 'P2', team: 'Digital Ops',
    metric_key: 'semati_transport_error_rate', operator: 'gte', threshold: 0.15, window_hours: 0.5, min_sample: 10,
    description: 'Connection reset / SSLException / HTTP 408 to Semati ≥15% over 30 min — points at network/TLS/provider-infra rather than the provider app (distinct from 715).',
    runbook: '1) Transport-layer, not app: check DNS + TLS handshake + egress firewall to semati.tcc-ict.com (login and /TCC-Web/api/eligibility/v2). 2) If broad across providers, suspect our egress/proxy; if Semati-only, provider infra. 3) Correlate with the timeout (408) count for the leading edge.' },
  { key: 'semati_flapping', name: 'Semati flapping (intermittent) (P2)', severity: 'P2', team: 'Digital Ops',
    metric_key: 'semati_flapping', operator: 'gte', threshold: 6, window_hours: 0.5, min_sample: 20,
    description: '≥6 ok→fail transitions in 30 min — Semati is returning success and "Service Not Available" intermittently. This is the pattern a flat failure-rate threshold misses.',
    runbook: '1) Semati is flapping (success ↔ "Service Not Available") — usually provider instability or one load-balanced node failing. 2) Troubleshoot → Semati: confirm the ok↔fail pattern. 3) Flag to TCC as intermittent (harder for them to spot than a hard down). 4) Expect user-visible retries; watch for it hardening into a full outage.' },

  // ---------- P3 : watch ----------
  { key: 'semati_timeouts', name: 'Semati timeouts (HTTP 408) rising (P3)', severity: 'P3', team: 'Digital Ops',
    metric_key: 'semati_timeout_count', operator: 'gte', threshold: 15, window_hours: 0.5, min_sample: 0,
    description: 'HTTP 408 timeouts to Semati climbing — latency is rising and usually precedes connection resets. Early warning; escalates to the provider-error P1 if it continues.',
    runbook: '1) 408 timeouts to Semati rising — latency creeping up, often precedes connection resets. 2) Troubleshoot → Semati: watch the 408 count. 3) Early warning only; if it continues it escalates to the provider-error P1. 4) Note it on any open TCC thread.' },

  // ---------- P2 : degradations (journeys) ----------
  { key: 'payment_fail_spike', name: 'Payment failure spike (P2)', severity: 'P2', team: 'Digital Ops',
    metric_key: 'payment_fail_rate', operator: 'gte', threshold: 0.30, window_hours: 3, min_sample: 40,
    description: 'Payment failure rate elevated above the ~19% baseline over 3h (early degradation).',
    runbook: '1) Payment failures elevated over 3h — early degradation, not yet a storm. 2) Troubleshoot → Payment: check the leading gateway and top decline code. 3) Watch for it crossing the P1 storm threshold. 4) Sample a few declines to rule out a systemic code.' },
  { key: 'payment_web_fail', name: 'Web checkout failure spike (P2)', severity: 'P2', team: 'Digital Ops',
    metric_key: 'payment_fail_rate', operator: 'gte', threshold: 0.35, window_hours: 3, min_sample: 20,
    dim: { platform: 'web' }, description: 'Web e-purchase payment failures elevated — isolate from app.',
    runbook: '1) Web checkout failures elevated (isolated from app). 2) Troubleshoot → Payment, filter platform=web: check the web gateway / 3DS redirect flow. 3) Compare with the app failure rate — if app is healthy, it is a web-checkout/redirect issue. 4) Engage the web/checkout owner.' },
  { key: 'nafath_fail_spike', name: 'Nafath failure spike (P2)', severity: 'P2', team: 'Digital Ops',
    metric_key: 'nafath_fail_rate', operator: 'gte', threshold: 0.25, window_hours: 1, min_sample: 20,
    description: 'Identity verification (Nafath) failing ≥25% in the last hour — early degradation on the onboarding-critical path.',
    runbook: '1) Nafath failing ≥25%/1h — early degradation on the onboarding path. 2) Troubleshoot → Nafath: confirm the failure type. 3) Watch toward the 50% storm threshold; correlate with the CITC composite. 4) Pre-warn the IAM/Absher owner if it is climbing.' },
  { key: 'semati_fail_spike', name: 'Semati provisioning failure spike (P2)', severity: 'P2', team: 'Digital Ops',
    metric_key: 'semati_fail_rate', operator: 'gte', threshold: 0.65, window_hours: 24, min_sample: 20,
    description: 'MSISDN provisioning failing above the ~55% baseline — SEMATI_FAILED / MOBILE_EXISTS.',
    runbook: '1) Semati provisioning above baseline over 24h — mostly MOBILE_EXISTS / SEMATI_FAILED business failures. 2) Troubleshoot → Semati: confirm it is business (not 715/transport). 3) If MOBILE_EXISTS dominates, review the number pool / duplicate-order logic. 4) Not a provider outage unless the Semati provider alerts also fire.' },
  { key: 'eligibility_deny_spike', name: 'Eligibility denials (P2)', severity: 'P2', team: 'Sales Ops',
    metric_key: 'eligibility_deny_rate', operator: 'gte', threshold: 0.50, window_hours: 24, min_sample: 50,
    description: 'CITC eligibility DENIED above the ~37% baseline (real spike, not the chronic denial level).',
    runbook: '1) Troubleshoot → Eligibility: check the denial reasons — legitimate CITC policy (max lines / ID) vs a systemic error. 2) If one reason surges, engage the CITC/eligibility owner. 3) Sales Ops to review whether genuine customers are affected. 4) Distinguish from a Semati provider outage (that path shows 715/transport, not DENIED).' },
  { key: 'change_plan_fail_spike', name: 'Change Plan failure spike (P2)', severity: 'P2', team: 'Digital Ops',
    metric_key: 'change_plan_fail_rate', operator: 'gte', threshold: 0.30, window_hours: 24, min_sample: 15,
    description: 'Prepaid↔postpaid / plan migration failing in BSS above threshold.',
    runbook: '1) Troubleshoot → Change Plan: identify the BSS error on the plan-migration API. 2) Check BSS availability and the specific change-plan endpoint. 3) Engage BSS L2 if systemic. 4) Note whether it is prepaid→postpaid or the reverse to narrow the failing flow.' },
  { key: 'delivery_fail_spike', name: 'Delivery failure/return spike (P2)', severity: 'P2', team: 'Digital Ops',
    metric_key: 'delivery_fail_rate', operator: 'gte', threshold: 0.25, window_hours: 24, min_sample: 20,
    description: 'Courier returns/failures elevated across vendors.',
    runbook: '1) Troubleshoot → Delivery: see which courier(s) dominate (SMSA/OTO/Barq/iMile/etc.). 2) One courier → contact that vendor; all couriers → suspect address/data quality or our delivery feed. 3) Engage the logistics owner. 4) Check returns vs outright failures to target the fix.' },
  { key: 'delivery_stuck', name: 'Deliveries stuck in transit (P2)', severity: 'P2', team: 'Digital Ops',
    metric_key: 'delivery_stuck', operator: 'gte', threshold: 60000, window_hours: 48, min_sample: 0,
    description: 'Stuck-shipment backlog growing past the steady ~51k (in-transit states never finalised) — investigate courier callbacks.',
    runbook: '1) In-transit shipments not finalising (backlog past ~51k). 2) Troubleshoot → Delivery: check for missing courier status callbacks. 3) If a courier stopped sending updates, chase that vendor webhook/feed. 4) Reconcile stuck shipments before assuming they are lost.' },
  { key: 'samsung_pay_down', name: 'Samsung Pay failing — new method (P1)', severity: 'P1', team: 'Digital Ops',
    metric_key: 'samsung_pay_fail_rate', operator: 'gte', threshold: 0.60, window_hours: 1, min_sample: 8,
    description: 'Samsung Pay (launched recently) failing ≥60% in the last hour — a launch regression or a UPG-side Samsung Pay outage. Small min-sample because volume is still ramping.',
    runbook: '1) Troubleshoot → Payment, filter to Samsung Pay (payment_method/vendor ~ samsung): read the gateway code · message from the decline breakdown. 2) If one gateway code dominates, it is UPG/Samsung-Pay side — correlate the payment_reference_id against UPG (payment_commit_response.gateway.response). 3) Compare with card/mada success in the same window — if only Samsung Pay is failing, isolate to the Samsung Pay rail. 4) Engage Payments L2 / the Samsung Pay integration owner; consider hiding the Samsung Pay option if it is hard-down.' },
  { key: 'samsung_pay_fail_spike', name: 'Samsung Pay failure spike (P2)', severity: 'P2', team: 'Digital Ops',
    metric_key: 'samsung_pay_fail_rate', operator: 'gte', threshold: 0.25, window_hours: 6, min_sample: 10,
    description: 'Samsung Pay failures elevated over 6h — early degradation on the new method before it becomes a full outage.',
    runbook: '1) Troubleshoot → Payment, Samsung Pay: check the leading gateway code · message. 2) Watch the trend toward the P1 threshold. 3) Sample a few declines to tell a customer-side cause (e.g. tokenisation/3DS) from a UPG-side one. 4) Pre-warn the Samsung Pay integration owner if it is climbing.' },
  { key: 'ownership_fail_spike', name: 'Change-Ownership failure spike (P2)', severity: 'P2', team: 'Digital Ops',
    metric_key: 'ownership_fail_rate', operator: 'gte', threshold: 0.30, window_hours: 24, min_sample: 10,
    description: 'Ownership-transfer (checkout_type 5) plan-change step failing above threshold — number-transfer completions dropping.',
    runbook: '1) Troubleshoot → Change Ownership: open a failing case and read its detail. 2) Split cause: the Nafath transfer_ownership authorize step vs the BSS plan-change for the new owner. 3) If Nafath, check the identity path; if BSS, check the change-plan API. 4) Escalate to Digital Ops L2 if systemic.' },
  { key: 'recharge_fail_spike', name: 'Recharge / renewal failure spike (P2)', severity: 'P2', team: 'Digital Ops',
    metric_key: 'recharge_fail_rate', operator: 'gte', threshold: 0.30, window_hours: 3, min_sample: 20,
    description: 'Plan renewal / recharge payments (checkout_type 6) failing above threshold over 3h — existing customers cannot top up / renew.',
    runbook: '1) Troubleshoot → Payment: filter to the renewal flow and check the leading gateway + top decline code. 2) Compare with the overall payment failure rate — renewal-only spike points at the renewal checkout/plan, not all payments. 3) Check the renewal plan catalogue / pricing service if declines are systemic. 4) Escalate to Payments/BSS L2.' },
  { key: 'courier_partner_down', name: 'Courier partner failing (P2)', severity: 'P2', team: 'Digital Ops',
    metric_key: 'courier_worst_fail_rate', operator: 'gte', threshold: 0.40, window_hours: 24, min_sample: 20,
    description: 'At least one courier is failing/returning ≥40% of shipments (with a meaningful sample) — a single-partner outage the blended delivery rate would hide.',
    runbook: '1) Troubleshoot → Delivery: sort by vendor to see which courier is breaching (SMSA/OTO/Barq/iMile/STCC/etc.). 2) One courier → contact that partner and check their status callbacks/webhook. 3) If it is the default courier, consider rerouting new shipments. 4) Engage the logistics owner.' },
  { key: 'conversion_drop', name: 'Onboarding conversion drop (P2)', severity: 'P2', team: 'Sales Ops',
    metric_key: 'onboarding_conversion', operator: 'lte', threshold: 0.02, window_hours: 24, min_sample: 50,
    description: 'Completed/created conversion near zero (baseline ~4–5%; low value partly reflects the completed-flag replica lag).',
    runbook: '1) Completed/created conversion near zero. 2) Caveat: partly reflects the completed-flag replica lag — verify against a live source before escalating. 3) If genuinely low, walk the funnel (order → eligibility → payment → activation) for the breaking step and link the matching alert. 4) Sales Ops + Digital Ops jointly.' },
  { key: 'offhours_orders', name: 'Off-hours unusual activity (P2)', severity: 'P2', team: 'Digital Ops',
    metric_key: 'offhours_orders', operator: 'gte', threshold: 30, window_hours: 3, min_sample: 0,
    active_from: 1, active_to: 6, description: 'Order attempts during the 01:00–06:00 KSA dead window (test/automation/fraud).',
    runbook: '1) Order attempts in the KSA dead window — usually test/automation, occasionally fraud. 2) Troubleshoot: inspect the sources/IPs and whether the orders complete. 3) A burst from one source → flag for fraud/security review. 4) Benign if it is known automation.' },
  { key: 'dealer_activity_drop', name: 'Working-hours dealer activity drop (P2)', severity: 'P2', team: 'Sales Ops',
    metric_key: 'dealer_activity', operator: 'lte', threshold: 2, window_hours: 6, min_sample: 0,
    active_from: 9, active_to: 22, description: 'Dealer (DMS) completed-order volume collapsed during dealer hours (data-dependent — dealer feed may be absent in the replica).',
    runbook: '1) Dealer (DMS) completed-order volume collapsed in dealer hours. 2) First check data: the dealer feed may be absent/lagged in the replica (known caveat) — confirm against a live source. 3) If real, contact dealer-channel ops. 4) Do not page if it is a known feed gap.' },

  // ---------- P3 : watch ----------
  { key: 'abandoned_orders', name: 'Abandoned onboarding surge (P3)', severity: 'P3', team: 'Sales Ops',
    metric_key: 'onboarding_abandoned', operator: 'gte', threshold: 12000, window_hours: 24, min_sample: 0,
    description: 'Abandoned (never completed/activated) onboarding surging past the ~9.5k daily baseline.',
    runbook: '1) Abandoned onboarding surging past baseline. 2) Troubleshoot: check where users drop (eligibility / payment). 3) If one step failure rate rose, that is the cause — link to the matching alert. 4) Watch-level; act if a specific step is breaking.' },
  { key: 'volume_drop', name: 'Payment volume drop (P3)', severity: 'P3', team: 'Digital Ops',
    metric_key: 'payment_volume', operator: 'lte', threshold: 20, window_hours: 3, min_sample: 0,
    active_from: 9, active_to: 22, description: 'Successful payment volume unusually low during business hours.',
    runbook: '1) Successful payment volume unusually low in business hours. 2) Cross-check the payment failure rate and order volume — fewer attempts, or more failures? 3) If failures are normal but volume is down, it is demand/upstream traffic, not a payment fault. 4) Watch-level.' }
];

module.exports = { CATALOG, RULES };
